In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('chest_elec.csv-sub03')

In [3]:
df1

        Timestamp (microseconds)  Sample (V)
0               1614622319711059   -0.016639
1               1614622319715061   -0.016189
2               1614622319719063   -0.015765
3               1614622319723065   -0.015383
4               1614622319727068   -0.015051
...                          ...         ...
678437          1614625036452579   -0.010613
678438          1614625036456582    0.003837
678439          1614625036460585   -0.001745
678440          1614625036464588   -0.013457
678441          1614625036468591   -0.012847

[678442 rows x 2 columns]

In [4]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-01 18:11:59.711059')

In [5]:
start = pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=14, second=40)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=15, second=40)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-5-8b430a89cfb6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

       Timestamp (microseconds)  Sample (V)             Activity_Label
40036          1614622480002534   -0.010743  Forward and backward step
40037          1614622480006538   -0.010743  Forward and backward step
40038          1614622480010542   -0.010749  Forward and backward step
40039          1614622480014546   -0.010718  Forward and backward step
40040          1614622480018550   -0.010669  Forward and backward step
...                         ...         ...                        ...
55017          1614622539982933   -0.010213  Forward and backward step
55018          1614622539986937   -0.010133  Forward and backward step
55019          1614622539990941   -0.009973  Forward and backward step
55020          1614622539994945   -0.009776  Forward and backward step
55021          1614622539998949   -0.009598  Forward and backward step

[14986 rows x 3 columns]

In [6]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=16, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=17, second=6)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-6-64e3e28cbbf9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

       Timestamp (microseconds)  Sample (V) Activity_Label
61516          1614622566003225   -0.010072  Sideward step
61517          1614622566007229   -0.010275  Sideward step
61518          1614622566011233   -0.010435  Sideward step
61519          1614622566015237   -0.010496  Sideward step
61520          1614622566019241   -0.010552  Sideward step
...                         ...         ...            ...
76497          1614622625983691   -0.009899  Sideward step
76498          1614622625987695   -0.009899  Sideward step
76499          1614622625991699   -0.009918  Sideward step
76500          1614622625995703   -0.009918  Sideward step
76501          1614622625999707   -0.009912  Sideward step

[14986 rows x 3 columns]

In [7]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=19, second=9)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=20, second=9)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-7-e5ebd074c4e9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

        Timestamp (microseconds)  Sample (V) Activity_Label
107222          1614622749000565   -0.011727        Pushups
107223          1614622749004569   -0.011598        Pushups
107224          1614622749008573   -0.011475        Pushups
107225          1614622749012577   -0.011389        Pushups
107226          1614622749016581   -0.011364        Pushups
...                          ...         ...            ...
122203          1614622808983870   -0.009979        Pushups
122204          1614622808987874   -0.010853        Pushups
122205          1614622808991878   -0.011684        Pushups
122206          1614622808995882   -0.011555        Pushups
122207          1614622808999886   -0.010724        Pushups

[14986 rows x 3 columns]

In [8]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=22, second=23)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=23, second=23)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-8-b55a38eee79a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Sample (V),Activity_Label
155674,1614622943001843,-0.010909,Hip raise step with punches in the air
155675,1614622943005847,-0.010940,Hip raise step with punches in the air
155676,1614622943009851,-0.010952,Hip raise step with punches in the air
155677,1614622943013855,-0.010970,Hip raise step with punches in the air
155678,1614622943017859,-0.010983,Hip raise step with punches in the air
...,...,...,...
170654,1614623002982480,-0.010183,Hip raise step with punches in the air
170655,1614623002986484,-0.010139,Hip raise step with punches in the air
170656,1614623002990488,-0.010090,Hip raise step with punches in the air
170657,1614623002994492,-0.010053,Hip raise step with punches in the air
170658,1614623002998496,-0.010023,Hip raise step with punches in the air

In [9]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=25, second=26)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=26, second=26)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-9-1a09d863ae9a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

        Timestamp (microseconds)  Sample (V)          Activity_Label
201377          1614623126000355   -0.010995  Front and back scooter
201378          1614623126004359   -0.010989  Front and back scooter
201379          1614623126008363   -0.010964  Front and back scooter
201380          1614623126012367   -0.010958  Front and back scooter
201381          1614623126016371   -0.010958  Front and back scooter
...                          ...         ...                     ...
216357          1614623185980540   -0.010392  Front and back scooter
216358          1614623185984544   -0.010386  Front and back scooter
216359          1614623185988548   -0.010386  Front and back scooter
216360          1614623185992552   -0.010386  Front and back scooter
216361          1614623185996556   -0.010392  Front and back scooter

[14985 rows x 3 columns]

In [10]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=27, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=28, second=57)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-10-9e111bdf0e8f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

        Timestamp (microseconds)  Sample (V) Activity_Label
239090          1614623277002645   -0.010767  Belly Scooter
239091          1614623277006649   -0.010773  Belly Scooter
239092          1614623277010653   -0.010755  Belly Scooter
239093          1614623277014657   -0.010743  Belly Scooter
239094          1614623277018661   -0.010706  Belly Scooter
...                          ...         ...            ...
254070          1614623336982129   -0.009198  Belly Scooter
254071          1614623336986133   -0.009204  Belly Scooter
254072          1614623336990137   -0.009222  Belly Scooter
254073          1614623336994141   -0.009235  Belly Scooter
254074          1614623336998145   -0.009229  Belly Scooter

[14985 rows x 3 columns]

In [11]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=28, second=58)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=29, second=58)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-11-a09fb26a9dfc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

        Timestamp (microseconds)  Sample (V)    Activity_Label
254325          1614623338003162   -0.010533  Circular Scooter
254326          1614623338007166   -0.010527  Circular Scooter
254327          1614623338011170   -0.010521  Circular Scooter
254328          1614623338015174   -0.010509  Circular Scooter
254329          1614623338019178   -0.010490  Circular Scooter
...                          ...         ...               ...
269305          1614623397982829   -0.010669  Circular Scooter
269306          1614623397986833   -0.010706  Circular Scooter
269307          1614623397990837   -0.010749  Circular Scooter
269308          1614623397994841   -0.010767  Circular Scooter
269309          1614623397998845   -0.010755  Circular Scooter

[14985 rows x 3 columns]

In [12]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=31, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=32, second=5)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-12-0ac04b7feb76>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

        Timestamp (microseconds)  Sample (V) Activity_Label
286043          1614623465001807   -0.010663   Cycling Slow
286044          1614623465005811   -0.010669   Cycling Slow
286045          1614623465009815   -0.010663   Cycling Slow
286046          1614623465013819   -0.010663   Cycling Slow
286047          1614623465017823   -0.010669   Cycling Slow
...                          ...         ...            ...
301023          1614623524981779   -0.010490   Cycling Slow
301024          1614623524985783   -0.010515   Cycling Slow
301025          1614623524989787   -0.010453   Cycling Slow
301026          1614623524993791   -0.010287   Cycling Slow
301027          1614623524997795   -0.010066   Cycling Slow

[14985 rows x 3 columns]

In [13]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=32, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=33, second=6)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-13-0b8f3aadaaa0>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

        Timestamp (microseconds)  Sample (V) Activity_Label
301278          1614623526002782   -0.010866   Cycling Fast
301279          1614623526006786   -0.010878   Cycling Fast
301280          1614623526010790   -0.010878   Cycling Fast
301281          1614623526014794   -0.010866   Cycling Fast
301282          1614623526018798   -0.010866   Cycling Fast
...                          ...         ...            ...
316258          1614623585980130   -0.010669   Cycling Fast
316259          1614623585984134   -0.010663   Cycling Fast
316260          1614623585988138   -0.010650   Cycling Fast
316261          1614623585992142   -0.010644   Cycling Fast
316262          1614623585996146   -0.010632   Cycling Fast

[14985 rows x 3 columns]

In [14]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=36, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=37, second=46)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-14-1b9c9b4cf6bb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
371210          1614623806000960   -0.010780  Medicine_ball
371211          1614623806004964   -0.010620  Medicine_ball
371212          1614623806008968   -0.010472  Medicine_ball
371213          1614623806012972   -0.010466  Medicine_ball
371214          1614623806016976   -0.010466  Medicine_ball
...                          ...         ...            ...
386190          1614623865981725   -0.010546  Medicine_ball
386191          1614623865985729   -0.010564  Medicine_ball
386192          1614623865989733   -0.010632  Medicine_ball
386193          1614623865993737   -0.010736  Medicine_ball
386194          1614623865997741   -0.010841  Medicine_ball

[14985 rows x 3 columns]

In [15]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=37, second=47)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=38, second=48)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-15-ba8de3496157>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

        Timestamp (microseconds)  Sample (V)              Activity_Label
386445          1614623867002759   -0.010540  Medicine ball with burpies
386446          1614623867006763   -0.010540  Medicine ball with burpies
386447          1614623867010767   -0.010558  Medicine ball with burpies
386448          1614623867014771   -0.010601  Medicine ball with burpies
386449          1614623867018775   -0.010626  Medicine ball with burpies
...                          ...         ...                         ...
401674          1614623927979985   -0.010355  Medicine ball with burpies
401675          1614623927983989   -0.010349  Medicine ball with burpies
401676          1614623927987993   -0.010392  Medicine ball with burpies
401677          1614623927991997   -0.010490  Medicine ball with burpies
401678          1614623927996001   -0.010533  Medicine ball with burpies

[15234 rows x 3 columns]

In [16]:
df2=pd.read_csv('chest_elec.csv-sub03-folder02')

In [17]:
df2

        Timestamp (microseconds)  Sample (V)
0               1614625157160553   -0.006601
1               1614625157164557   -0.006441
2               1614625157168561   -0.006274
3               1614625157172565   -0.006133
4               1614625157176569   -0.006010
...                          ...         ...
728945          1614628077874036   -0.003745
728946          1614628077878041   -0.004213
728947          1614628077882046   -0.004010
728948          1614628077886051   -0.004022
728949          1614628077890056   -0.003862

[728950 rows x 2 columns]

In [18]:
pd.Timestamp(df2['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-01 18:59:17.160553')

In [45]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=0, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=1, second=51)
end_ts=int(end.timestamp() * 1e6)

DF12= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-45-cedc23365675>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

       Timestamp (microseconds)  Sample (V) Activity_Label
23421          1614625251002421   -0.004416     punch ball
23422          1614625251006427   -0.004631     punch ball
23423          1614625251010434   -0.004810     punch ball
23424          1614625251014434   -0.004914     punch ball
23425          1614625251018441   -0.004976     punch ball
...                         ...         ...            ...
38390          1614625310983783   -0.004650     punch ball
38391          1614625310987791   -0.004674     punch ball
38392          1614625310991798   -0.004687     punch ball
38393          1614625310995805   -0.004693     punch ball
38394          1614625310999813   -0.004724     punch ball

[14974 rows x 3 columns]

In [46]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=2, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=3, second=40)
end_ts=int(end.timestamp() * 1e6)

DF13= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-46-42ae15fc3d48>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

       Timestamp (microseconds)  Sample (V)   Activity_Label
50623          1614625360003629   -0.004182  Squarts Toe ups
50624          1614625360007637   -0.004182  Squarts Toe ups
50625          1614625360011644   -0.004188  Squarts Toe ups
50626          1614625360015651   -0.004200  Squarts Toe ups
50627          1614625360019659   -0.004194  Squarts Toe ups
...                         ...         ...              ...
65591          1614625419983369   -0.006022  Squarts Toe ups
65592          1614625419987377   -0.006016  Squarts Toe ups
65593          1614625419991384   -0.005905  Squarts Toe ups
65594          1614625419995391   -0.005690  Squarts Toe ups
65595          1614625419999399   -0.005394  Squarts Toe ups

[14973 rows x 3 columns]

In [47]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=5, second=10)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=6, second=10)
end_ts=int(end.timestamp() * 1e6)

DF14= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-47-05f6b27f8ab2>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

        Timestamp (microseconds)  Sample (V) Activity_Label
88055           1614625510001405   -0.002551   Weight lifts
88056           1614625510005413   -0.002557   Weight lifts
88057           1614625510009420   -0.002569   Weight lifts
88058           1614625510013427   -0.002563   Weight lifts
88059           1614625510017435   -0.002569   Weight lifts
...                          ...         ...            ...
103023          1614625569982519   -0.003025   Weight lifts
103024          1614625569986526   -0.002883   Weight lifts
103025          1614625569990533   -0.002668   Weight lifts
103026          1614625569994541   -0.002526   Weight lifts
103027          1614625569998548   -0.002656   Weight lifts

[14973 rows x 3 columns]

In [48]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=7, second=21)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=8, second=21)
end_ts=int(end.timestamp() * 1e6)

DF15= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-48-59c110aae176>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

        Timestamp (microseconds)  Sample (V)      Activity_Label
120745          1614625641000158   -0.004859  Heavy Weight lifts
120746          1614625641004165   -0.004034  Heavy Weight lifts
120747          1614625641008173   -0.004114  Heavy Weight lifts
120748          1614625641012180   -0.003862  Heavy Weight lifts
120749          1614625641016187   -0.004244  Heavy Weight lifts
...                          ...         ...                 ...
135713          1614625700982248   -0.004188  Heavy Weight lifts
135714          1614625700986255   -0.004244  Heavy Weight lifts
135715          1614625700990263   -0.004194  Heavy Weight lifts
135716          1614625700994270   -0.003917  Heavy Weight lifts
135717          1614625700998277   -0.004145  Heavy Weight lifts

[14973 rows x 3 columns]

In [49]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=9, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=10, second=45)
end_ts=int(end.timestamp() * 1e6)

DF16= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-49-5fc004af0bcf>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

        Timestamp (microseconds)  Sample (V)          Activity_Label
156680          1614625785003906   -0.001886  Forward Lunges on Bosu
156681          1614625785007913   -0.001751  Forward Lunges on Bosu
156682          1614625785011921   -0.001665  Forward Lunges on Bosu
156683          1614625785015928   -0.001665  Forward Lunges on Bosu
156684          1614625785019935   -0.001812  Forward Lunges on Bosu
...                          ...         ...                     ...
171647          1614625844980161   -0.002988  Forward Lunges on Bosu
171648          1614625844984169   -0.003080  Forward Lunges on Bosu
171649          1614625844988176   -0.003696  Forward Lunges on Bosu
171650          1614625844992183   -0.003320  Forward Lunges on Bosu
171651          1614625844996191   -0.003603  Forward Lunges on Bosu

[14972 rows x 3 columns]

In [50]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=11, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=12, second=51)
end_ts=int(end.timestamp() * 1e6)

DF17= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-50-3272f14d181b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
188123          1614625911001398   -0.003782  Split squart left on Bosu
188124          1614625911005371   -0.003942  Split squart left on Bosu
188125          1614625911009378   -0.003948  Split squart left on Bosu
188126          1614625911013385   -0.003887  Split squart left on Bosu
188127          1614625911017393   -0.003880  Split squart left on Bosu
...                          ...         ...                        ...
203091          1614625970980772   -0.003468  Split squart left on Bosu
203092          1614625970984779   -0.003456  Split squart left on Bosu
203093          1614625970988786   -0.003450  Split squart left on Bosu
203094          1614625970992794   -0.003450  Split squart left on Bosu
203095          1614625970996801   -0.003437  Split squart left on Bosu

[14973 rows x 3 columns]

In [51]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=12, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=13, second=57)
end_ts=int(end.timestamp() * 1e6)

DF18= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-51-14524529af3b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

        Timestamp (microseconds)  Sample (V)              Activity_Label
204594          1614625977003601   -0.003905  Split squart right on Bosu
204595          1614625977007608   -0.004028  Split squart right on Bosu
204596          1614625977011615   -0.003856  Split squart right on Bosu
204597          1614625977015623   -0.003794  Split squart right on Bosu
204598          1614625977019630   -0.003850  Split squart right on Bosu
...                          ...         ...                         ...
219561          1614626036980283   -0.004311  Split squart right on Bosu
219562          1614626036984291   -0.004034  Split squart right on Bosu
219563          1614626036988298   -0.003825  Split squart right on Bosu
219564          1614626036992305   -0.004083  Split squart right on Bosu
219565          1614626036996313   -0.004225  Split squart right on Bosu

[14972 rows x 3 columns]

In [52]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=14, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=15, second=45)
end_ts=int(end.timestamp() * 1e6)

DF19= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-52-2ab3e1100cc5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
231545          1614626085003286   -0.004416  plank pie on Bosu
231546          1614626085007293   -0.004416  plank pie on Bosu
231547          1614626085011301   -0.004379  plank pie on Bosu
231548          1614626085015308   -0.004354  plank pie on Bosu
231549          1614626085019315   -0.004471  plank pie on Bosu
...                          ...         ...                ...
246513          1614626144982015   -0.004637  plank pie on Bosu
246514          1614626144986022   -0.004176  plank pie on Bosu
246515          1614626144990028   -0.004305  plank pie on Bosu
246516          1614626144994035   -0.004354  plank pie on Bosu
246517          1614626144998042   -0.004342  plank pie on Bosu

[14973 rows x 3 columns]

In [53]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=19, second=12)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=20, second=12)
end_ts=int(end.timestamp() * 1e6)

DF20= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-53-884dc8445d69>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
298181          1614626352000209   -0.006404  plank top on Bosu
298182          1614626352004216   -0.006404  plank top on Bosu
298183          1614626352008223   -0.006398  plank top on Bosu
298184          1614626352012230   -0.006391  plank top on Bosu
298185          1614626352016236   -0.006354  plank top on Bosu
...                          ...         ...                ...
313153          1614626411983118   -0.004016  plank top on Bosu
313154          1614626411987124   -0.004065  plank top on Bosu
313155          1614626411991130   -0.003967  plank top on Bosu
313156          1614626411995136   -0.004028  plank top on Bosu
313157          1614626411999142   -0.003997  plank top on Bosu

[14977 rows x 3 columns]

In [54]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=22, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=23, second=14)
end_ts=int(end.timestamp() * 1e6)

DF21= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-54-492fa303cdda>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

        Timestamp (microseconds)  Sample (V) Activity_Label
343620          1614626534002044   -0.003807   dips on Bosu
343621          1614626534006050   -0.003800   dips on Bosu
343622          1614626534010055   -0.003794   dips on Bosu
343623          1614626534014061   -0.003794   dips on Bosu
343624          1614626534018066   -0.003807   dips on Bosu
...                          ...         ...            ...
358593          1614626593980722   -0.003979   dips on Bosu
358594          1614626593984727   -0.004003   dips on Bosu
358595          1614626593988733   -0.003997   dips on Bosu
358596          1614626593992739   -0.004047   dips on Bosu
358597          1614626593996745   -0.004077   dips on Bosu

[14978 rows x 3 columns]

In [55]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=24, second=24)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=25, second=24)
end_ts=int(end.timestamp() * 1e6)

DF22= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-55-a9cc1792e7bd>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

        Timestamp (microseconds)  Sample (V)                Activity_Label
376071          1614626664001582   -0.004010  moveforward backward on Bosu
376072          1614626664005588   -0.004028  moveforward backward on Bosu
376073          1614626664009595   -0.004047  moveforward backward on Bosu
376074          1614626664013601   -0.004040  moveforward backward on Bosu
376075          1614626664017607   -0.004034  moveforward backward on Bosu
...                          ...         ...                           ...
391042          1614626723983963   -0.004539  moveforward backward on Bosu
391043          1614626723987970   -0.004551  moveforward backward on Bosu
391044          1614626723991976   -0.004545  moveforward backward on Bosu
391045          1614626723995983   -0.004545  moveforward backward on Bosu
391046          1614626723999990   -0.004539  moveforward backward on Bosu

[14976 rows x 3 columns]

In [56]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=26, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=27, second=30)
end_ts=int(end.timestamp() * 1e6)

DF23= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-56-e8db329940eb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)            Activity_Label
407518          1614626790001918   -0.004200  Left leg Hip ups on Bosu
407519          1614626790005926   -0.004194  Left leg Hip ups on Bosu
407520          1614626790009933   -0.004194  Left leg Hip ups on Bosu
407521          1614626790013940   -0.004188  Left leg Hip ups on Bosu
407522          1614626790017948   -0.004170  Left leg Hip ups on Bosu
...                          ...         ...                       ...
422486          1614626849980102   -0.003942  Left leg Hip ups on Bosu
422487          1614626849984110   -0.003948  Left leg Hip ups on Bosu
422488          1614626849988117   -0.003936  Left leg Hip ups on Bosu
422489          1614626849992124   -0.003942  Left leg Hip ups on Bosu
422490          1614626849996132   -0.003954  Left leg Hip ups on Bosu

[14973 rows x 3 columns]

In [57]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=27, second=31)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=28, second=31)
end_ts=int(end.timestamp() * 1e6)

DF24= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-57-5846fc2475d7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
422741          1614626851001936   -0.004127  right leg Hip ups on Bosu
422742          1614626851005943   -0.004127  right leg Hip ups on Bosu
422743          1614626851009950   -0.004151  right leg Hip ups on Bosu
422744          1614626851013958   -0.004151  right leg Hip ups on Bosu
422745          1614626851017965   -0.004127  right leg Hip ups on Bosu
...                          ...         ...                        ...
437709          1614626910983358   -0.004447  right leg Hip ups on Bosu
437710          1614626910987365   -0.004465  right leg Hip ups on Bosu
437711          1614626910991373   -0.004465  right leg Hip ups on Bosu
437712          1614626910995380   -0.004496  right leg Hip ups on Bosu
437713          1614626910999387   -0.004490  right leg Hip ups on Bosu

[14973 rows x 3 columns]

In [58]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=29, second=15)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=30, second=13)
end_ts=int(end.timestamp() * 1e6)

DF25= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-58-48af10944a48>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

        Timestamp (microseconds)  Sample (V)         Activity_Label
448693          1614626955001066   -0.003862  V-Shift Swift on Bosu
448694          1614626955005073   -0.003930  V-Shift Swift on Bosu
448695          1614626955009081   -0.004022  V-Shift Swift on Bosu
448696          1614626955013088   -0.004108  V-Shift Swift on Bosu
448697          1614626955017095   -0.004108  V-Shift Swift on Bosu
...                          ...         ...                    ...
463161          1614627012981356   -0.004053  V-Shift Swift on Bosu
463162          1614627012985364   -0.004059  V-Shift Swift on Bosu
463163          1614627012989371   -0.004059  V-Shift Swift on Bosu
463164          1614627012993379   -0.004053  V-Shift Swift on Bosu
463165          1614627012997387   -0.004065  V-Shift Swift on Bosu

[14473 rows x 3 columns]

In [59]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=32, second=50)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=33, second=20)
end_ts=int(end.timestamp() * 1e6)

DF26= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-59-82278fe99667>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

        Timestamp (microseconds)  Sample (V)    Activity_Label
502342          1614627170000650   -0.003893  Freestyle Boxing
502343          1614627170004658   -0.003880  Freestyle Boxing
502344          1614627170008666   -0.003880  Freestyle Boxing
502345          1614627170012673   -0.003905  Freestyle Boxing
502346          1614627170016681   -0.003923  Freestyle Boxing
...                          ...         ...               ...
509823          1614627199980054   -0.004157  Freestyle Boxing
509824          1614627199984062   -0.004151  Freestyle Boxing
509825          1614627199988069   -0.004164  Freestyle Boxing
509826          1614627199992076   -0.004164  Freestyle Boxing
509827          1614627199996084   -0.004170  Freestyle Boxing

[7486 rows x 3 columns]

In [60]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=33, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=33, second=55)
end_ts=int(end.timestamp() * 1e6)

DF27= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-60-7ec7962534a8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

        Timestamp (microseconds)  Sample (V)           Activity_Label
513572          1614627215003177   -0.004631  Left_Right_Punches_flip
513573          1614627215007185   -0.004619  Left_Right_Punches_flip
513574          1614627215011192   -0.004594  Left_Right_Punches_flip
513575          1614627215015199   -0.004564  Left_Right_Punches_flip
513576          1614627215019207   -0.004557  Left_Right_Punches_flip
...                          ...         ...                      ...
518558          1614627234982792   -0.004003  Left_Right_Punches_flip
518559          1614627234986799   -0.004003  Left_Right_Punches_flip
518560          1614627234990806   -0.003985  Left_Right_Punches_flip
518561          1614627234994814   -0.003985  Left_Right_Punches_flip
518562          1614627234998821   -0.004022  Left_Right_Punches_flip

[4991 rows x 3 columns]

In [61]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=37, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=38, second=5)
end_ts=int(end.timestamp() * 1e6)

DF28= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-61-941e99927124>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

        Timestamp (microseconds)  Sample (V)    Activity_Label
573472          1614627455000312   -0.004200  left_Right_Punch
573473          1614627455004319   -0.004360  left_Right_Punch
573474          1614627455008325   -0.004496  left_Right_Punch
573475          1614627455012332   -0.004576  left_Right_Punch
573476          1614627455016338   -0.004588  left_Right_Punch
...                          ...         ...               ...
580955          1614627484980919   -0.004114  left_Right_Punch
580956          1614627484984926   -0.004071  left_Right_Punch
580957          1614627484988932   -0.004102  left_Right_Punch
580958          1614627484992939   -0.004114  left_Right_Punch
580959          1614627484996945   -0.004139  left_Right_Punch

[7488 rows x 3 columns]

In [62]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=38, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=39, second=6)
end_ts=int(end.timestamp() * 1e6)

DF29= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-62-3dc3ac3eb8a5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

        Timestamp (microseconds)  Sample (V) Activity_Label
588947          1614627517001273   -0.004176       one_twos
588948          1614627517005280   -0.004188       one_twos
588949          1614627517009287   -0.004200       one_twos
588950          1614627517013294   -0.004200       one_twos
588951          1614627517017301   -0.004207       one_twos
...                          ...         ...            ...
596180          1614627545981205   -0.003074       one_twos
596181          1614627545985211   -0.003043       one_twos
596182          1614627545989218   -0.003197       one_twos
596183          1614627545993225   -0.003296       one_twos
596184          1614627545997232   -0.003333       one_twos

[7238 rows x 3 columns]

In [63]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=39, second=19)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=39, second=49)
end_ts=int(end.timestamp() * 1e6)

DF30= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-63-075f6d0c4ad7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

        Timestamp (microseconds)  Sample (V) Activity_Label
599430          1614627559002870   -0.003831          hooks
599431          1614627559006877   -0.003837          hooks
599432          1614627559010884   -0.003819          hooks
599433          1614627559014891   -0.003745          hooks
599434          1614627559018898   -0.003683          hooks
...                          ...         ...            ...
606912          1614627588981077   -0.005357          hooks
606913          1614627588985084   -0.005579          hooks
606914          1614627588989091   -0.005628          hooks
606915          1614627588993097   -0.005542          hooks
606916          1614627588997104   -0.005444          hooks

[7487 rows x 3 columns]

In [64]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=41, second=20)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=41, second=50)
end_ts=int(end.timestamp() * 1e6)

DF31= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-64-82629abdddcb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

        Timestamp (microseconds)  Sample (V) Activity_Label
629628          1614627680000337   -0.003690     Upper_cuts
629629          1614627680004344   -0.003573     Upper_cuts
629630          1614627680008351   -0.003413     Upper_cuts
629631          1614627680012358   -0.003308     Upper_cuts
629632          1614627680016365   -0.003160     Upper_cuts
...                          ...         ...            ...
637111          1614627709983368   -0.008256     Upper_cuts
637112          1614627709987375   -0.008189     Upper_cuts
637113          1614627709991382   -0.007733     Upper_cuts
637114          1614627709995389   -0.007561     Upper_cuts
637115          1614627709999395   -0.007050     Upper_cuts

[7488 rows x 3 columns]

In [65]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=43, second=25)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=44, second=5)
end_ts=int(end.timestamp() * 1e6)

DF32= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-65-5360007f70e6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

        Timestamp (microseconds)  Sample (V) Activity_Label
660828          1614627805001262   -0.003117            run
660829          1614627805005269   -0.003111            run
660830          1614627805009275   -0.003099            run
660831          1614627805013281   -0.003080            run
660832          1614627805017288   -0.003068            run
...                          ...         ...            ...
670808          1614627844983295   -0.004133            run
670809          1614627844987301   -0.004127            run
670810          1614627844991308   -0.004108            run
670811          1614627844995314   -0.004096            run
670812          1614627844999321   -0.004102            run

[9985 rows x 3 columns]

In [43]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=45, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=46, second=10)
end_ts=int(end.timestamp() * 1e6)

DF33= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-43-259a10fd93ee>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

        Timestamp (microseconds)  Sample (V)       Activity_Label
694525          1614627940000378   -0.004047  Punch_down_Up_Hooks
694526          1614627940004385   -0.004065  Punch_down_Up_Hooks
694527          1614627940008391   -0.004053  Punch_down_Up_Hooks
694528          1614627940012397   -0.004047  Punch_down_Up_Hooks
694529          1614627940016404   -0.004053  Punch_down_Up_Hooks
...                          ...         ...                  ...
702008          1614627969981168   -0.001597  Punch_down_Up_Hooks
702009          1614627969985175   -0.001591  Punch_down_Up_Hooks
702010          1614627969989182   -0.001517  Punch_down_Up_Hooks
702011          1614627969993189   -0.001609  Punch_down_Up_Hooks
702012          1614627969997196   -0.001603  Punch_down_Up_Hooks

[7488 rows x 3 columns]

In [66]:
sub03_final_chest_elec=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub03_final_chest_elec

        Timestamp (microseconds)  Sample (V)             Activity_Label
0               1614622480002534   -0.010743  Forward and backward step
1               1614622480006538   -0.010743  Forward and backward step
2               1614622480010542   -0.010749  Forward and backward step
3               1614622480014546   -0.010718  Forward and backward step
4               1614622480018550   -0.010669  Forward and backward step
...                          ...         ...                        ...
433866          1614627969981168   -0.001597        Punch_down_Up_Hooks
433867          1614627969985175   -0.001591        Punch_down_Up_Hooks
433868          1614627969989182   -0.001517        Punch_down_Up_Hooks
433869          1614627969993189   -0.001609        Punch_down_Up_Hooks
433870          1614627969997196   -0.001603        Punch_down_Up_Hooks

[433871 rows x 3 columns]

In [67]:
sub03_final_chest_elec.to_csv('final_cleaned_chest_elec-sub03.csv-sub03')