In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('chest_elec.csv-sub02')

In [3]:
df1

        Timestamp (microseconds)  Sample (V)
0               1614546068813324   -0.016374
1               1614546068817325   -0.015937
2               1614546068821327   -0.015512
3               1614546068825328   -0.015137
4               1614546068829330   -0.014798
...                          ...         ...
367093          1614547538283012   -0.010109
367094          1614547538287016   -0.010103
367095          1614547538291020   -0.010103
367096          1614547538295024   -0.010103
367097          1614547538299028   -0.010127

[367098 rows x 2 columns]

In [4]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-02-28 21:01:08.813324')

In [5]:
start = pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=1, second=42)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=2, second=42)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-5-ab7a8690006c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

       Timestamp (microseconds)  Sample (V)             Activity_Label
8292           1614546102002668   -0.010540  Forward and backward step
8293           1614546102006671   -0.010546  Forward and backward step
8294           1614546102010673   -0.010546  Forward and backward step
8295           1614546102014676   -0.010552  Forward and backward step
8296           1614546102018707   -0.010558  Forward and backward step
...                         ...         ...                        ...
23276          1614546161980392   -0.010435  Forward and backward step
23277          1614546161984395   -0.010435  Forward and backward step
23278          1614546161988398   -0.010429  Forward and backward step
23279          1614546161992401   -0.010447  Forward and backward step
23280          1614546161996404   -0.010429  Forward and backward step

[14989 rows x 3 columns]

In [6]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=2, second=58)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=3, second=58)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-6-08206e5f85b5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

       Timestamp (microseconds)  Sample (V) Activity_Label
27279          1614546178003709   -0.010650  Sideward step
27280          1614546178007712   -0.010644  Sideward step
27281          1614546178011715   -0.010644  Sideward step
27282          1614546178015718   -0.010638  Sideward step
27283          1614546178019721   -0.010626  Sideward step
...                         ...         ...            ...
42263          1614546237983299   -0.010613  Sideward step
42264          1614546237987302   -0.010589  Sideward step
42265          1614546237991305   -0.010706  Sideward step
42266          1614546237995309   -0.010823  Sideward step
42267          1614546237999312   -0.010860  Sideward step

[14989 rows x 3 columns]

In [7]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=4, second=42)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=5, second=42)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-7-2888d9db6424>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

       Timestamp (microseconds)  Sample (V) Activity_Label
53260          1614546282003805   -0.010133        Pushups
53261          1614546282007808   -0.010152        Pushups
53262          1614546282011811   -0.010090        Pushups
53263          1614546282015814   -0.010139        Pushups
53264          1614546282019817   -0.010127        Pushups
...                         ...         ...            ...
68243          1614546341980277   -0.010823        Pushups
68244          1614546341984280   -0.010767        Pushups
68245          1614546341988283   -0.010829        Pushups
68246          1614546341992286   -0.010890        Pushups
68247          1614546341996289   -0.010841        Pushups

[14988 rows x 3 columns]

In [8]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=6, second=26)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=7, second=26)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-8-569cdf13fc52>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Sample (V),Activity_Label
79240,1614546386000630,-0.010589,Hip raise step with punches in the air
79241,1614546386004633,-0.010589,Hip raise step with punches in the air
79242,1614546386008636,-0.010589,Hip raise step with punches in the air
79243,1614546386012639,-0.010595,Hip raise step with punches in the air
79244,1614546386016642,-0.010595,Hip raise step with punches in the air
...,...,...,...
94224,1614546445982265,-0.010183,Hip raise step with punches in the air
94225,1614546445986268,-0.010189,Hip raise step with punches in the air
94226,1614546445990271,-0.010146,Hip raise step with punches in the air
94227,1614546445994274,-0.010121,Hip raise step with punches in the air
94228,1614546445998277,-0.010250,Hip raise step with punches in the air

In [9]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=8, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=9, second=6)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-9-fa535ec846bc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

        Timestamp (microseconds)  Sample (V)          Activity_Label
104221          1614546486001836   -0.010724  Front and back scooter
104222          1614546486005840   -0.010718  Front and back scooter
104223          1614546486009843   -0.010706  Front and back scooter
104224          1614546486013847   -0.010693  Front and back scooter
104225          1614546486017851   -0.010675  Front and back scooter
...                          ...         ...                     ...
119204          1614546545980281   -0.010256  Front and back scooter
119205          1614546545984285   -0.010263  Front and back scooter
119206          1614546545988289   -0.010269  Front and back scooter
119207          1614546545992292   -0.010269  Front and back scooter
119208          1614546545996296   -0.010269  Front and back scooter

[14988 rows x 3 columns]

In [10]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=9, second=42)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=10, second=42)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-10-fefe9f7bffac>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

        Timestamp (microseconds)  Sample (V) Activity_Label
128202          1614546582001072   -0.010256  Belly Scooter
128203          1614546582005075   -0.010238  Belly Scooter
128204          1614546582009079   -0.010232  Belly Scooter
128205          1614546582013082   -0.010220  Belly Scooter
128206          1614546582017086   -0.010201  Belly Scooter
...                          ...         ...            ...
143185          1614546641983514   -0.010810  Belly Scooter
143186          1614546641987518   -0.010835  Belly Scooter
143187          1614546641991521   -0.010853  Belly Scooter
143188          1614546641995525   -0.010829  Belly Scooter
143189          1614546641999529   -0.010804  Belly Scooter

[14988 rows x 3 columns]

In [11]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=10, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=11, second=48)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-11-0ce6205528b1>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

        Timestamp (microseconds)  Sample (V)    Activity_Label
144688          1614546648000797   -0.010816  Circular Scooter
144689          1614546648004800   -0.010823  Circular Scooter
144690          1614546648008804   -0.010816  Circular Scooter
144691          1614546648012807   -0.010829  Circular Scooter
144692          1614546648016845   -0.010853  Circular Scooter
...                          ...         ...               ...
159670          1614546707982044   -0.010866  Circular Scooter
159671          1614546707986047   -0.010841  Circular Scooter
159672          1614546707990051   -0.010767  Circular Scooter
159673          1614546707994054   -0.010700  Circular Scooter
159674          1614546707998058   -0.010656  Circular Scooter

[14987 rows x 3 columns]

In [12]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=13, second=39)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=14, second=39)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-12-6ca9c089f5db>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

        Timestamp (microseconds)  Sample (V) Activity_Label
187401          1614546819002676   -0.009844   Cycling Slow
187402          1614546819006679   -0.009850   Cycling Slow
187403          1614546819010683   -0.009850   Cycling Slow
187404          1614546819014686   -0.009844   Cycling Slow
187405          1614546819018690   -0.009844   Cycling Slow
...                          ...         ...            ...
202383          1614546878983400   -0.009696   Cycling Slow
202384          1614546878987403   -0.009709   Cycling Slow
202385          1614546878991407   -0.009727   Cycling Slow
202386          1614546878995411   -0.009776   Cycling Slow
202387          1614546878999414   -0.009850   Cycling Slow

[14987 rows x 3 columns]

In [13]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=14, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=15, second=40)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-13-e987b5c5c9ad>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

        Timestamp (microseconds)  Sample (V) Activity_Label
202637          1614546880000272   -0.009666   Cycling Fast
202638          1614546880004276   -0.009672   Cycling Fast
202639          1614546880008279   -0.009653   Cycling Fast
202640          1614546880012283   -0.009647   Cycling Fast
202641          1614546880016286   -0.009666   Cycling Fast
...                          ...         ...            ...
217620          1614546939980565   -0.011327   Cycling Fast
217621          1614546939984568   -0.011284   Cycling Fast
217622          1614546939988571   -0.011241   Cycling Fast
217623          1614546939992574   -0.011241   Cycling Fast
217624          1614546939996577   -0.011204   Cycling Fast

[14988 rows x 3 columns]

In [14]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=17, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=18, second=35)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-14-81a58fd31854>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
246355          1614547055002086   -0.011832  Medicine_ball
246356          1614547055006089   -0.011820  Medicine_ball
246357          1614547055010092   -0.011795  Medicine_ball
246358          1614547055014095   -0.011777  Medicine_ball
246359          1614547055018098   -0.011777  Medicine_ball
...                          ...         ...            ...
261340          1614547114982597   -0.011044  Medicine_ball
261341          1614547114986600   -0.011038  Medicine_ball
261342          1614547114990603   -0.010995  Medicine_ball
261343          1614547114994606   -0.010989  Medicine_ball
261344          1614547114998609   -0.010964  Medicine_ball

[14990 rows x 3 columns]

In [15]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=19, second=22)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=20, second=22)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-15-2f7dc500ac6a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

        Timestamp (microseconds)  Sample (V)              Activity_Label
273087          1614547162002007   -0.010447  Medicine ball with burpies
273088          1614547162006010   -0.010453  Medicine ball with burpies
273089          1614547162010013   -0.010447  Medicine ball with burpies
273090          1614547162014016   -0.010447  Medicine ball with burpies
273091          1614547162018019   -0.010447  Medicine ball with burpies
...                          ...         ...                         ...
288072          1614547221982335   -0.010650  Medicine ball with burpies
288073          1614547221986338   -0.010620  Medicine ball with burpies
288074          1614547221990341   -0.010620  Medicine ball with burpies
288075          1614547221994344   -0.010650  Medicine ball with burpies
288076          1614547221998347   -0.010656  Medicine ball with burpies

[14990 rows x 3 columns]

In [16]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=21, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=22, second=14)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-16-d0ed01ea138e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
301069          1614547274003382   -0.010281     punch ball
301070          1614547274007385   -0.010336     punch ball
301071          1614547274011387   -0.010318     punch ball
301072          1614547274015390   -0.010343     punch ball
301073          1614547274019393   -0.010367     punch ball
...                          ...         ...            ...
316056          1614547333981216   -0.010484     punch ball
316057          1614547333985218   -0.010558     punch ball
316058          1614547333989219   -0.010546     punch ball
316059          1614547333993221   -0.010515     punch ball
316060          1614547333997223   -0.010490     punch ball

[14992 rows x 3 columns]

In [19]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=31, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=32, second=5)
end_ts=int(end.timestamp() * 1e6)

DF13= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

Empty DataFrame
Columns: [Timestamp (microseconds), Sample (V), Activity_Label]
Index: []

In [20]:
df2=pd.read_csv('chest_elec.csv-sub-02-folder02')

In [21]:
df2

        Timestamp (microseconds)  Sample (V)
0               1614547828742340   -0.016436
1               1614547828746341   -0.015986
2               1614547828750343   -0.015574
3               1614547828754345   -0.015211
4               1614547828758346   -0.014878
...                          ...         ...
497999          1614549822429848   -0.010835
498000          1614549822433851   -0.010853
498001          1614549822437853   -0.010860
498002          1614549822441856   -0.010860
498003          1614549822445859   -0.010872

[498004 rows x 2 columns]

In [23]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=31, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=32, second=5)
end_ts=int(end.timestamp() * 1e6)

DF13= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-23-d95deb96beeb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

       Timestamp (microseconds)  Sample (V)   Activity_Label
9060           1614547865003997   -0.010656  Squarts Toe ups
9061           1614547865008000   -0.010675  Squarts Toe ups
9062           1614547865012003   -0.010669  Squarts Toe ups
9063           1614547865016005   -0.010663  Squarts Toe ups
9064           1614547865020008   -0.010656  Squarts Toe ups
...                         ...         ...              ...
24045          1614547924981375   -0.010632  Squarts Toe ups
24046          1614547924985378   -0.010644  Squarts Toe ups
24047          1614547924989380   -0.010663  Squarts Toe ups
24048          1614547924993383   -0.010669  Squarts Toe ups
24049          1614547924997386   -0.010669  Squarts Toe ups

[14990 rows x 3 columns]

In [24]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=32, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=33, second=37)
end_ts=int(end.timestamp() * 1e6)

DF14= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-24-4d91d95eefda>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

       Timestamp (microseconds)  Sample (V) Activity_Label
32045          1614547957002652   -0.010281   Weight lifts
32046          1614547957006655   -0.010263   Weight lifts
32047          1614547957010658   -0.010263   Weight lifts
32048          1614547957014661   -0.010238   Weight lifts
32049          1614547957018664   -0.010232   Weight lifts
...                         ...         ...            ...
47030          1614548016983224   -0.010275   Weight lifts
47031          1614548016987228   -0.010275   Weight lifts
47032          1614548016991231   -0.010275   Weight lifts
47033          1614548016995234   -0.010269   Weight lifts
47034          1614548016999237   -0.010263   Weight lifts

[14990 rows x 3 columns]

In [25]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=34, second=43)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=35, second=43)
end_ts=int(end.timestamp() * 1e6)

DF15= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-25-afacfecb25b9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

       Timestamp (microseconds)  Sample (V)      Activity_Label
63524          1614548083003797   -0.010650  Heavy Weight lifts
63525          1614548083007800   -0.010687  Heavy Weight lifts
63526          1614548083011803   -0.010730  Heavy Weight lifts
63527          1614548083015806   -0.010761  Heavy Weight lifts
63528          1614548083019809   -0.010786  Heavy Weight lifts
...                         ...         ...                 ...
78508          1614548142982380   -0.010761  Heavy Weight lifts
78509          1614548142986384   -0.010755  Heavy Weight lifts
78510          1614548142990387   -0.010773  Heavy Weight lifts
78511          1614548142994390   -0.010804  Heavy Weight lifts
78512          1614548142998393   -0.010810  Heavy Weight lifts

[14989 rows x 3 columns]

In [26]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=36, second=13)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=37, second=10)
end_ts=int(end.timestamp() * 1e6)

DF16= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-26-03661f6b1e49>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

        Timestamp (microseconds)  Sample (V)          Activity_Label
86007           1614548173000013   -0.010743  Forward Lunges on Bosu
86008           1614548173004017   -0.010767  Forward Lunges on Bosu
86009           1614548173008020   -0.010773  Forward Lunges on Bosu
86010           1614548173012024   -0.010780  Forward Lunges on Bosu
86011           1614548173016027   -0.010786  Forward Lunges on Bosu
...                          ...         ...                     ...
100242          1614548229981895   -0.010601  Forward Lunges on Bosu
100243          1614548229985898   -0.010607  Forward Lunges on Bosu
100244          1614548229989901   -0.010607  Forward Lunges on Bosu
100245          1614548229993904   -0.010620  Forward Lunges on Bosu
100246          1614548229997907   -0.010632  Forward Lunges on Bosu

[14240 rows x 3 columns]

In [27]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=37, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=38, second=48)
end_ts=int(end.timestamp() * 1e6)

DF17= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-27-d409ccdc3cda>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
109740          1614548268001698   -0.010755  Split squart left on Bosu
109741          1614548268005701   -0.010761  Split squart left on Bosu
109742          1614548268009704   -0.010761  Split squart left on Bosu
109743          1614548268013707   -0.010767  Split squart left on Bosu
109744          1614548268017710   -0.010767  Split squart left on Bosu
...                          ...         ...                        ...
124723          1614548327980569   -0.010527  Split squart left on Bosu
124724          1614548327984573   -0.010533  Split squart left on Bosu
124725          1614548327988577   -0.010546  Split squart left on Bosu
124726          1614548327992580   -0.010552  Split squart left on Bosu
124727          1614548327996584   -0.010546  Split squart left on Bosu

[14988 rows x 3 columns]

In [28]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=28, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=39, second=56)
end_ts=int(end.timestamp() * 1e6)

DF18= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-28-b6f641265c34>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

        Timestamp (microseconds)  Sample (V)              Activity_Label
0               1614547828742340   -0.016436  Split squart right on Bosu
1               1614547828746341   -0.015986  Split squart right on Bosu
2               1614547828750343   -0.015574  Split squart right on Bosu
3               1614547828754345   -0.015211  Split squart right on Bosu
4               1614547828758346   -0.014878  Split squart right on Bosu
...                          ...         ...                         ...
141709          1614548395981859   -0.010570  Split squart right on Bosu
141710          1614548395985862   -0.010576  Split squart right on Bosu
141711          1614548395989866   -0.010570  Split squart right on Bosu
141712          1614548395993869   -0.010583  Split squart right on Bosu
141713          1614548395997873   -0.010583  Split squart right on Bosu

[141714 rows x 3 columns]

In [29]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=41, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=42, second=56)
end_ts=int(end.timestamp() * 1e6)

DF19= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-29-e72965f51e32>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
171688          1614548516003826   -0.010515  plank pie on Bosu
171689          1614548516007829   -0.010515  plank pie on Bosu
171690          1614548516011833   -0.010441  plank pie on Bosu
171691          1614548516015836   -0.010453  plank pie on Bosu
171692          1614548516019840   -0.010490  plank pie on Bosu
...                          ...         ...                ...
186668          1614548575980732   -0.010724  plank pie on Bosu
186669          1614548575984736   -0.010718  plank pie on Bosu
186670          1614548575988740   -0.010743  plank pie on Bosu
186671          1614548575992744   -0.010755  plank pie on Bosu
186672          1614548575996748   -0.010718  plank pie on Bosu

[14985 rows x 3 columns]

In [30]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=43, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=44, second=35)
end_ts=int(end.timestamp() * 1e6)

DF20= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-30-a1a0fcb9dd9d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
196414          1614548615002672   -0.010804  plank top on Bosu
196415          1614548615006676   -0.010829  plank top on Bosu
196416          1614548615010680   -0.010841  plank top on Bosu
196417          1614548615014684   -0.010853  plank top on Bosu
196418          1614548615018688   -0.010853  plank top on Bosu
...                          ...         ...                ...
211394          1614548674981209   -0.010841  plank top on Bosu
211395          1614548674985213   -0.010866  plank top on Bosu
211396          1614548674989217   -0.010890  plank top on Bosu
211397          1614548674993221   -0.010903  plank top on Bosu
211398          1614548674997225   -0.010903  plank top on Bosu

[14985 rows x 3 columns]

In [31]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=47, second=18)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=48, second=18)
end_ts=int(end.timestamp() * 1e6)

DF21= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-31-b879ed8696d0>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

        Timestamp (microseconds)  Sample (V) Activity_Label
252110          1614548838000268   -0.010896   dips on Bosu
252111          1614548838004272   -0.010909   dips on Bosu
252112          1614548838008276   -0.010860   dips on Bosu
252113          1614548838012280   -0.010761   dips on Bosu
252114          1614548838016284   -0.010669   dips on Bosu
...                          ...         ...            ...
267090          1614548897981811   -0.010318   dips on Bosu
267091          1614548897985816   -0.010312   dips on Bosu
267092          1614548897989820   -0.010300   dips on Bosu
267093          1614548897993825   -0.010287   dips on Bosu
267094          1614548897997829   -0.010287   dips on Bosu

[14985 rows x 3 columns]

In [32]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=48, second=49)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=49, second=49)
end_ts=int(end.timestamp() * 1e6)

DF22= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-32-7965ea57549b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

        Timestamp (microseconds)  Sample (V)                Activity_Label
274837          1614548929002879   -0.011721  moveforward backward on Bosu
274838          1614548929006883   -0.011721  moveforward backward on Bosu
274839          1614548929010888   -0.011715  moveforward backward on Bosu
274840          1614548929014892   -0.011721  moveforward backward on Bosu
274841          1614548929018897   -0.011740  moveforward backward on Bosu
...                          ...         ...                           ...
289816          1614548988980420   -0.010730  moveforward backward on Bosu
289817          1614548988984424   -0.010730  moveforward backward on Bosu
289818          1614548988988428   -0.010724  moveforward backward on Bosu
289819          1614548988992432   -0.010736  moveforward backward on Bosu
289820          1614548988996436   -0.010743  moveforward backward on Bosu

[14984 rows x 3 columns]

In [33]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=50, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=51, second=53)
end_ts=int(end.timestamp() * 1e6)

DF23= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-33-f8f5768a03fe>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)            Activity_Label
305806          1614549053002808   -0.009586  Left leg Hip ups on Bosu
305807          1614549053006812   -0.009586  Left leg Hip ups on Bosu
305808          1614549053010816   -0.009598  Left leg Hip ups on Bosu
305809          1614549053014820   -0.009610  Left leg Hip ups on Bosu
305810          1614549053018824   -0.009604  Left leg Hip ups on Bosu
...                          ...         ...                       ...
320786          1614549112982231   -0.010810  Left leg Hip ups on Bosu
320787          1614549112986235   -0.010804  Left leg Hip ups on Bosu
320788          1614549112990239   -0.010810  Left leg Hip ups on Bosu
320789          1614549112994243   -0.010810  Left leg Hip ups on Bosu
320790          1614549112998247   -0.010804  Left leg Hip ups on Bosu

[14985 rows x 3 columns]

In [34]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=52, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=53, second=5)
end_ts=int(end.timestamp() * 1e6)

DF24= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-34-07ea0f7e01a7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
323788          1614549125001892   -0.010601  right leg Hip ups on Bosu
323789          1614549125005896   -0.010607  right leg Hip ups on Bosu
323790          1614549125009900   -0.010607  right leg Hip ups on Bosu
323791          1614549125013904   -0.010626  right leg Hip ups on Bosu
323792          1614549125017908   -0.010626  right leg Hip ups on Bosu
...                          ...         ...                        ...
338768          1614549184980941   -0.010681  right leg Hip ups on Bosu
338769          1614549184984945   -0.010681  right leg Hip ups on Bosu
338770          1614549184988949   -0.010687  right leg Hip ups on Bosu
338771          1614549184992953   -0.010693  right leg Hip ups on Bosu
338772          1614549184996957   -0.010693  right leg Hip ups on Bosu

[14985 rows x 3 columns]

In [35]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=54, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=55, second=20)
end_ts=int(end.timestamp() * 1e6)

DF25= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-35-f4f92cb05653>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

        Timestamp (microseconds)  Sample (V)         Activity_Label
364497          1614549288002202   -0.010792  V-Shift Swift on Bosu
364498          1614549288006206   -0.010804  V-Shift Swift on Bosu
364499          1614549288010211   -0.010810  V-Shift Swift on Bosu
364500          1614549288014215   -0.010798  V-Shift Swift on Bosu
364501          1614549288018220   -0.010798  V-Shift Swift on Bosu
...                          ...         ...                    ...
372484          1614549319982716   -0.010767  V-Shift Swift on Bosu
372485          1614549319986720   -0.010761  V-Shift Swift on Bosu
372486          1614549319990724   -0.010755  V-Shift Swift on Bosu
372487          1614549319994728   -0.010749  V-Shift Swift on Bosu
372488          1614549319998732   -0.010749  V-Shift Swift on Bosu

[7992 rows x 3 columns]

In [36]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=56, second=42)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=57, second=12)
end_ts=int(end.timestamp() * 1e6)

DF26= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-36-77d880e23070>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

        Timestamp (microseconds)  Sample (V)    Activity_Label
392970          1614549402003433   -0.010946  Freestyle Boxing
392971          1614549402007436   -0.010946  Freestyle Boxing
392972          1614549402011440   -0.010940  Freestyle Boxing
392973          1614549402015443   -0.010946  Freestyle Boxing
392974          1614549402019447   -0.010977  Freestyle Boxing
...                          ...         ...               ...
400458          1614549431981296   -0.010484  Freestyle Boxing
400459          1614549431985300   -0.010484  Freestyle Boxing
400460          1614549431989303   -0.010496  Freestyle Boxing
400461          1614549431993307   -0.010509  Freestyle Boxing
400462          1614549431997310   -0.010509  Freestyle Boxing

[7493 rows x 3 columns]

In [37]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=57, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=58, second=15)
end_ts=int(end.timestamp() * 1e6)

DF27= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-37-9ca049cde5c9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

        Timestamp (microseconds)  Sample (V)           Activity_Label
408706          1614549465001133   -0.010183  Left_Right_Punches_flip
408707          1614549465005136   -0.010170  Left_Right_Punches_flip
408708          1614549465009140   -0.010146  Left_Right_Punches_flip
408709          1614549465013143   -0.010139  Left_Right_Punches_flip
408710          1614549465017147   -0.010127  Left_Right_Punches_flip
...                          ...         ...                      ...
416195          1614549494981596   -0.010540  Left_Right_Punches_flip
416196          1614549494985599   -0.010540  Left_Right_Punches_flip
416197          1614549494989603   -0.010521  Left_Right_Punches_flip
416198          1614549494993606   -0.010509  Left_Right_Punches_flip
416199          1614549494997610   -0.010515  Left_Right_Punches_flip

[7494 rows x 3 columns]

In [38]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=58, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=59, second=0)
end_ts=int(end.timestamp() * 1e6)

DF28= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-38-ade80b987577>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

        Timestamp (microseconds)  Sample (V)    Activity_Label
419947          1614549510001596   -0.010718  left_Right_Punch
419948          1614549510005600   -0.010706  left_Right_Punch
419949          1614549510009603   -0.010712  left_Right_Punch
419950          1614549510013607   -0.010718  left_Right_Punch
419951          1614549510017610   -0.010700  left_Right_Punch
...                          ...         ...               ...
427436          1614549539981080   -0.010700  left_Right_Punch
427437          1614549539985083   -0.010669  left_Right_Punch
427438          1614549539989086   -0.010638  left_Right_Punch
427439          1614549539993089   -0.010607  left_Right_Punch
427440          1614549539997092   -0.010589  left_Right_Punch

[7494 rows x 3 columns]

In [39]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=59, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=0, second=10)
end_ts=int(end.timestamp() * 1e6)

DF29= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-39-72ed8cfc8945>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

        Timestamp (microseconds)  Sample (V) Activity_Label
437434          1614549580003936   -0.010650       one_twos
437435          1614549580007939   -0.010663       one_twos
437436          1614549580011942   -0.010681       one_twos
437437          1614549580015946   -0.010675       one_twos
437438          1614549580019949   -0.010675       one_twos
...                          ...         ...            ...
444923          1614549609983248   -0.010847       one_twos
444924          1614549609987251   -0.010835       one_twos
444925          1614549609991254   -0.010816       one_twos
444926          1614549609995257   -0.010804       one_twos
444927          1614549609999260   -0.010798       one_twos

[7494 rows x 3 columns]

In [40]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=0, second=18)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=0, second=48)
end_ts=int(end.timestamp() * 1e6)

DF30= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-40-c4cfda12eb5d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

        Timestamp (microseconds)  Sample (V) Activity_Label
446926          1614549618001522   -0.010773          hooks
446927          1614549618005525   -0.010773          hooks
446928          1614549618009528   -0.010773          hooks
446929          1614549618013531   -0.010767          hooks
446930          1614549618017534   -0.010767          hooks
...                          ...         ...            ...
454415          1614549647980192   -0.010533          hooks
454416          1614549647984195   -0.010533          hooks
454417          1614549647988198   -0.010533          hooks
454418          1614549647992201   -0.010527          hooks
454419          1614549647996204   -0.010521          hooks

[7494 rows x 3 columns]

In [41]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=1, second=18)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=1, second=48)
end_ts=int(end.timestamp() * 1e6)

DF31= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-41-9a11398e6231>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

        Timestamp (microseconds)  Sample (V) Activity_Label
461915          1614549678002104   -0.010023     Upper_cuts
461916          1614549678006107   -0.010041     Upper_cuts
461917          1614549678010110   -0.010053     Upper_cuts
461918          1614549678014113   -0.010035     Upper_cuts
461919          1614549678018116   -0.010029     Upper_cuts
...                          ...         ...            ...
469405          1614549707983374   -0.010663     Upper_cuts
469406          1614549707987377   -0.010656     Upper_cuts
469407          1614549707991380   -0.010650     Upper_cuts
469408          1614549707995383   -0.010650     Upper_cuts
469409          1614549707999386   -0.010650     Upper_cuts

[7495 rows x 3 columns]

In [42]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=2, second=7)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=2, second=37)
end_ts=int(end.timestamp() * 1e6)

DF32= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-42-4c9ad5278874>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

        Timestamp (microseconds)  Sample (V) Activity_Label
474156          1614549727000579   -0.010792            run
474157          1614549727004583   -0.010773            run
474158          1614549727008586   -0.010767            run
474159          1614549727012589   -0.010761            run
474160          1614549727016592   -0.010749            run
...                          ...         ...            ...
481647          1614549756983693   -0.010367            run
481648          1614549756987695   -0.010361            run
481649          1614549756991698   -0.010373            run
481650          1614549756995700   -0.010373            run
481651          1614549756999703   -0.010373            run

[7496 rows x 3 columns]

In [43]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=2, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=3, second=24)
end_ts=int(end.timestamp() * 1e6)

DF33= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-43-7d2a4c8d2a1c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

        Timestamp (microseconds)  Sample (V)       Activity_Label
486399          1614549776002493   -0.010589  Punch_down_Up_Hooks
486400          1614549776006496   -0.010589  Punch_down_Up_Hooks
486401          1614549776010499   -0.010576  Punch_down_Up_Hooks
486402          1614549776014501   -0.010558  Punch_down_Up_Hooks
486403          1614549776018504   -0.010540  Punch_down_Up_Hooks
...                          ...         ...                  ...
493390          1614549803982710   -0.010472  Punch_down_Up_Hooks
493391          1614549803986712   -0.010484  Punch_down_Up_Hooks
493392          1614549803990715   -0.010484  Punch_down_Up_Hooks
493393          1614549803994717   -0.010503  Punch_down_Up_Hooks
493394          1614549803998720   -0.010515  Punch_down_Up_Hooks

[6996 rows x 3 columns]

In [44]:
sub02_final_chest_elec=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub02_final_chest_elec

        Timestamp (microseconds)  Sample (V)             Activity_Label
0               1614546102002668   -0.010540  Forward and backward step
1               1614546102006671   -0.010546  Forward and backward step
2               1614546102010673   -0.010546  Forward and backward step
3               1614546102014676   -0.010552  Forward and backward step
4               1614546102018707   -0.010558  Forward and backward step
...                          ...         ...                        ...
553128          1614549803982710   -0.010472        Punch_down_Up_Hooks
553129          1614549803986712   -0.010484        Punch_down_Up_Hooks
553130          1614549803990715   -0.010484        Punch_down_Up_Hooks
553131          1614549803994717   -0.010503        Punch_down_Up_Hooks
553132          1614549803998720   -0.010515        Punch_down_Up_Hooks

[553133 rows x 3 columns]

In [45]:
sub02_final_chest_elec.to_csv('final_cleaned_chest_elec-sub02.csv-sub02')