In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('chest_elec.csv-sub05')

In [3]:
df1

         Timestamp (microseconds)  Sample (V)
0                1614642548778381    0.002126
1                1614642548782385    0.002065
2                1614642548786390    0.002028
3                1614642548790394    0.001991
4                1614642548794399    0.001954
...                           ...         ...
1014547          1614646614642051    0.001979
1014548          1614646614646058    0.001800
1014549          1614646614650065    0.002151
1014550          1614646614654071    0.001782
1014551          1614646614658078    0.002262

[1014552 rows x 2 columns]

In [4]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-01 23:49:08.778381')

In [5]:
start = pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=51, second=36)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=52, second=36)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-5-e9561541a177>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

       Timestamp (microseconds)  Sample (V)             Activity_Label
36739          1614642696002603    0.001812  Forward and backward step
36740          1614642696006610    0.001806  Forward and backward step
36741          1614642696010618    0.001812  Forward and backward step
36742          1614642696014625    0.001800  Forward and backward step
36743          1614642696018633    0.001794  Forward and backward step
...                         ...         ...                        ...
51706          1614642755982904    0.001917  Forward and backward step
51707          1614642755986912    0.001917  Forward and backward step
51708          1614642755990920    0.001911  Forward and backward step
51709          1614642755994928    0.001911  Forward and backward step
51710          1614642755998935    0.001911  Forward and backward step

[14972 rows x 3 columns]

In [6]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=52, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=53, second=48)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-6-25854c32d455>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

       Timestamp (microseconds)  Sample (V) Activity_Label
54705          1614642768001467    0.002422  Sideward step
54706          1614642768005475    0.002373  Sideward step
54707          1614642768009482    0.002182  Sideward step
54708          1614642768013490    0.001973  Sideward step
54709          1614642768017498    0.001837  Sideward step
...                         ...         ...            ...
69671          1614642827980375    0.002397  Sideward step
69672          1614642827984383    0.002391  Sideward step
69673          1614642827988391    0.002379  Sideward step
69674          1614642827992399    0.002391  Sideward step
69675          1614642827996407    0.002416  Sideward step

[14971 rows x 3 columns]

In [7]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=54, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=55, second=53)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-7-9aa91ac6d6ce>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

        Timestamp (microseconds)  Sample (V) Activity_Label
85895           1614642893002694    0.002065        Pushups
85896           1614642893006702    0.002096        Pushups
85897           1614642893010710    0.002114        Pushups
85898           1614642893014718    0.002114        Pushups
85899           1614642893018725    0.002102        Pushups
...                          ...         ...            ...
100860          1614642952980587    0.002139        Pushups
100861          1614642952984594    0.002133        Pushups
100862          1614642952988602    0.002133        Pushups
100863          1614642952992610    0.002096        Pushups
100864          1614642952996618    0.002071        Pushups

[14970 rows x 3 columns]

In [8]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=56, second=39)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=57, second=39)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-8-d2f7630bf61a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Sample (V),Activity_Label
112343,1614642999001947,0.002120,Hip raise step with punches in the air
112344,1614642999005954,0.002157,Hip raise step with punches in the air
112345,1614642999009962,0.002176,Hip raise step with punches in the air
112346,1614642999013970,0.002169,Hip raise step with punches in the air
112347,1614642999017978,0.002169,Hip raise step with punches in the air
...,...,...,...
127309,1614643058983022,0.002650,Hip raise step with punches in the air
127310,1614643058987030,0.002662,Hip raise step with punches in the air
127311,1614643058991037,0.002668,Hip raise step with punches in the air
127312,1614643058995045,0.002680,Hip raise step with punches in the air
127313,1614643058999053,0.002699,Hip raise step with punches in the air

In [9]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=58, second=58)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=59, second=58)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-9-2a715700a61f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

        Timestamp (microseconds)  Sample (V)          Activity_Label
147024          1614643138001489    0.002366  Front and back scooter
147025          1614643138005498    0.002348  Front and back scooter
147026          1614643138009506    0.002342  Front and back scooter
147027          1614643138013514    0.002329  Front and back scooter
147028          1614643138017522    0.002329  Front and back scooter
...                          ...         ...                     ...
161988          1614643197981699    0.001966  Front and back scooter
161989          1614643197985707    0.001966  Front and back scooter
161990          1614643197989715    0.001985  Front and back scooter
161991          1614643197993723    0.002028  Front and back scooter
161992          1614643197997732    0.002114  Front and back scooter

[14969 rows x 3 columns]

In [10]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=2, second=25)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=3, second=25)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-10-5b4fd6879356>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

        Timestamp (microseconds)  Sample (V) Activity_Label
198668          1614643345000124    0.002182  Belly Scooter
198669          1614643345004131    0.002317  Belly Scooter
198670          1614643345008139    0.002249  Belly Scooter
198671          1614643345012147    0.002219  Belly Scooter
198672          1614643345016155    0.002213  Belly Scooter
...                          ...         ...            ...
213634          1614643404980985    0.002286  Belly Scooter
213635          1614643404984993    0.002274  Belly Scooter
213636          1614643404989001    0.002268  Belly Scooter
213637          1614643404993009    0.002268  Belly Scooter
213638          1614643404997017    0.002280  Belly Scooter

[14971 rows x 3 columns]

In [11]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=3, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=4, second=45)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-11-14cc1c1edf38>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

        Timestamp (microseconds)  Sample (V)    Activity_Label
218629          1614643425000355    0.003283  Circular Scooter
218630          1614643425004363    0.003271  Circular Scooter
218631          1614643425008371    0.003345  Circular Scooter
218632          1614643425012378    0.003413  Circular Scooter
218633          1614643425016386    0.003560  Circular Scooter
...                          ...         ...               ...
233594          1614643484980760    0.001843  Circular Scooter
233595          1614643484984768    0.001843  Circular Scooter
233596          1614643484988777    0.001849  Circular Scooter
233597          1614643484992785    0.001819  Circular Scooter
233598          1614643484996793    0.001831  Circular Scooter

[14970 rows x 3 columns]

In [12]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=6, second=58)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=7, second=58)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-12-81eeea766c0c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

        Timestamp (microseconds)  Sample (V) Activity_Label
266783          1614643618001491    0.002083   Cycling Slow
266784          1614643618005499    0.002077   Cycling Slow
266785          1614643618009506    0.002059   Cycling Slow
266786          1614643618013514    0.002096   Cycling Slow
266787          1614643618017522    0.002071   Cycling Slow
...                          ...         ...            ...
281749          1614643677982291    0.002545   Cycling Slow
281750          1614643677986299    0.002477   Cycling Slow
281751          1614643677990307    0.002539   Cycling Slow
281752          1614643677994315    0.002453   Cycling Slow
281753          1614643677998323    0.002416   Cycling Slow

[14971 rows x 3 columns]

In [13]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=7, second=59)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=8, second=59)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-13-e864ea10ed90>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

        Timestamp (microseconds)  Sample (V) Activity_Label
282003          1614643679000244    0.001382   Cycling Fast
282004          1614643679004252    0.001369   Cycling Fast
282005          1614643679008260    0.001351   Cycling Fast
282006          1614643679012268    0.001388   Cycling Fast
282007          1614643679016276    0.001431   Cycling Fast
...                          ...         ...            ...
296970          1614643738981502    0.001732   Cycling Fast
296971          1614643738985509    0.001579   Cycling Fast
296972          1614643738989517    0.001794   Cycling Fast
296973          1614643738993524    0.001665   Cycling Fast
296974          1614643738997532    0.001757   Cycling Fast

[14972 rows x 3 columns]

In [14]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=10, second=43)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=11, second=43)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-14-185538fb6733>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
322926          1614643843001507    0.001529  Medicine_ball
322927          1614643843005515    0.001529  Medicine_ball
322928          1614643843009523    0.001536  Medicine_ball
322929          1614643843013531    0.001542  Medicine_ball
322930          1614643843017539    0.001529  Medicine_ball
...                          ...         ...            ...
337891          1614643902980502    0.002237  Medicine_ball
337892          1614643902984510    0.002188  Medicine_ball
337893          1614643902988518    0.002169  Medicine_ball
337894          1614643902992527    0.002163  Medicine_ball
337895          1614643902996535    0.002157  Medicine_ball

[14970 rows x 3 columns]

In [15]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=11, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=12, second=53)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-15-4896ff752642>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

        Timestamp (microseconds)  Sample (V)              Activity_Label
340391          1614643913000512    0.001689  Medicine ball with burpies
340392          1614643913004520    0.001819  Medicine ball with burpies
340393          1614643913008528    0.001757  Medicine ball with burpies
340394          1614643913012537    0.001745  Medicine ball with burpies
340395          1614643913016545    0.001763  Medicine ball with burpies
...                          ...         ...                         ...
355358          1614643972981701    0.001536  Medicine ball with burpies
355359          1614643972985708    0.001696  Medicine ball with burpies
355360          1614643972989715    0.001308  Medicine ball with burpies
355361          1614643972993723    0.001763  Medicine ball with burpies
355362          1614643972997730    0.001652  Medicine ball with burpies

[14972 rows x 3 columns]

In [16]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=17, second=20)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=18, second=20)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-16-8c2dcfc459b6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
422021          1614644240002281    0.001726     punch ball
422022          1614644240006286    0.001726     punch ball
422023          1614644240010292    0.001726     punch ball
422024          1614644240014297    0.001726     punch ball
422025          1614644240018303    0.001726     punch ball
...                          ...         ...            ...
436994          1614644299981338    0.002108     punch ball
436995          1614644299985345    0.002040     punch ball
436996          1614644299989351    0.001979     punch ball
436997          1614644299993357    0.001917     punch ball
436998          1614644299997364    0.001923     punch ball

[14978 rows x 3 columns]

In [17]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=19, second=13)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=20, second=13)
end_ts=int(end.timestamp() * 1e6)

DF13= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-17-fd04f2203726>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

        Timestamp (microseconds)  Sample (V)   Activity_Label
450229          1614644353003625    0.001997  Squarts Toe ups
450230          1614644353007631    0.002003  Squarts Toe ups
450231          1614644353011637    0.001997  Squarts Toe ups
450232          1614644353015644    0.001991  Squarts Toe ups
450233          1614644353019650    0.001985  Squarts Toe ups
...                          ...         ...              ...
465200          1614644412983220    0.001720  Squarts Toe ups
465201          1614644412987227    0.001732  Squarts Toe ups
465202          1614644412991233    0.001732  Squarts Toe ups
465203          1614644412995240    0.001732  Squarts Toe ups
465204          1614644412999247    0.001732  Squarts Toe ups

[14976 rows x 3 columns]

In [18]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=20, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=21, second=55)
end_ts=int(end.timestamp() * 1e6)

DF14= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-18-950049b5159c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

        Timestamp (microseconds)  Sample (V) Activity_Label
475687          1614644455001119    0.002305   Weight lifts
475688          1614644455005126    0.002305   Weight lifts
475689          1614644455009132    0.002305   Weight lifts
475690          1614644455013139    0.002286   Weight lifts
475691          1614644455017146    0.002280   Weight lifts
...                          ...         ...            ...
490656          1614644514981517    0.002650   Weight lifts
490657          1614644514985525    0.002637   Weight lifts
490658          1614644514989532    0.002613   Weight lifts
490659          1614644514993539    0.002588   Weight lifts
490660          1614644514997547    0.002569   Weight lifts

[14974 rows x 3 columns]

In [19]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=22, second=49)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=23, second=49)
end_ts=int(end.timestamp() * 1e6)

DF15= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-19-18773cd91355>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

        Timestamp (microseconds)  Sample (V)      Activity_Label
504137          1614644569002695    0.001843  Heavy Weight lifts
504138          1614644569006702    0.001868  Heavy Weight lifts
504139          1614644569010709    0.001874  Heavy Weight lifts
504140          1614644569014717    0.001886  Heavy Weight lifts
504141          1614644569018724    0.001899  Heavy Weight lifts
...                          ...         ...                 ...
519105          1614644628982988    0.001917  Heavy Weight lifts
519106          1614644628986995    0.001868  Heavy Weight lifts
519107          1614644628991003    0.001800  Heavy Weight lifts
519108          1614644628995010    0.001757  Heavy Weight lifts
519109          1614644628999017    0.001757  Heavy Weight lifts

[14973 rows x 3 columns]

In [20]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=24, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=25, second=45)
end_ts=int(end.timestamp() * 1e6)

DF16= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-20-94083dc3f1f6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

        Timestamp (microseconds)  Sample (V)          Activity_Label
533084          1614644685002155    0.001831  Forward Lunges on Bosu
533085          1614644685006162    0.001819  Forward Lunges on Bosu
533086          1614644685010170    0.001812  Forward Lunges on Bosu
533087          1614644685014177    0.001800  Forward Lunges on Bosu
533088          1614644685018184    0.001806  Forward Lunges on Bosu
...                          ...         ...                     ...
548052          1614644744983390    0.002016  Forward Lunges on Bosu
548053          1614644744987398    0.002016  Forward Lunges on Bosu
548054          1614644744991405    0.002022  Forward Lunges on Bosu
548055          1614644744995412    0.002034  Forward Lunges on Bosu
548056          1614644744999420    0.002034  Forward Lunges on Bosu

[14973 rows x 3 columns]

In [21]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=26, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=27, second=48)
end_ts=int(end.timestamp() * 1e6)

DF17= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-21-62080580c548>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
563778          1614644808002105    0.002003  Split squart left on Bosu
563779          1614644808006113    0.002009  Split squart left on Bosu
563780          1614644808010120    0.001991  Split squart left on Bosu
563781          1614644808014127    0.001979  Split squart left on Bosu
563782          1614644808018135    0.001929  Split squart left on Bosu
...                          ...         ...                        ...
578745          1614644867983230    0.002397  Split squart left on Bosu
578746          1614644867987238    0.002391  Split squart left on Bosu
578747          1614644867991245    0.002391  Split squart left on Bosu
578748          1614644867995253    0.002379  Split squart left on Bosu
578749          1614644867999261    0.002385  Split squart left on Bosu

[14972 rows x 3 columns]

In [22]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=28, second=0)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=29, second=0)
end_ts=int(end.timestamp() * 1e6)

DF18= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-22-bdbb8cdde35b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

        Timestamp (microseconds)  Sample (V)              Activity_Label
581744          1614644880002037    0.001929  Split squart right on Bosu
581745          1614644880006044    0.001936  Split squart right on Bosu
581746          1614644880010052    0.001911  Split squart right on Bosu
581747          1614644880014060    0.001868  Split squart right on Bosu
581748          1614644880018068    0.001843  Split squart right on Bosu
...                          ...         ...                         ...
596710          1614644939982380    0.000766  Split squart right on Bosu
596711          1614644939986387    0.000754  Split squart right on Bosu
596712          1614644939990395    0.000754  Split squart right on Bosu
596713          1614644939994403    0.000754  Split squart right on Bosu
596714          1614644939998411    0.000754  Split squart right on Bosu

[14971 rows x 3 columns]

In [23]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=30, second=32)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=31, second=32)
end_ts=int(end.timestamp() * 1e6)

DF19= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-23-f5483580dfe9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
619669          1614645032002553    0.002650  plank pie on Bosu
619670          1614645032006561    0.002662  plank pie on Bosu
619671          1614645032010569    0.002668  plank pie on Bosu
619672          1614645032014577    0.002662  plank pie on Bosu
619673          1614645032018586    0.002643  plank pie on Bosu
...                          ...         ...                ...
634633          1614645091983616    0.002416  plank pie on Bosu
634634          1614645091987625    0.001622  plank pie on Bosu
634635          1614645091991633    0.000686  plank pie on Bosu
634636          1614645091995641    0.000686  plank pie on Bosu
634637          1614645091999650    0.001172  plank pie on Bosu

[14969 rows x 3 columns]

In [24]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=32, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=33, second=37)
end_ts=int(end.timestamp() * 1e6)

DF20= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-24-82eaf00409de>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
650854          1614645157001478    0.002003  plank top on Bosu
650855          1614645157005486    0.002016  plank top on Bosu
650856          1614645157009494    0.002053  plank top on Bosu
650857          1614645157013503    0.002059  plank top on Bosu
650858          1614645157017511    0.002028  plank top on Bosu
...                          ...         ...                ...
665817          1614645216980854    0.001837  plank top on Bosu
665818          1614645216984863    0.001923  plank top on Bosu
665819          1614645216988872    0.002040  plank top on Bosu
665820          1614645216992880    0.002139  plank top on Bosu
665821          1614645216996889    0.002169  plank top on Bosu

[14968 rows x 3 columns]

In [25]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=34, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=35, second=57)
end_ts=int(end.timestamp() * 1e6)

DF21= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-25-f965cc1a2ab4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

        Timestamp (microseconds)  Sample (V) Activity_Label
685780          1614645297000188    0.001622   dips on Bosu
685781          1614645297004197    0.001616   dips on Bosu
685782          1614645297008205    0.001628   dips on Bosu
685783          1614645297012213    0.001640   dips on Bosu
685784          1614645297016222    0.001634   dips on Bosu
...                          ...         ...            ...
700744          1614645356981696    0.001985   dips on Bosu
700745          1614645356985705    0.001954   dips on Bosu
700746          1614645356989713    0.001917   dips on Bosu
700747          1614645356993722    0.001948   dips on Bosu
700748          1614645356997731    0.001948   dips on Bosu

[14969 rows x 3 columns]

In [26]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=36, second=52)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=37, second=52)
end_ts=int(end.timestamp() * 1e6)

DF22= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-26-e9267ac5fbf7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

        Timestamp (microseconds)  Sample (V)                Activity_Label
714470          1614645412002199    0.001825  moveforward backward on Bosu
714471          1614645412006207    0.001837  moveforward backward on Bosu
714472          1614645412010215    0.001849  moveforward backward on Bosu
714473          1614645412014224    0.001849  moveforward backward on Bosu
714474          1614645412018232    0.001868  moveforward backward on Bosu
...                          ...         ...                           ...
729434          1614645471981798    0.002896  moveforward backward on Bosu
729435          1614645471985806    0.002883  moveforward backward on Bosu
729436          1614645471989814    0.002871  moveforward backward on Bosu
729437          1614645471993823    0.002859  moveforward backward on Bosu
729438          1614645471997802    0.002859  moveforward backward on Bosu

[14969 rows x 3 columns]

In [27]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=39, second=2)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=40, second=2)
end_ts=int(end.timestamp() * 1e6)

DF23= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-27-eb7f55f1d151>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)            Activity_Label
746904          1614645542003536    0.002016  Left leg Hip ups on Bosu
746905          1614645542007544    0.002016  Left leg Hip ups on Bosu
746906          1614645542011552    0.002016  Left leg Hip ups on Bosu
746907          1614645542015561    0.002016  Left leg Hip ups on Bosu
746908          1614645542019569    0.002009  Left leg Hip ups on Bosu
...                          ...         ...                       ...
761868          1614645601982006    0.001474  Left leg Hip ups on Bosu
761869          1614645601986014    0.001474  Left leg Hip ups on Bosu
761870          1614645601990022    0.001474  Left leg Hip ups on Bosu
761871          1614645601994031    0.001486  Left leg Hip ups on Bosu
761872          1614645601998039    0.001486  Left leg Hip ups on Bosu

[14969 rows x 3 columns]

In [28]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=40, second=11)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=41, second=11)
end_ts=int(end.timestamp() * 1e6)

DF24= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-28-b2b9804ae980>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
764118          1614645611000671    0.002133  right leg Hip ups on Bosu
764119          1614645611004679    0.002139  right leg Hip ups on Bosu
764120          1614645611008688    0.002157  right leg Hip ups on Bosu
764121          1614645611012696    0.002157  right leg Hip ups on Bosu
764122          1614645611016704    0.002169  right leg Hip ups on Bosu
...                          ...         ...                        ...
779082          1614645670981460    0.002311  right leg Hip ups on Bosu
779083          1614645670985468    0.002305  right leg Hip ups on Bosu
779084          1614645670989477    0.002305  right leg Hip ups on Bosu
779085          1614645670993485    0.002293  right leg Hip ups on Bosu
779086          1614645670997493    0.002293  right leg Hip ups on Bosu

[14969 rows x 3 columns]

In [29]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=43, second=2)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=44, second=2)
end_ts=int(end.timestamp() * 1e6)

DF25= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-29-3995fabb524f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

        Timestamp (microseconds)  Sample (V)         Activity_Label
806780          1614645782001918    0.001548  V-Shift Swift on Bosu
806781          1614645782005927    0.001640  V-Shift Swift on Bosu
806782          1614645782009935    0.001554  V-Shift Swift on Bosu
806783          1614645782013943    0.001425  V-Shift Swift on Bosu
806784          1614645782017952    0.001480  V-Shift Swift on Bosu
...                          ...         ...                    ...
821744          1614645841981123    0.002569  V-Shift Swift on Bosu
821745          1614645841985131    0.002576  V-Shift Swift on Bosu
821746          1614645841989139    0.002563  V-Shift Swift on Bosu
821747          1614645841993147    0.002557  V-Shift Swift on Bosu
821748          1614645841997156    0.002551  V-Shift Swift on Bosu

[14969 rows x 3 columns]

In [30]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=46, second=50)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=47, second=20)
end_ts=int(end.timestamp() * 1e6)

DF26= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-30-ac3c15f67f9f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

        Timestamp (microseconds)  Sample (V)    Activity_Label
863666          1614646010001623    0.001640  Freestyle Boxing
863667          1614646010005631    0.001640  Freestyle Boxing
863668          1614646010009638    0.001628  Freestyle Boxing
863669          1614646010013646    0.001622  Freestyle Boxing
863670          1614646010017654    0.001622  Freestyle Boxing
...                          ...         ...               ...
871147          1614646039982696    0.000052  Freestyle Boxing
871148          1614646039986703   -0.000126  Freestyle Boxing
871149          1614646039990711   -0.000058  Freestyle Boxing
871150          1614646039994719   -0.000329  Freestyle Boxing
871151          1614646039998727   -0.000206  Freestyle Boxing

[7486 rows x 3 columns]

In [31]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=47, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=48, second=25)
end_ts=int(end.timestamp() * 1e6)

DF27= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-31-3990e029228f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

        Timestamp (microseconds)  Sample (V)           Activity_Label
879885          1614646075000820    0.002409  Left_Right_Punches_flip
879886          1614646075004828    0.002434  Left_Right_Punches_flip
879887          1614646075008836    0.002422  Left_Right_Punches_flip
879888          1614646075012844    0.002403  Left_Right_Punches_flip
879889          1614646075016852    0.002409  Left_Right_Punches_flip
...                          ...         ...                      ...
887366          1614646104981130    0.000249  Left_Right_Punches_flip
887367          1614646104985138    0.000040  Left_Right_Punches_flip
887368          1614646104989146    0.000194  Left_Right_Punches_flip
887369          1614646104993154    0.000145  Left_Right_Punches_flip
887370          1614646104997161    0.000071  Left_Right_Punches_flip

[7486 rows x 3 columns]

In [32]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=49, second=21)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=49, second=51)
end_ts=int(end.timestamp() * 1e6)

DF28= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-32-83b28f4f9fc4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

        Timestamp (microseconds)  Sample (V)    Activity_Label
901345          1614646161002440    0.001739  left_Right_Punch
901346          1614646161006447    0.001689  left_Right_Punch
901347          1614646161010455    0.001671  left_Right_Punch
901348          1614646161014463    0.001659  left_Right_Punch
901349          1614646161018471    0.001640  left_Right_Punch
...                          ...         ...               ...
908826          1614646190982597    0.003905  left_Right_Punch
908827          1614646190986605    0.003923  left_Right_Punch
908828          1614646190990613    0.003917  left_Right_Punch
908829          1614646190994620    0.003936  left_Right_Punch
908830          1614646190998628    0.003942  left_Right_Punch

[7486 rows x 3 columns]

In [33]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=50, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=51, second=21)
end_ts=int(end.timestamp() * 1e6)

DF29= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-33-759ec8fe4387>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

        Timestamp (microseconds)  Sample (V) Activity_Label
923803          1614646251000761    0.002348       one_twos
923804          1614646251004768    0.002477       one_twos
923805          1614646251008775    0.002600       one_twos
923806          1614646251012783    0.002723       one_twos
923807          1614646251016790    0.002773       one_twos
...                          ...         ...            ...
931285          1614646280983686    0.000175       one_twos
931286          1614646280987693    0.000612       one_twos
931287          1614646280991701    0.000754       one_twos
931288          1614646280995708    0.000452       one_twos
931289          1614646280999715   -0.000157       one_twos

[7487 rows x 3 columns]

In [34]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=51, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=52, second=15)
end_ts=int(end.timestamp() * 1e6)

DF30= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-34-ec76f3665bbb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

        Timestamp (microseconds)  Sample (V) Activity_Label
937279          1614646305003919    0.002065          hooks
937280          1614646305007927    0.002071          hooks
937281          1614646305011934    0.002065          hooks
937282          1614646305015941    0.002053          hooks
937283          1614646305019949    0.002034          hooks
...                          ...         ...            ...
944760          1614646334982654    0.003628          hooks
944761          1614646334986662    0.003616          hooks
944762          1614646334990669    0.003597          hooks
944763          1614646334994676    0.003560          hooks
944764          1614646334998684    0.003523          hooks

[7486 rows x 3 columns]

In [35]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=52, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=53, second=21)
end_ts=int(end.timestamp() * 1e6)

DF31= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-35-26154fb3a353>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

        Timestamp (microseconds)  Sample (V) Activity_Label
953748          1614646371000644    0.002391     Upper_cuts
953749          1614646371004652    0.002403     Upper_cuts
953750          1614646371008659    0.002397     Upper_cuts
953751          1614646371012666    0.002397     Upper_cuts
953752          1614646371016674    0.002391     Upper_cuts
...                          ...         ...            ...
961230          1614646400983966    0.002896     Upper_cuts
961231          1614646400987974    0.002926     Upper_cuts
961232          1614646400991981    0.002933     Upper_cuts
961233          1614646400995988    0.002926     Upper_cuts
961234          1614646400999996    0.002902     Upper_cuts

[7487 rows x 3 columns]

In [36]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=54, second=0)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=54, second=30)
end_ts=int(end.timestamp() * 1e6)

DF32= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-36-f3dcc3cf0331>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

        Timestamp (microseconds)  Sample (V) Activity_Label
970967          1614646440002882    0.001849            run
970968          1614646440006889    0.001849            run
970969          1614646440010896    0.001849            run
970970          1614646440014904    0.001862            run
970971          1614646440018911    0.001874            run
...                          ...         ...            ...
978448          1614646469980728    0.001357            run
978449          1614646469984735    0.001412            run
978450          1614646469988742    0.001462            run
978451          1614646469992750    0.001468            run
978452          1614646469996757    0.001474            run

[7486 rows x 3 columns]

In [37]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=55, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=0, minute=55, second=36)
end_ts=int(end.timestamp() * 1e6)

DF33= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-37-78e3e95211d3>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

        Timestamp (microseconds)  Sample (V)       Activity_Label
987437          1614646506000990    0.002262  Punch_down_Up_Hooks
987438          1614646506004997    0.002317  Punch_down_Up_Hooks
987439          1614646506009004    0.002379  Punch_down_Up_Hooks
987440          1614646506013012    0.002428  Punch_down_Up_Hooks
987441          1614646506017019    0.002477  Punch_down_Up_Hooks
...                          ...         ...                  ...
994918          1614646535980396    0.002428  Punch_down_Up_Hooks
994919          1614646535984404    0.002422  Punch_down_Up_Hooks
994920          1614646535988412    0.002403  Punch_down_Up_Hooks
994921          1614646535992419    0.002397  Punch_down_Up_Hooks
994922          1614646535996427    0.002397  Punch_down_Up_Hooks

[7486 rows x 3 columns]

In [38]:
sub05_final_chest_elec=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub05_final_chest_elec

        Timestamp (microseconds)  Sample (V)             Activity_Label
0               1614642696002603    0.001812  Forward and backward step
1               1614642696006610    0.001806  Forward and backward step
2               1614642696010618    0.001812  Forward and backward step
3               1614642696014625    0.001800  Forward and backward step
4               1614642696018633    0.001794  Forward and backward step
...                          ...         ...                        ...
434163          1614646535980396    0.002428        Punch_down_Up_Hooks
434164          1614646535984404    0.002422        Punch_down_Up_Hooks
434165          1614646535988412    0.002403        Punch_down_Up_Hooks
434166          1614646535992419    0.002397        Punch_down_Up_Hooks
434167          1614646535996427    0.002397        Punch_down_Up_Hooks

[434168 rows x 3 columns]

In [39]:
sub05_final_chest_elec.to_csv('final_cleaned_chest_elec-sub05.csv-sub05')