In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [5]:
df1=pd.read_csv('chest_elec.csv-sub01')

#

In [6]:
df1

        Timestamp (microseconds)  Sample (V)
0               1614540756261016   -0.015919
1               1614540756265019   -0.015537
2               1614540756269022   -0.015155
3               1614540756273024   -0.014817
4               1614540756277027   -0.014521
...                          ...         ...
951717          1614544567854383   -0.010681
951718          1614544567858388   -0.010681
951719          1614544567862393   -0.010681
951720          1614544567866397   -0.010687
951721          1614544567870402   -0.010687

[951722 rows x 2 columns]

In [7]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-02-28 19:32:36.261016')

In [9]:
start = pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=33, second=30)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=34, second=30)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-9-0eac88270dbb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

       Timestamp (microseconds)  Sample (V)             Activity_Label
13422          1614540810001538   -0.010564  Forward and backward step
13423          1614540810005542   -0.010558  Forward and backward step
13424          1614540810009546   -0.010564  Forward and backward step
13425          1614540810013550   -0.010570  Forward and backward step
13426          1614540810017554   -0.010570  Forward and backward step
...                         ...         ...                        ...
28402          1614540869982130   -0.011333  Forward and backward step
28403          1614540869986134   -0.011340  Forward and backward step
28404          1614540869990139   -0.011333  Forward and backward step
28405          1614540869994143   -0.011340  Forward and backward step
28406          1614540869998148   -0.011333  Forward and backward step

[14985 rows x 3 columns]

In [10]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=35, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=36, second=30)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-10-6149fb3799e2>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

       Timestamp (microseconds)  Sample (V) Activity_Label
43391          1614540930001059   -0.010115  Sideward step
43392          1614540930005064   -0.010256  Sideward step
43393          1614540930009068   -0.010466  Sideward step
43394          1614540930013073   -0.010595  Sideward step
43395          1614540930017077   -0.010632  Sideward step
...                         ...         ...            ...
58370          1614540989980585   -0.010275  Sideward step
58371          1614540989984589   -0.010269  Sideward step
58372          1614540989988594   -0.010269  Sideward step
58373          1614540989992598   -0.010275  Sideward step
58374          1614540989996603   -0.010263  Sideward step

[14984 rows x 3 columns]

In [11]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=37, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=38, second=5)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-11-d5cfe6bf41a2>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

       Timestamp (microseconds)  Sample (V) Activity_Label
67116          1614541025001663   -0.010386        Pushups
67117          1614541025005667   -0.010410        Pushups
67118          1614541025009672   -0.010398        Pushups
67119          1614541025013676   -0.010386        Pushups
67120          1614541025017681   -0.010386        Pushups
...                         ...         ...            ...
82095          1614541084983163   -0.010650        Pushups
82096          1614541084987167   -0.009943        Pushups
82097          1614541084991171   -0.010072        Pushups
82098          1614541084995176   -0.010361        Pushups
82099          1614541084999180   -0.010232        Pushups

[14984 rows x 3 columns]

In [12]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=39, second=11)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=40, second=11)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-12-fc4672a9299a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Sample (V),Activity_Label
98582,1614541151003610,-0.010133,Hip raise step with punches in the air
98583,1614541151007615,-0.010146,Hip raise step with punches in the air
98584,1614541151011619,-0.010139,Hip raise step with punches in the air
98585,1614541151015624,-0.010133,Hip raise step with punches in the air
98586,1614541151019628,-0.010139,Hip raise step with punches in the air
...,...,...,...
113561,1614541210983981,-0.010872,Hip raise step with punches in the air
113562,1614541210987985,-0.010847,Hip raise step with punches in the air
113563,1614541210991990,-0.010804,Hip raise step with punches in the air
113564,1614541210995994,-0.010798,Hip raise step with punches in the air
113565,1614541210999999,-0.010767,Hip raise step with punches in the air

In [13]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=41, second=10)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=42, second=10)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-13-c7f94ef2835e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

        Timestamp (microseconds)  Sample (V)          Activity_Label
128299          1614541270000178   -0.010478  Front and back scooter
128300          1614541270004182   -0.010478  Front and back scooter
128301          1614541270008187   -0.010472  Front and back scooter
128302          1614541270012191   -0.010478  Front and back scooter
128303          1614541270016196   -0.010478  Front and back scooter
...                          ...         ...                     ...
143278          1614541329981992   -0.010429  Front and back scooter
143279          1614541329985997   -0.010416  Front and back scooter
143280          1614541329990001   -0.010410  Front and back scooter
143281          1614541329994006   -0.010392  Front and back scooter
143282          1614541329998010   -0.010386  Front and back scooter

[14984 rows x 3 columns]

In [14]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=42, second=50)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=43, second=50)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-14-565b1f3c8817>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

        Timestamp (microseconds)  Sample (V) Activity_Label
153272          1614541370002525   -0.010484  Belly Scooter
153273          1614541370006529   -0.010576  Belly Scooter
153274          1614541370010534   -0.010583  Belly Scooter
153275          1614541370014538   -0.010521  Belly Scooter
153276          1614541370018543   -0.010484  Belly Scooter
...                          ...         ...            ...
168249          1614541429981798   -0.010613  Belly Scooter
168250          1614541429985803   -0.010626  Belly Scooter
168251          1614541429989808   -0.010632  Belly Scooter
168252          1614541429993813   -0.010644  Belly Scooter
168253          1614541429997818   -0.010638  Belly Scooter

[14982 rows x 3 columns]

In [15]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=44, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=45, second=56)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-15-1477e7540475>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

        Timestamp (microseconds)  Sample (V)    Activity_Label
184733          1614541496000636   -0.010940  Circular Scooter
184734          1614541496004641   -0.010921  Circular Scooter
184735          1614541496008646   -0.010927  Circular Scooter
184736          1614541496012651   -0.010921  Circular Scooter
184737          1614541496016656   -0.010915  Circular Scooter
...                          ...         ...               ...
199709          1614541555981666   -0.010638  Circular Scooter
199710          1614541555985672   -0.010644  Circular Scooter
199711          1614541555989677   -0.010638  Circular Scooter
199712          1614541555993682   -0.010650  Circular Scooter
199713          1614541555997688   -0.010650  Circular Scooter

[14981 rows x 3 columns]

In [16]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=47, second=9)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=48, second=9)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-16-7e30ec82c6bd>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

        Timestamp (microseconds)  Sample (V) Activity_Label
217941          1614541629003517   -0.010429   Cycling Slow
217942          1614541629007522   -0.010429   Cycling Slow
217943          1614541629011528   -0.010435   Cycling Slow
217944          1614541629015533   -0.010447   Cycling Slow
217945          1614541629019539   -0.010435   Cycling Slow
...                          ...         ...            ...
232917          1614541688982039   -0.010220   Cycling Slow
232918          1614541688986044   -0.010232   Cycling Slow
232919          1614541688990049   -0.010238   Cycling Slow
232920          1614541688994053   -0.010220   Cycling Slow
232921          1614541688998058   -0.010232   Cycling Slow

[14981 rows x 3 columns]

In [17]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=48, second=10)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=49, second=10)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-17-48cf4f2785dd>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

        Timestamp (microseconds)  Sample (V) Activity_Label
233172          1614541690003266   -0.010109   Cycling Fast
233173          1614541690007271   -0.010121   Cycling Fast
233174          1614541690011276   -0.010103   Cycling Fast
233175          1614541690015281   -0.010078   Cycling Fast
233176          1614541690019286   -0.010072   Cycling Fast
...                          ...         ...            ...
248149          1614541749980841   -0.010509   Cycling Fast
248150          1614541749984846   -0.010515   Cycling Fast
248151          1614541749988850   -0.010533   Cycling Fast
248152          1614541749992855   -0.010527   Cycling Fast
248153          1614541749996859   -0.010533   Cycling Fast

[14982 rows x 3 columns]

In [18]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=50, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=51, second=37)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-18-9c5b592e39e9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
269880          1614541837000534   -0.011167  Medicine_ball
269881          1614541837004538   -0.011321  Medicine_ball
269882          1614541837008543   -0.011284  Medicine_ball
269883          1614541837012547   -0.011137  Medicine_ball
269884          1614541837016552   -0.011007  Medicine_ball
...                          ...         ...            ...
284859          1614541896983376   -0.010546  Medicine_ball
284860          1614541896987381   -0.010663  Medicine_ball
284861          1614541896991385   -0.010743  Medicine_ball
284862          1614541896995390   -0.010761  Medicine_ball
284863          1614541896999394   -0.010829  Medicine_ball

[14984 rows x 3 columns]

In [19]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=52, second=13)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=53, second=13)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-19-406e0154fd17>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

        Timestamp (microseconds)  Sample (V)              Activity_Label
293853          1614541933000331   -0.010724  Medicine ball with burpies
293854          1614541933004335   -0.010767  Medicine ball with burpies
293855          1614541933008340   -0.010780  Medicine ball with burpies
293856          1614541933012344   -0.010773  Medicine ball with burpies
293857          1614541933016348   -0.010780  Medicine ball with burpies
...                          ...         ...                         ...
308831          1614541992981002   -0.011044  Medicine ball with burpies
308832          1614541992985007   -0.010496  Medicine ball with burpies
308833          1614541992989012   -0.010318  Medicine ball with burpies
308834          1614541992993017   -0.010478  Medicine ball with burpies
308835          1614541992997022   -0.010607  Medicine ball with burpies

[14983 rows x 3 columns]

In [20]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=53, second=42)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=54, second=42)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-20-94b20f9ca0fb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
316078          1614542022002471   -0.010503     punch ball
316079          1614542022006476   -0.010521     punch ball
316080          1614542022010481   -0.010533     punch ball
316081          1614542022014485   -0.010540     punch ball
316082          1614542022018490   -0.010527     punch ball
...                          ...         ...            ...
331055          1614542081980779   -0.010601     punch ball
331056          1614542081984784   -0.010638     punch ball
331057          1614542081988789   -0.010681     punch ball
331058          1614542081992794   -0.010681     punch ball
331059          1614542081996799   -0.010663     punch ball

[14982 rows x 3 columns]

In [21]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=56, second=36)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=57, second=36)
end_ts=int(end.timestamp() * 1e6)

DF13= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-21-a452feb0919a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

        Timestamp (microseconds)  Sample (V)   Activity_Label
359526          1614542196000815   -0.010650  Squarts Toe ups
359527          1614542196004820   -0.010644  Squarts Toe ups
359528          1614542196008825   -0.010650  Squarts Toe ups
359529          1614542196012830   -0.010656  Squarts Toe ups
359530          1614542196016835   -0.010656  Squarts Toe ups
...                          ...         ...              ...
374503          1614542255980252   -0.010663  Squarts Toe ups
374504          1614542255984257   -0.010669  Squarts Toe ups
374505          1614542255988262   -0.010675  Squarts Toe ups
374506          1614542255992267   -0.010718  Squarts Toe ups
374507          1614542255996272   -0.010767  Squarts Toe ups

[14982 rows x 3 columns]

In [22]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=58, second=1)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=59, second=1)
end_ts=int(end.timestamp() * 1e6)

DF14= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-22-009ce562053d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

        Timestamp (microseconds)  Sample (V) Activity_Label
380751          1614542281002014   -0.010583   Weight lifts
380752          1614542281006019   -0.010583   Weight lifts
380753          1614542281010024   -0.010601   Weight lifts
380754          1614542281014029   -0.010607   Weight lifts
380755          1614542281018034   -0.010613   Weight lifts
...                          ...         ...            ...
395728          1614542340982489   -0.010743   Weight lifts
395729          1614542340986494   -0.010736   Weight lifts
395730          1614542340990499   -0.010724   Weight lifts
395731          1614542340994504   -0.010724   Weight lifts
395732          1614542340998509   -0.010724   Weight lifts

[14982 rows x 3 columns]

In [23]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=19, minute=59, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=0, second=37)
end_ts=int(end.timestamp() * 1e6)

DF15= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-23-ac94358ae792>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

        Timestamp (microseconds)  Sample (V)      Activity_Label
404722          1614542377002662   -0.010133  Heavy Weight lifts
404723          1614542377006667   -0.010139  Heavy Weight lifts
404724          1614542377010672   -0.010207  Heavy Weight lifts
404725          1614542377014677   -0.010250  Heavy Weight lifts
404726          1614542377018682   -0.010183  Heavy Weight lifts
...                          ...         ...                 ...
419698          1614542436980322   -0.010724  Heavy Weight lifts
419699          1614542436984327   -0.010712  Heavy Weight lifts
419700          1614542436988332   -0.010700  Heavy Weight lifts
419701          1614542436992337   -0.010700  Heavy Weight lifts
419702          1614542436996342   -0.010712  Heavy Weight lifts

[14981 rows x 3 columns]

In [24]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=2, second=54)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=3, second=54)
end_ts=int(end.timestamp() * 1e6)

DF16= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-24-526001b53d17>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

        Timestamp (microseconds)  Sample (V)          Activity_Label
453912          1614542574003963   -0.010349  Forward Lunges on Bosu
453913          1614542574007968   -0.010343  Forward Lunges on Bosu
453914          1614542574011973   -0.010343  Forward Lunges on Bosu
453915          1614542574015978   -0.010343  Forward Lunges on Bosu
453916          1614542574019983   -0.010349  Forward Lunges on Bosu
...                          ...         ...                     ...
468888          1614542633980708   -0.010164  Forward Lunges on Bosu
468889          1614542633984713   -0.010318  Forward Lunges on Bosu
468890          1614542633988718   -0.010416  Forward Lunges on Bosu
468891          1614542633992723   -0.010466  Forward Lunges on Bosu
468892          1614542633996728   -0.010503  Forward Lunges on Bosu

[14981 rows x 3 columns]

In [25]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=5, second=20)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=6, second=20)
end_ts=int(end.timestamp() * 1e6)

DF17= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-25-064fe2983e1b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
490367          1614542720000869   -0.010693  Split squart left on Bosu
490368          1614542720004874   -0.010687  Split squart left on Bosu
490369          1614542720008879   -0.010687  Split squart left on Bosu
490370          1614542720012884   -0.010675  Split squart left on Bosu
490371          1614542720016889   -0.010669  Split squart left on Bosu
...                          ...         ...                        ...
505344          1614542779982168   -0.010503  Split squart left on Bosu
505345          1614542779986173   -0.010490  Split squart left on Bosu
505346          1614542779990178   -0.010496  Split squart left on Bosu
505347          1614542779994183   -0.010503  Split squart left on Bosu
505348          1614542779998188   -0.010496  Split squart left on Bosu

[14982 rows x 3 columns]

In [26]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=6, second=21)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=7, second=21)
end_ts=int(end.timestamp() * 1e6)

DF18= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-26-3b6bbd92101a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

        Timestamp (microseconds)  Sample (V)              Activity_Label
505599          1614542781003395   -0.010620  Split squart right on Bosu
505600          1614542781007400   -0.010632  Split squart right on Bosu
505601          1614542781011405   -0.010656  Split squart right on Bosu
505602          1614542781015410   -0.010656  Split squart right on Bosu
505603          1614542781019415   -0.010626  Split squart right on Bosu
...                          ...         ...                         ...
520575          1614542840980323   -0.010503  Split squart right on Bosu
520576          1614542840984328   -0.010496  Split squart right on Bosu
520577          1614542840988333   -0.010496  Split squart right on Bosu
520578          1614542840992338   -0.010490  Split squart right on Bosu
520579          1614542840996343   -0.010503  Split squart right on Bosu

[14981 rows x 3 columns]

In [27]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=9, second=50)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=10, second=50)
end_ts=int(end.timestamp() * 1e6)

DF19= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-27-788afebcb202>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
557783          1614542990003212   -0.010207  plank pie on Bosu
557784          1614542990007202   -0.010213  plank pie on Bosu
557785          1614542990011207   -0.010220  plank pie on Bosu
557786          1614542990015213   -0.010226  plank pie on Bosu
557787          1614542990019218   -0.010232  plank pie on Bosu
...                          ...         ...                ...
572758          1614543049983749   -0.010730  plank pie on Bosu
572759          1614543049987754   -0.010743  plank pie on Bosu
572760          1614543049991760   -0.010749  plank pie on Bosu
572761          1614543049995765   -0.010755  plank pie on Bosu
572762          1614543049999771   -0.010767  plank pie on Bosu

[14980 rows x 3 columns]

In [28]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=11, second=16)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=12, second=10)
end_ts=int(end.timestamp() * 1e6)

DF20= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-28-7c7d8bd29913>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
579254          1614543076003082   -0.010798  plank top on Bosu
579255          1614543076007087   -0.010804  plank top on Bosu
579256          1614543076011108   -0.010798  plank top on Bosu
579257          1614543076015113   -0.010798  plank top on Bosu
579258          1614543076019119   -0.010786  plank top on Bosu
...                          ...         ...                ...
592730          1614543129981639   -0.010558  plank top on Bosu
592731          1614543129985644   -0.010404  plank top on Bosu
592732          1614543129989650   -0.010176  plank top on Bosu
592733          1614543129993656   -0.009967  plank top on Bosu
592734          1614543129997662   -0.009912  plank top on Bosu

[13481 rows x 3 columns]

In [29]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=13, second=12)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=14, second=12)
end_ts=int(end.timestamp() * 1e6)

DF21= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-29-5e3b7b6bbed4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

        Timestamp (microseconds)  Sample (V) Activity_Label
608213          1614543192001081   -0.010207   dips on Bosu
608214          1614543192005087   -0.010404   dips on Bosu
608215          1614543192009092   -0.010589   dips on Bosu
608216          1614543192013098   -0.010687   dips on Bosu
608217          1614543192017104   -0.010693   dips on Bosu
...                          ...         ...            ...
623187          1614543251981107   -0.010656   dips on Bosu
623188          1614543251985113   -0.010663   dips on Bosu
623189          1614543251989119   -0.010663   dips on Bosu
623190          1614543251993125   -0.010669   dips on Bosu
623191          1614543251997130   -0.010663   dips on Bosu

[14979 rows x 3 columns]

In [30]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=15, second=0)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=16, second=0)
end_ts=int(end.timestamp() * 1e6)

DF22= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-30-88ce99b0d6ae>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

        Timestamp (microseconds)  Sample (V)                Activity_Label
635175          1614543300001447   -0.010767  moveforward backward on Bosu
635176          1614543300005453   -0.010718  moveforward backward on Bosu
635177          1614543300009459   -0.010687  moveforward backward on Bosu
635178          1614543300013465   -0.010730  moveforward backward on Bosu
635179          1614543300017470   -0.010755  moveforward backward on Bosu
...                          ...         ...                           ...
650149          1614543359982328   -0.010355  moveforward backward on Bosu
650150          1614543359986333   -0.010367  moveforward backward on Bosu
650151          1614543359990339   -0.010361  moveforward backward on Bosu
650152          1614543359994345   -0.010355  moveforward backward on Bosu
650153          1614543359998351   -0.010330  moveforward backward on Bosu

[14979 rows x 3 columns]

In [31]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=16, second=47)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=17, second=47)
end_ts=int(end.timestamp() * 1e6)

DF23= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-31-13cd6b7f967b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)            Activity_Label
661887          1614543407003687   -0.011149  Left leg Hip ups on Bosu
661888          1614543407007693   -0.011149  Left leg Hip ups on Bosu
661889          1614543407011699   -0.011161  Left leg Hip ups on Bosu
661890          1614543407015705   -0.011155  Left leg Hip ups on Bosu
661891          1614543407019711   -0.011161  Left leg Hip ups on Bosu
...                          ...         ...                       ...
676860          1614543466981172   -0.010970  Left leg Hip ups on Bosu
676861          1614543466985178   -0.010970  Left leg Hip ups on Bosu
676862          1614543466989184   -0.010983  Left leg Hip ups on Bosu
676863          1614543466993190   -0.010983  Left leg Hip ups on Bosu
676864          1614543466997196   -0.010977  Left leg Hip ups on Bosu

[14978 rows x 3 columns]

In [32]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=17, second=50)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=18, second=50)
end_ts=int(end.timestamp() * 1e6)

DF24= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-32-9eab59b4ef94>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
677614          1614543470001431   -0.010669  right leg Hip ups on Bosu
677615          1614543470005437   -0.010669  right leg Hip ups on Bosu
677616          1614543470009443   -0.010669  right leg Hip ups on Bosu
677617          1614543470013449   -0.010681  right leg Hip ups on Bosu
677618          1614543470017455   -0.010675  right leg Hip ups on Bosu
...                          ...         ...                        ...
692588          1614543529980713   -0.010281  right leg Hip ups on Bosu
692589          1614543529984718   -0.010324  right leg Hip ups on Bosu
692590          1614543529988723   -0.010336  right leg Hip ups on Bosu
692591          1614543529992729   -0.010343  right leg Hip ups on Bosu
692592          1614543529996734   -0.010355  right leg Hip ups on Bosu

[14979 rows x 3 columns]

In [33]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=19, second=20)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=20, second=6)
end_ts=int(end.timestamp() * 1e6)

DF25= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-33-72c93f8d9ead>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

        Timestamp (microseconds)  Sample (V)         Activity_Label
700083          1614543560002975   -0.010736  V-Shift Swift on Bosu
700084          1614543560006981   -0.010743  V-Shift Swift on Bosu
700085          1614543560010986   -0.010743  V-Shift Swift on Bosu
700086          1614543560014992   -0.010773  V-Shift Swift on Bosu
700087          1614543560018998   -0.010773  V-Shift Swift on Bosu
...                          ...         ...                    ...
711561          1614543605981114   -0.010386  V-Shift Swift on Bosu
711562          1614543605985119   -0.010392  V-Shift Swift on Bosu
711563          1614543605989125   -0.010398  V-Shift Swift on Bosu
711564          1614543605993131   -0.010410  V-Shift Swift on Bosu
711565          1614543605997137   -0.010416  V-Shift Swift on Bosu

[11483 rows x 3 columns]

In [34]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=24, second=9)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=24, second=39)
end_ts=int(end.timestamp() * 1e6)

DF26= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-34-1532cc2b44b5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

        Timestamp (microseconds)  Sample (V)    Activity_Label
772228          1614543849002060   -0.010250  Freestyle Boxing
772229          1614543849006065   -0.010256  Freestyle Boxing
772230          1614543849010070   -0.010256  Freestyle Boxing
772231          1614543849014076   -0.010244  Freestyle Boxing
772232          1614543849018081   -0.010207  Freestyle Boxing
...                          ...         ...               ...
779713          1614543878982627   -0.010435  Freestyle Boxing
779714          1614543878986633   -0.010447  Freestyle Boxing
779715          1614543878990638   -0.010472  Freestyle Boxing
779716          1614543878994644   -0.010484  Freestyle Boxing
779717          1614543878998649   -0.010484  Freestyle Boxing

[7490 rows x 3 columns]

In [35]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=34, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=35, second=25)
end_ts=int(end.timestamp() * 1e6)

DF27= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-35-c2e3a329ecd2>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

        Timestamp (microseconds)  Sample (V)           Activity_Label
933526          1614544495003002   -0.010244  Left_Right_Punches_flip
933527          1614544495007007   -0.010244  Left_Right_Punches_flip
933528          1614544495011012   -0.010250  Left_Right_Punches_flip
933529          1614544495015017   -0.010244  Left_Right_Punches_flip
933530          1614544495019022   -0.010250  Left_Right_Punches_flip
...                          ...         ...                      ...
941012          1614544524983248   -0.010226  Left_Right_Punches_flip
941013          1614544524987253   -0.010213  Left_Right_Punches_flip
941014          1614544524991258   -0.010220  Left_Right_Punches_flip
941015          1614544524995263   -0.010256  Left_Right_Punches_flip
941016          1614544524999268   -0.010373  Left_Right_Punches_flip

[7491 rows x 3 columns]

In [36]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=26, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=27, second=0)
end_ts=int(end.timestamp() * 1e6)

DF28= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-36-61e675806f5c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

        Timestamp (microseconds)  Sample (V)    Activity_Label
807431          1614543990000250   -0.010860  left_Right_Punch
807432          1614543990004255   -0.010878  left_Right_Punch
807433          1614543990008260   -0.010915  left_Right_Punch
807434          1614543990012265   -0.010933  left_Right_Punch
807435          1614543990016270   -0.010903  left_Right_Punch
...                          ...         ...               ...
814917          1614544019982071   -0.010521  left_Right_Punch
814918          1614544019986076   -0.010527  left_Right_Punch
814919          1614544019990081   -0.010527  left_Right_Punch
814920          1614544019994086   -0.010527  left_Right_Punch
814921          1614544019998091   -0.010540  left_Right_Punch

[7491 rows x 3 columns]

In [37]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=28, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=29, second=10)
end_ts=int(end.timestamp() * 1e6)

DF29= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-37-a3ea04ef6d08>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

        Timestamp (microseconds)  Sample (V) Activity_Label
839891          1614544120003725   -0.010607       one_twos
839892          1614544120007730   -0.010607       one_twos
839893          1614544120011735   -0.010607       one_twos
839894          1614544120015740   -0.010607       one_twos
839895          1614544120019745   -0.010607       one_twos
...                          ...         ...            ...
847376          1614544149981857   -0.011143       one_twos
847377          1614544149985862   -0.011057       one_twos
847378          1614544149989868   -0.010995       one_twos
847379          1614544149993873   -0.010970       one_twos
847380          1614544149997879   -0.010970       one_twos

[7490 rows x 3 columns]

In [38]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=29, second=44)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=30, second=14)
end_ts=int(end.timestamp() * 1e6)

DF30= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-38-2b69fef1c448>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

        Timestamp (microseconds)  Sample (V) Activity_Label
855870          1614544184000164   -0.010435          hooks
855871          1614544184004169   -0.010546          hooks
855872          1614544184008174   -0.010576          hooks
855873          1614544184012179   -0.010601          hooks
855874          1614544184016183   -0.010650          hooks
...                          ...         ...            ...
863356          1614544213980795   -0.010533          hooks
863357          1614544213984799   -0.010533          hooks
863358          1614544213988804   -0.010546          hooks
863359          1614544213992809   -0.010546          hooks
863360          1614544213996814   -0.010546          hooks

[7491 rows x 3 columns]

In [39]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=32, second=10)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=32, second=40)
end_ts=int(end.timestamp() * 1e6)

DF31= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-39-d3e4a21905ee>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

        Timestamp (microseconds)  Sample (V) Activity_Label
892326          1614544330002844   -0.010909     Upper_cuts
892327          1614544330006849   -0.010933     Upper_cuts
892328          1614544330010854   -0.010952     Upper_cuts
892329          1614544330014859   -0.010970     Upper_cuts
892330          1614544330018864   -0.010983     Upper_cuts
...                          ...         ...            ...
899812          1614544359983903   -0.010589     Upper_cuts
899813          1614544359987908   -0.010576     Upper_cuts
899814          1614544359991912   -0.010576     Upper_cuts
899815          1614544359995917   -0.010583     Upper_cuts
899816          1614544359999922   -0.010583     Upper_cuts

[7491 rows x 3 columns]

In [40]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=33, second=25)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=33, second=55)
end_ts=int(end.timestamp() * 1e6)

DF32= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-40-b219018de2e6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

        Timestamp (microseconds)  Sample (V) Activity_Label
911053          1614544405003159   -0.010392            run
911054          1614544405007164   -0.010373            run
911055          1614544405011169   -0.010343            run
911056          1614544405015174   -0.010293            run
911057          1614544405019178   -0.010275            run
...                          ...         ...            ...
918539          1614544434983588   -0.010220            run
918540          1614544434987593   -0.010226            run
918541          1614544434991598   -0.010244            run
918542          1614544434995603   -0.010306            run
918543          1614544434999608   -0.010398            run

[7491 rows x 3 columns]

In [41]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=35, second=0)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=20, minute=35, second=30)
end_ts=int(end.timestamp() * 1e6)

DF33= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-41-b4ba166fc906>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

        Timestamp (microseconds)  Sample (V)       Activity_Label
934774          1614544500001078   -0.010423  Punch_down_Up_Hooks
934775          1614544500005083   -0.010447  Punch_down_Up_Hooks
934776          1614544500009088   -0.010453  Punch_down_Up_Hooks
934777          1614544500013093   -0.010460  Punch_down_Up_Hooks
934778          1614544500017098   -0.010478  Punch_down_Up_Hooks
...                          ...         ...                  ...
942260          1614544529981282   -0.010392  Punch_down_Up_Hooks
942261          1614544529985287   -0.010226  Punch_down_Up_Hooks
942262          1614544529989292   -0.010103  Punch_down_Up_Hooks
942263          1614544529993297   -0.010170  Punch_down_Up_Hooks
942264          1614544529997302   -0.010287  Punch_down_Up_Hooks

[7491 rows x 3 columns]

In [42]:
sub01_final_chest_elec=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub01_final_chest_elec

        Timestamp (microseconds)  Sample (V)             Activity_Label
0               1614540810001538   -0.010564  Forward and backward step
1               1614540810005542   -0.010558  Forward and backward step
2               1614540810009546   -0.010564  Forward and backward step
3               1614540810013550   -0.010570  Forward and backward step
4               1614540810017554   -0.010570  Forward and backward step
...                          ...         ...                        ...
429465          1614544529981282   -0.010392        Punch_down_Up_Hooks
429466          1614544529985287   -0.010226        Punch_down_Up_Hooks
429467          1614544529989292   -0.010103        Punch_down_Up_Hooks
429468          1614544529993297   -0.010170        Punch_down_Up_Hooks
429469          1614544529997302   -0.010287        Punch_down_Up_Hooks

[429470 rows x 3 columns]

In [43]:
sub01_final_chest_elec.to_csv('final_cleaned_chest_elec-sub01.csv-sub01')