In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('leg_gyro.csv-sub02')

In [3]:
df1

       Timestamp (microseconds)  Gyro X (°/s)  Gyro Y (°/s)  Gyro Z (°/s)
0              1614546063535278     -9.796292    -45.197223     17.181659
1              1614546063551272    -12.848096    -44.098573     20.294499
2              1614546063567267     -8.514534    -43.854429     22.308690
3              1614546063583262     -3.753719    -43.793393     19.745174
4              1614546063599256     -6.622416    -41.046769     16.937514
...                         ...           ...           ...           ...
93555          1614547558088844     -2.227817     -3.448539     -1.495384
93556          1614547558104820     -1.739528     -3.082322     -1.251240
93557          1614547558120795     -1.861601     -2.105745     -1.556420
93558          1614547558136771     -1.312276     -1.617456     -1.800565
93559          1614547558152746     -0.457771     -0.335698     -1.678492

[93560 rows x 4 columns]

In [4]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-02-28 21:01:03.535278')

In [5]:
start = pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=1, second=42)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=2, second=42)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-5-ab7a8690006c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
2408,1614546102005397,24.811170,-13.275349,7.476921,Forward and backward step
2409,1614546102021373,23.285267,-17.975128,9.430076,Forward and backward step
2410,1614546102037348,21.698329,-25.482567,11.627375,Forward and backward step
2411,1614546102053324,27.801938,-36.774243,9.185931,Forward and backward step
2412,1614546102069299,47.272450,-50.446326,8.880751,Forward and backward step
...,...,...,...,...,...
6159,1614546161929480,-25.665675,-101.228351,51.789120,Forward and backward step
6160,1614546161945434,-40.436408,-78.278782,62.104219,Forward and backward step
6161,1614546161961410,-56.183719,-51.422904,73.334859,Forward and backward step
6162,1614546161977385,-50.019074,-18.036164,83.161669,Forward and backward step
6163,1614546161993361,-31.158923,26.215000,82.185092,Forward and backward step

In [6]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=2, second=58)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=3, second=58)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-6-08206e5f85b5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
7165,1614546178000745,-14.435035,19.562066,12.603952,Sideward step
7166,1614546178016720,-5.523766,16.388190,15.106432,Sideward step
7167,1614546178032696,5.035477,13.092241,19.562066,Sideward step
7168,1614546178048671,3.753719,11.017014,18.280308,Sideward step
7169,1614546178064647,3.021286,11.322194,21.271077,Sideward step
...,...,...,...,...,...
10916,1614546237924492,69.184405,7.965209,43.244068,Sideward step
10917,1614546237940467,-323.460746,-7.904173,-61.249714,Sideward step
10918,1614546237956442,-131.441215,-64.057374,0.518807,Sideward step
10919,1614546237972418,135.774777,-67.475395,-16.815442,Sideward step
10920,1614546237988372,150.240330,-80.231937,-39.826047,Sideward step

In [7]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=4, second=42)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=5, second=42)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-7-2888d9db6424>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
13675,1614546282000740,1.068132,-0.701915,-10.223545,Pushups
13676,1614546282016716,-1.007095,4.486152,-11.871519,Pushups
13677,1614546282032691,-1.983673,9.308003,-12.787060,Pushups
13678,1614546282048667,-3.387503,7.232776,-13.092241,Pushups
13679,1614546282064642,-0.457771,-0.030518,-13.031205,Pushups
...,...,...,...,...,...
17426,1614546341925290,-2.899214,-1.922637,-2.777142,Pushups
17427,1614546341941265,-2.410925,-2.288853,-1.373312,Pushups
17428,1614546341957241,-3.021286,-4.119936,-0.335698,Pushups
17429,1614546341973216,2.288853,-4.364080,3.143359,Pushups
17430,1614546341989192,-3.021286,-6.500343,7.171740,Pushups

In [8]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=6, second=26)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=7, second=26)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-8-569cdf13fc52>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
20185,1614546386002149,4.364080,6.378271,5.218585,Hip raise step with punches in the air
20186,1614546386018124,9.979400,9.124895,4.364080,Hip raise step with punches in the air
20187,1614546386034100,15.716793,11.322194,3.875792,Hip raise step with punches in the air
20188,1614546386050075,18.707561,11.505303,3.692683,Hip raise step with punches in the air
20189,1614546386066051,20.111391,11.749447,1.922637,Hip raise step with punches in the air
...,...,...,...,...,...
23936,1614546445926818,17.059586,0.640879,-3.082322,Hip raise step with punches in the air
23937,1614546445942794,9.124895,0.640879,0.030518,Hip raise step with punches in the air
23938,1614546445958770,3.753719,0.213626,-2.044709,Hip raise step with punches in the air
23939,1614546445974746,7.232776,-1.983673,-3.875792,Hip raise step with punches in the air
23940,1614546445990692,11.871519,-4.791333,-2.166781,Hip raise step with punches in the air

In [9]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=8, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=9, second=6)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-9-fa535ec846bc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
26445,1614546486010086,-6.073091,-11.139086,8.331426,Front and back scooter
26446,1614546486026062,-35.187304,-12.298772,24.261845,Front and back scooter
26447,1614546486042038,10.711833,-20.416571,24.017700,Front and back scooter
26448,1614546486058014,46.845197,-31.891356,10.467689,Front and back scooter
26449,1614546486073989,37.506676,-35.614557,3.936828,Front and back scooter
...,...,...,...,...,...
30196,1614546545934806,-14.618143,-26.153964,2.899214,Front and back scooter
30197,1614546545950782,-6.622416,-27.130541,0.518807,Front and back scooter
30198,1614546545966757,1.678492,-34.821088,11.505303,Front and back scooter
30199,1614546545982733,-3.936828,-38.605325,7.660029,Front and back scooter
30200,1614546545998687,-5.706874,-33.600366,7.293812,Front and back scooter

In [10]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=9, second=42)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=10, second=42)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-10-fefe9f7bffac>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
32454,1614546582007439,7.537957,0.823987,-0.091554,Belly Scooter
32455,1614546582023415,19.623102,0.213626,-6.317235,Belly Scooter
32456,1614546582039390,32.745861,1.556420,-10.040436,Belly Scooter
32457,1614546582055366,32.135500,-0.396735,-14.740215,Belly Scooter
32458,1614546582071341,32.135500,-1.129168,-20.172427,Belly Scooter
...,...,...,...,...,...
36205,1614546641931623,-16.693370,-9.369039,45.136187,Belly Scooter
36206,1614546641947598,-23.895628,-7.293812,43.549248,Belly Scooter
36207,1614546641963574,-13.153277,-6.317235,44.892042,Belly Scooter
36208,1614546641979549,-13.275349,-6.073091,45.075151,Belly Scooter
36209,1614546641995525,-27.618830,-5.645838,43.976501,Belly Scooter

In [11]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=10, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=11, second=48)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-11-0ce6205528b1>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
36585,1614546648002362,-2.166781,-1.068132,-9.246967,Circular Scooter
36586,1614546648018338,53.131914,4.425116,-6.683452,Circular Scooter
36587,1614546648034313,39.887083,13.336385,-3.814755,Circular Scooter
36588,1614546648050289,-12.848096,16.754406,-12.176699,Circular Scooter
36589,1614546648066264,-15.777829,16.632334,-12.420844,Circular Scooter
...,...,...,...,...,...
40336,1614546707926628,-62.043183,10.345617,55.634394,Circular Scooter
40337,1614546707942603,-65.766384,9.308003,51.606012,Circular Scooter
40338,1614546707958579,-54.962997,7.598993,49.042496,Circular Scooter
40339,1614546707974554,-41.412985,6.622416,40.985733,Circular Scooter
40340,1614546707990539,-34.637980,8.453498,39.398795,Circular Scooter

In [12]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=13, second=39)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=14, second=39)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-12-6ca9c089f5db>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
47289,1614546819003368,-4.730297,-23.285267,-5.035477,Cycling Slow
47290,1614546819019343,-7.049668,-25.177386,-3.082322,Cycling Slow
47291,1614546819035318,-9.430076,-24.994278,-1.922637,Cycling Slow
47292,1614546819051294,-7.965209,-24.383917,-1.434348,Cycling Slow
47293,1614546819067269,2.227817,-27.679866,-2.349889,Cycling Slow
...,...,...,...,...,...
51040,1614546878925171,11.383230,45.014115,4.180972,Cycling Slow
51041,1614546878941145,-2.471962,36.041810,4.730297,Cycling Slow
51042,1614546878957120,15.838865,31.158923,4.242008,Cycling Slow
51043,1614546878973094,1.983673,32.684825,8.331426,Cycling Slow
51044,1614546878989069,-26.153964,24.200809,3.204395,Cycling Slow

In [13]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=14, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=15, second=40)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-13-e987b5c5c9ad>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
51108,1614546880011432,80.781262,94.514382,-47.821775,Cycling Fast
51109,1614546880027407,113.496605,90.547036,-36.652171,Cycling Fast
51110,1614546880043381,99.580377,81.879911,-23.285267,Cycling Fast
51111,1614546880059356,59.540703,60.212100,-16.449226,Cycling Fast
51112,1614546880075330,55.268177,51.667048,-12.359808,Cycling Fast
...,...,...,...,...,...
54859,1614546939930063,24.322881,-27.740902,17.242695,Cycling Fast
54860,1614546939946045,-9.613184,-42.328527,22.613870,Cycling Fast
54861,1614546939962019,-18.341344,-61.310750,22.186618,Cycling Fast
54862,1614546939977993,-2.532998,-83.344778,15.838865,Cycling Fast
54863,1614546939993967,3.936828,-99.336233,12.420844,Cycling Fast

In [14]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=17, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=18, second=35)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-14-81a58fd31854>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
62063,1614547055006540,-17.608911,-20.477607,20.416571,Medicine_ball
62064,1614547055022514,-22.308690,-27.618830,24.261845,Medicine_ball
62065,1614547055038488,-29.999237,-23.590448,28.412299,Medicine_ball
62066,1614547055054462,-41.351949,-27.252613,31.952392,Medicine_ball
62067,1614547055070436,-55.939574,-28.656443,36.408026,Medicine_ball
...,...,...,...,...,...
65814,1614547114926676,-9.674220,-3.875792,4.242008,Medicine_ball
65815,1614547114942651,-9.735256,-3.936828,0.762951,Medicine_ball
65816,1614547114958625,-10.040436,-2.594034,0.457771,Medicine_ball
65817,1614547114974600,-8.758679,-0.579843,0.701915,Medicine_ball
65818,1614547114990574,-3.143359,1.129168,0.579843,Medicine_ball

In [15]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=19, second=22)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=20, second=22)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-15-2f7dc500ac6a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
68761,1614547162004072,-39.093614,4.974441,-22.858015,Medicine ball with burpies
68762,1614547162020047,-24.383917,7.721065,-29.144732,Medicine ball with burpies
68763,1614547162036021,10.650797,15.289540,-34.882124,Medicine ball with burpies
68764,1614547162051996,13.519493,11.810483,-32.867933,Medicine ball with burpies
68765,1614547162067970,4.791333,3.326467,-24.383917,Medicine ball with burpies
...,...,...,...,...,...
72512,1614547221925647,0.152590,41.901274,8.941787,Medicine ball with burpies
72513,1614547221941622,-0.396735,43.793393,9.369039,Medicine ball with burpies
72514,1614547221957597,22.247654,36.957351,1.678492,Medicine ball with burpies
72515,1614547221973572,35.126268,49.408713,7.110704,Medicine ball with burpies
72516,1614547221989547,21.576257,45.807584,6.012055,Medicine ball with burpies

In [16]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=21, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=22, second=14)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-16-d0ed01ea138e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
75772,1614547274003772,-40.680552,-27.008469,13.580529,punch ball
75773,1614547274019747,-34.332799,-25.421530,7.598993,punch ball
75774,1614547274035722,-24.567025,-23.468376,11.383230,punch ball
75775,1614547274051697,-35.370413,-28.107118,10.040436,punch ball
75776,1614547274067672,-15.289540,-22.308690,9.124895,punch ball
...,...,...,...,...,...
79523,1614547333925854,65.278096,32.257572,-7.537957,punch ball
79524,1614547333941829,86.945907,36.408026,-15.472648,punch ball
79525,1614547333957804,101.106279,21.210040,-21.820401,punch ball
79526,1614547333973779,83.527886,23.834592,-24.505989,punch ball
79527,1614547333989754,80.598154,22.980087,-14.068818,punch ball

In [17]:
df2=pd.read_csv('leg_gyro.csv-sub02-folder2')

In [18]:
df2

        Timestamp (microseconds)  Gyro X (°/s)  Gyro Y (°/s)  Gyro Z (°/s)
0               1614547834469329      1.556420      0.274662     -1.129168
1               1614547834485324      1.251240      0.091554     -1.312276
2               1614547834501320      0.823987     -0.030518     -1.068132
3               1614547834517315      1.129168     -0.091554     -1.190204
4               1614547834533310      2.044709      0.091554     -1.495384
...                          ...           ...           ...           ...
124595          1614549824892694    -25.726711     72.907607      3.143359
124596          1614549824908668    -29.327840     65.644312     -4.486152
124597          1614549824924643     -7.537957     39.459831     11.932555
124598          1614549824940617     -1.922637      9.735256     19.439994
124599          1614549824956592     -8.575570      7.660029     15.045396

[124600 rows x 4 columns]

In [19]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=31, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=32, second=5)
end_ts=int(end.timestamp() * 1e6)

DF13= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-19-d95deb96beeb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
1912,1614547865014789,-7.782101,5.096513,-9.369039,Squarts Toe ups
1913,1614547865030764,-12.298772,-0.762951,-2.044709,Squarts Toe ups
1914,1614547865046739,-11.688411,-5.279622,-2.349889,Squarts Toe ups
1915,1614547865062714,1.617456,-0.396735,-1.983673,Squarts Toe ups
1916,1614547865078689,5.951019,7.782101,4.730297,Squarts Toe ups
...,...,...,...,...,...
5662,1614547924921476,-7.476921,9.002823,1.800565,Squarts Toe ups
5663,1614547924937451,-21.026932,11.810483,3.387503,Squarts Toe ups
5664,1614547924953426,-16.449226,11.261158,0.274662,Squarts Toe ups
5665,1614547924969401,-2.105745,10.345617,-4.364080,Squarts Toe ups
5666,1614547924985376,8.087282,10.101472,-6.195163,Squarts Toe ups

In [20]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=32, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=33, second=37)
end_ts=int(end.timestamp() * 1e6)

DF14= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-20-4d91d95eefda>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
7671,1614547957015568,-51.056687,-35.797665,4.425116,Weight lifts
7672,1614547957031543,24.811170,-25.665675,-13.763638,Weight lifts
7673,1614547957047518,48.493172,-19.989319,-12.848096,Weight lifts
7674,1614547957063493,22.247654,-19.867247,-5.828946,Weight lifts
7675,1614547957079468,-10.040436,-17.547875,0.823987,Weight lifts
...,...,...,...,...,...
11421,1614548016922622,19.256886,1.922637,9.246967,Weight lifts
11422,1614548016938597,28.534371,-1.190204,3.936828,Weight lifts
11423,1614548016954573,27.740902,0.152590,0.457771,Weight lifts
11424,1614548016970548,13.031205,0.213626,2.777142,Weight lifts
11425,1614548016986524,-3.692683,-1.007095,4.242008,Weight lifts

In [21]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=34, second=43)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=35, second=43)
end_ts=int(end.timestamp() * 1e6)

DF15= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-21-afacfecb25b9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
15558,1614548083012320,-29.694057,2.899214,5.951019,Heavy Weight lifts
15559,1614548083028296,-14.557107,21.271077,-7.598993,Heavy Weight lifts
15560,1614548083044250,-21.698329,42.877852,-7.415885,Heavy Weight lifts
15561,1614548083060226,-53.070878,77.302205,11.139086,Heavy Weight lifts
15562,1614548083076201,-88.410773,95.063706,15.594720,Heavy Weight lifts
...,...,...,...,...,...
19309,1614548142935649,2.960250,4.242008,-1.617456,Heavy Weight lifts
19310,1614548142951624,1.007095,2.410925,-2.655070,Heavy Weight lifts
19311,1614548142967600,0.946059,2.105745,-2.594034,Heavy Weight lifts
19312,1614548142983575,-0.091554,1.739528,-1.556420,Heavy Weight lifts
19313,1614548142999551,-2.716106,3.753719,-0.640879,Heavy Weight lifts

In [22]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=36, second=13)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=37, second=10)
end_ts=int(end.timestamp() * 1e6)

DF16= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-22-03661f6b1e49>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
21191,1614548173001261,103.425650,-86.274510,-93.415732,Forward Lunges on Bosu
21192,1614548173017236,3.570611,-89.021134,25.482567,Forward Lunges on Bosu
21193,1614548173033212,-72.968643,-141.451133,34.515908,Forward Lunges on Bosu
21194,1614548173049187,-68.818189,-166.781109,0.823987,Forward Lunges on Bosu
21195,1614548173065163,31.769284,-147.432670,-21.820401,Forward Lunges on Bosu
...,...,...,...,...,...
24754,1614548229921037,97.505150,111.970703,-114.717327,Forward Lunges on Bosu
24755,1614548229937012,40.802625,136.385138,-88.410773,Forward Lunges on Bosu
24756,1614548229952987,-37.323568,144.686046,-67.719539,Forward Lunges on Bosu
24757,1614548229968962,-70.710307,144.258793,-69.611658,Forward Lunges on Bosu
24758,1614548229984937,-24.322881,151.033799,-59.479667,Forward Lunges on Bosu

In [23]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=37, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=38, second=48)
end_ts=int(end.timestamp() * 1e6)

DF17= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-23-d409ccdc3cda>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
27138,1614548268005537,18.585489,-33.966583,-21.820401,Split squart left on Bosu
27139,1614548268021512,32.440681,-29.266804,-10.772869,Split squart left on Bosu
27140,1614548268037506,-11.627375,-44.220645,2.471962,Split squart left on Bosu
27141,1614548268053481,-51.911192,-58.930343,-11.444266,Split squart left on Bosu
27142,1614548268069456,-44.586862,-62.287327,-32.318608,Split squart left on Bosu
...,...,...,...,...,...
30889,1614548327928076,10.162509,-5.096513,2.166781,Split squart left on Bosu
30890,1614548327944051,-19.684138,7.904173,11.383230,Split squart left on Bosu
30891,1614548327960026,-13.946746,15.350576,16.144045,Split squart left on Bosu
30892,1614548327976001,8.514534,11.810483,9.430076,Split squart left on Bosu
30893,1614548327991976,9.185931,9.124895,-7.904173,Split squart left on Bosu

In [24]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=28, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=39, second=56)
end_ts=int(end.timestamp() * 1e6)

DF18= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-24-b6f641265c34>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
0,1614547834469329,1.556420,0.274662,-1.129168,Split squart right on Bosu
1,1614547834485324,1.251240,0.091554,-1.312276,Split squart right on Bosu
2,1614547834501320,0.823987,-0.030518,-1.068132,Split squart right on Bosu
3,1614547834517315,1.129168,-0.091554,-1.190204,Split squart right on Bosu
4,1614547834533310,2.044709,0.091554,-1.495384,Split squart right on Bosu
...,...,...,...,...,...
35146,1614548395933862,26.886397,101.899748,-74.982834,Split squart right on Bosu
35147,1614548395949837,37.262531,107.270924,-90.363928,Split squart right on Bosu
35148,1614548395965812,46.601053,112.703136,-87.678340,Split squart right on Bosu
35149,1614548395981787,63.141833,108.735790,-78.706035,Split squart right on Bosu
35150,1614548395997762,68.696117,102.082856,-75.410086,Split squart right on Bosu

In [25]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=41, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=42, second=56)
end_ts=int(end.timestamp() * 1e6)

DF19= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-25-e72965f51e32>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
42662,1614548516002744,-5.157549,-58.869306,6.439307,plank pie on Bosu
42663,1614548516018719,-7.537957,-59.357595,4.058900,plank pie on Bosu
42664,1614548516034694,-5.462730,-60.944533,2.655070,plank pie on Bosu
42665,1614548516050669,6.256199,-61.799039,-3.814755,plank pie on Bosu
42666,1614548516066644,17.730983,-60.028992,-5.767910,plank pie on Bosu
...,...,...,...,...,...
46413,1614548575925723,9.063859,16.021973,-3.448539,plank pie on Bosu
46414,1614548575941698,8.636606,15.655756,-0.946059,plank pie on Bosu
46415,1614548575957673,1.678492,13.641566,2.777142,plank pie on Bosu
46416,1614548575973648,-2.899214,11.993591,2.227817,plank pie on Bosu
46417,1614548575989623,-0.091554,10.833906,-1.800565,plank pie on Bosu

In [26]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=43, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=44, second=35)
end_ts=int(end.timestamp() * 1e6)

DF20= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-26-a1a0fcb9dd9d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
48859,1614548615001135,26.092927,-4.913405,-13.824674,plank top on Bosu
48860,1614548615017120,43.305104,-2.594034,-16.510262,plank top on Bosu
48861,1614548615033095,27.374685,-1.556420,-11.810483,plank top on Bosu
48862,1614548615049071,9.796292,-0.701915,-7.354849,plank top on Bosu
48863,1614548615065046,14.007782,0.946059,-5.340658,plank top on Bosu
...,...,...,...,...,...
52610,1614548674924616,-81.025406,-10.589761,7.965209,plank top on Bosu
52611,1614548674940592,-68.146792,-5.584802,10.833906,plank top on Bosu
52612,1614548674956567,-38.910506,-7.476921,7.354849,plank top on Bosu
52613,1614548674972543,-16.937514,-5.279622,-4.242008,plank top on Bosu
52614,1614548674988518,-27.130541,-3.570611,-4.119936,plank top on Bosu

In [27]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=47, second=18)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=48, second=18)
end_ts=int(end.timestamp() * 1e6)

DF21= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-27-b879ed8696d0>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
62818,1614548838001883,-7.721065,-9.002823,11.505303,dips on Bosu
62819,1614548838017859,-14.862287,-7.293812,10.223545,dips on Bosu
62820,1614548838033874,-15.289540,-3.265431,11.444266,dips on Bosu
62821,1614548838049850,-10.711833,-2.655070,10.467689,dips on Bosu
62822,1614548838065825,-11.139086,-2.532998,7.843137,dips on Bosu
...,...,...,...,...,...
66569,1614548897927047,39.093614,-16.021973,-5.706874,dips on Bosu
66570,1614548897943023,43.915465,-13.946746,-4.730297,dips on Bosu
66571,1614548897958999,33.539330,-14.862287,-0.518807,dips on Bosu
66572,1614548897974975,9.796292,-19.501030,5.157549,dips on Bosu
66573,1614548897990951,-10.284581,-27.862974,12.603952,dips on Bosu

In [28]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=48, second=49)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=49, second=49)
end_ts=int(end.timestamp() * 1e6)

DF22= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-28-7965ea57549b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
68515,1614548929015915,-22.919051,2.716106,2.166781,moveforward backward on Bosu
68516,1614548929031890,-12.787060,-9.308003,1.495384,moveforward backward on Bosu
68517,1614548929047866,1.861601,-7.721065,-7.598993,moveforward backward on Bosu
68518,1614548929063842,11.688411,-3.875792,-12.787060,moveforward backward on Bosu
68519,1614548929079818,11.383230,0.396735,-10.223545,moveforward backward on Bosu
...,...,...,...,...,...
72265,1614548988923810,-18.768597,21.454185,-38.361181,moveforward backward on Bosu
72266,1614548988939786,5.951019,-54.657816,-27.496757,moveforward backward on Bosu
72267,1614548988955761,9.185931,-57.282368,-3.753719,moveforward backward on Bosu
72268,1614548988971737,-3.692683,28.412299,9.308003,moveforward backward on Bosu
72269,1614548988987712,-18.219272,82.551308,7.415885,moveforward backward on Bosu

In [29]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=50, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=51, second=53)
end_ts=int(end.timestamp() * 1e6)

DF23= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-29-f8f5768a03fe>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
76276,1614549053000541,1.373312,1.251240,-12.664988,Left leg Hip ups on Bosu
76277,1614549053016517,7.660029,81.818875,-13.336385,Left leg Hip ups on Bosu
76278,1614549053032492,-17.120623,65.949493,1.007095,Left leg Hip ups on Bosu
76279,1614549053048468,-39.154650,-16.388190,21.087968,Left leg Hip ups on Bosu
76280,1614549053064483,-24.628061,-57.343404,22.430762,Left leg Hip ups on Bosu
...,...,...,...,...,...
80027,1614549112922524,5.523766,47.943847,-4.425116,Left leg Hip ups on Bosu
80028,1614549112938499,-2.594034,37.750820,5.157549,Left leg Hip ups on Bosu
80029,1614549112954474,-13.336385,-9.857328,28.839551,Left leg Hip ups on Bosu
80030,1614549112970449,-5.096513,-40.192264,34.699016,Left leg Hip ups on Bosu
80031,1614549112986424,3.753719,-23.102159,16.937514,Left leg Hip ups on Bosu

In [30]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=52, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=53, second=5)
end_ts=int(end.timestamp() * 1e6)

DF24= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-30-07ea0f7e01a7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
80784,1614549125015314,1.861601,-5.767910,2.410925,right leg Hip ups on Bosu
80785,1614549125031288,1.678492,-6.622416,1.556420,right leg Hip ups on Bosu
80786,1614549125047263,0.762951,-8.697642,1.373312,right leg Hip ups on Bosu
80787,1614549125063237,1.007095,-10.284581,1.068132,right leg Hip ups on Bosu
80788,1614549125079212,2.655070,-10.467689,-0.091554,right leg Hip ups on Bosu
...,...,...,...,...,...
84534,1614549184921709,25.482567,-128.633555,-1.007095,right leg Hip ups on Bosu
84535,1614549184937684,23.285267,-139.314870,2.532998,right leg Hip ups on Bosu
84536,1614549184953659,25.360494,-144.625010,9.918364,right leg Hip ups on Bosu
84537,1614549184969634,20.416571,-149.629969,14.740215,right leg Hip ups on Bosu
84538,1614549184985609,11.444266,-160.128176,12.603952,right leg Hip ups on Bosu

In [31]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=54, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=55, second=20)
end_ts=int(end.timestamp() * 1e6)

DF25= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-31-f4f92cb05653>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
90987,1614549288009102,-29.449912,-9.185931,43.488212,V-Shift Swift on Bosu
90988,1614549288025077,-10.345617,9.491112,26.764324,V-Shift Swift on Bosu
90989,1614549288041052,4.791333,25.726711,13.214313,V-Shift Swift on Bosu
90990,1614549288057027,-25.970855,33.661402,7.354849,V-Shift Swift on Bosu
90991,1614549288073002,-21.271077,41.474022,16.083009,V-Shift Swift on Bosu
...,...,...,...,...,...
92985,1614549319927073,2.777142,-32.135500,-16.998550,V-Shift Swift on Bosu
92986,1614549319943048,-2.105745,3.936828,1.739528,V-Shift Swift on Bosu
92987,1614549319959023,-5.340658,30.243381,10.650797,V-Shift Swift on Bosu
92988,1614549319974998,-0.091554,13.824674,-4.303044,V-Shift Swift on Bosu
92989,1614549319990973,4.364080,-20.050355,-14.862287,V-Shift Swift on Bosu

In [32]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=56, second=42)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=57, second=12)
end_ts=int(end.timestamp() * 1e6)

DF26= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-32-77d880e23070>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
98123,1614549402008192,48.065919,26.520180,-19.501030,Freestyle Boxing
98124,1614549402024168,24.505989,24.139773,-9.613184,Freestyle Boxing
98125,1614549402040143,7.354849,19.195850,-2.166781,Freestyle Boxing
98126,1614549402056119,12.787060,19.867247,-2.655070,Freestyle Boxing
98127,1614549402072094,26.581216,16.266117,-10.711833,Freestyle Boxing
...,...,...,...,...,...
99996,1614549431930107,13.946746,21.637293,22.674907,Freestyle Boxing
99997,1614549431946082,5.889982,10.406653,32.379644,Freestyle Boxing
99998,1614549431962058,-3.387503,-2.410925,31.097887,Freestyle Boxing
99999,1614549431978033,-4.791333,1.190204,29.022660,Freestyle Boxing
100000,1614549431993988,1.007095,-1.129168,31.158923,Freestyle Boxing

In [33]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=57, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=58, second=15)
end_ts=int(end.timestamp() * 1e6)

DF27= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-33-9ca049cde5c9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
102067,1614549465014813,-3.326467,-14.190890,4.852369,Left_Right_Punches_flip
102068,1614549465030788,-55.756466,1.495384,16.083009,Left_Right_Punches_flip
102069,1614549465046764,-69.855802,1.068132,14.373999,Left_Right_Punches_flip
102070,1614549465062739,-97.505150,2.227817,11.993591,Left_Right_Punches_flip
102071,1614549465078714,-73.640040,8.941787,8.819715,Left_Right_Punches_flip
...,...,...,...,...,...
103939,1614549494920254,-73.395895,35.614557,59.357595,Left_Right_Punches_flip
103940,1614549494936218,-66.010529,39.276722,48.065919,Left_Right_Punches_flip
103941,1614549494952193,-125.520714,37.811856,55.390249,Left_Right_Punches_flip
103942,1614549494968168,-123.933776,37.872892,52.521553,Left_Right_Punches_flip
103943,1614549494984143,-69.184405,47.577630,37.750820,Left_Right_Punches_flip

In [34]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=58, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=59, second=0)
end_ts=int(end.timestamp() * 1e6)

DF28= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-34-ade80b987577>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
104883,1614549510000683,16.205081,33.478294,22.552834,left_Right_Punch
104884,1614549510016658,61.860075,33.234150,-10.650797,left_Right_Punch
104885,1614549510032633,41.657130,47.760739,-30.609598,left_Right_Punch
104886,1614549510048608,6.439307,47.943847,-6.866560,left_Right_Punch
104887,1614549510064583,-3.143359,36.713207,-2.227817,left_Right_Punch
...,...,...,...,...,...
106756,1614549539921707,15.228504,112.458991,40.253300,left_Right_Punch
106757,1614549539937682,16.021973,145.235370,38.910506,left_Right_Punch
106758,1614549539953657,5.951019,163.179980,19.195850,left_Right_Punch
106759,1614549539969632,-86.579690,139.497978,0.946059,left_Right_Punch
106760,1614549539985626,-116.975662,109.651331,-22.552834,left_Right_Punch

In [35]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=21, minute=59, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=0, second=10)
end_ts=int(end.timestamp() * 1e6)

DF29= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-35-72ed8cfc8945>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
109265,1614549580002513,23.407340,-25.299458,7.782101,one_twos
109266,1614549580018488,44.037537,-24.689097,9.491112,one_twos
109267,1614549580034463,56.305791,-40.558480,14.801251,one_twos
109268,1614549580050438,54.291600,-77.302205,6.683452,one_twos
109269,1614549580066413,40.924697,-121.248188,-12.298772,one_twos
...,...,...,...,...,...
111138,1614549609923292,-29.388876,135.225452,-63.813230,one_twos
111139,1614549609939267,56.916152,95.613031,-80.598154,one_twos
111140,1614549609955230,40.619516,32.501717,-94.209201,one_twos
111141,1614549609971205,21.759365,-19.134813,-136.812390,one_twos
111142,1614549609987180,165.011063,-53.253986,-238.925765,one_twos

In [36]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=0, second=18)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=0, second=48)
end_ts=int(end.timestamp() * 1e6)

DF30= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-36-c4cfda12eb5d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
111644,1614549618006496,37.079423,-29.571984,32.257572,hooks
111645,1614549618022471,76.447700,-31.525139,16.754406,hooks
111646,1614549618038446,88.654917,-15.411612,6.378271,hooks
111647,1614549618054421,114.900435,-7.415885,-8.453498,hooks
111648,1614549618070396,105.134661,-1.068132,-18.890669,hooks
...,...,...,...,...,...
113517,1614549647926993,59.601740,-181.002518,-45.746548,hooks
113518,1614549647942967,-1.007095,-140.718700,-26.642252,hooks
113519,1614549647958942,-67.048142,-179.293507,12.237736,hooks
113520,1614549647974914,-67.780575,-202.609293,22.125582,hooks
113521,1614549647990889,-28.473335,-180.758373,-4.730297,hooks

In [37]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=1, second=18)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=1, second=48)
end_ts=int(end.timestamp() * 1e6)

DF31= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-37-9a11398e6231>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
115400,1614549678007110,155.428397,-215.793088,8.148318,Upper_cuts
115401,1614549678023085,329.686427,-276.646067,-315.465019,Upper_cuts
115402,1614549678039059,-65.156023,241.977569,-485.755703,Upper_cuts
115403,1614549678055034,-34.821088,92.256046,-89.448386,Upper_cuts
115404,1614549678071008,-70.954452,-106.904707,53.009842,Upper_cuts
...,...,...,...,...,...
117273,1614549707927548,-116.426337,-86.945907,60.395209,Upper_cuts
117274,1614549707943522,-176.974136,-107.942321,41.474022,Upper_cuts
117275,1614549707959497,-179.903868,-112.214847,22.247654,Upper_cuts
117276,1614549707975471,-103.181506,-83.649958,17.181659,Upper_cuts
117277,1614549707991446,-12.420844,-58.625162,22.491798,Upper_cuts

In [38]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=2, second=7)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=2, second=37)
end_ts=int(end.timestamp() * 1e6)

DF32= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-38-4c9ad5278874>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
118467,1614549727001287,-60.334173,63.324941,26.520180,run
118468,1614549727017261,-23.651484,148.531319,-17.303731,run
118469,1614549727033236,42.694743,232.089723,-65.705348,run
118470,1614549727049210,28.656443,282.322423,-122.652018,run
118471,1614549727065185,-44.647898,309.483482,-174.227512,run
...,...,...,...,...,...
120340,1614549756921630,72.114137,415.136950,-232.455940,run
120341,1614549756937605,81.208515,400.793469,-193.453880,run
120342,1614549756953580,-1.556420,454.383154,-169.466697,run
120343,1614549756969554,34.637980,435.217823,-137.605859,run
120344,1614549756985529,85.725185,380.834668,-57.221332,run

In [39]:
start=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=2, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=2, day=28, hour=22, minute=3, second=24)
end_ts=int(end.timestamp() * 1e6)

DF33= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-39-7d2a4c8d2a1c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
121535,1614549776011041,-107.087816,-105.928130,91.096361,Punch_down_Up_Hooks
121536,1614549776027015,-63.569085,-71.808957,68.635080,Punch_down_Up_Hooks
121537,1614549776042990,118.684672,-76.142519,54.657816,Punch_down_Up_Hooks
121538,1614549776058964,161.837186,-102.510109,58.869306,Punch_down_Up_Hooks
121539,1614549776074939,-26.520180,-121.858549,82.612345,Punch_down_Up_Hooks
...,...,...,...,...,...
123283,1614549803934398,0.457771,-1.373312,-0.579843,Punch_down_Up_Hooks
123284,1614549803950372,0.457771,-1.373312,-0.518807,Punch_down_Up_Hooks
123285,1614549803966347,0.457771,-1.434348,-0.579843,Punch_down_Up_Hooks
123286,1614549803982321,0.457771,-1.373312,-0.579843,Punch_down_Up_Hooks
123287,1614549803998296,0.457771,-1.373312,-0.579843,Punch_down_Up_Hooks

In [40]:
sub02_final_leg_gyro=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub02_final_leg_gyro

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
0,1614546102005397,24.811170,-13.275349,7.476921,Forward and backward step
1,1614546102021373,23.285267,-17.975128,9.430076,Forward and backward step
2,1614546102037348,21.698329,-25.482567,11.627375,Forward and backward step
3,1614546102053324,27.801938,-36.774243,9.185931,Forward and backward step
4,1614546102069299,47.272450,-50.446326,8.880751,Forward and backward step
...,...,...,...,...,...
138243,1614549803934398,0.457771,-1.373312,-0.579843,Punch_down_Up_Hooks
138244,1614549803950372,0.457771,-1.373312,-0.518807,Punch_down_Up_Hooks
138245,1614549803966347,0.457771,-1.434348,-0.579843,Punch_down_Up_Hooks
138246,1614549803982321,0.457771,-1.373312,-0.579843,Punch_down_Up_Hooks
138247,1614549803998296,0.457771,-1.373312,-0.579843,Punch_down_Up_Hooks

In [41]:
sub02_final_leg_gyro.to_csv('final_cleaned_leg_gyro-sub02.csv-sub02')