In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('hand_gyro.csv-sub03')

In [3]:
df1

        Timestamp (microseconds)  Gyro X (°/s)  Gyro Y (°/s)  Gyro Z (°/s)
0               1614622325725341   -114.106966     77.180133     18.341344
1               1614622325741340   -107.881285     75.898375     11.871519
2               1614622325757338    -92.256046     65.156023      3.387503
3               1614622325773337    -79.377432     56.977188    -13.031205
4               1614622325789335   -102.449073     56.366827    -26.581216
...                          ...           ...           ...           ...
148515          1614624700911138      0.701915     -1.007095     -0.701915
148516          1614624700927131      0.762951     -0.946059     -0.701915
148517          1614624700943125      0.762951     -0.946059     -0.762951
148518          1614624700959118      0.762951     -1.068132     -0.701915
148519          1614624700975112      0.762951     -1.007095     -0.701915

[148520 rows x 4 columns]

In [4]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-01 18:12:05.725341')

In [5]:
start = pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=14, second=40)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=15, second=40)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-5-8b430a89cfb6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
9647,1614622480005655,79.194324,40.558480,-41.840238,Forward and backward step
9648,1614622480021648,41.962310,50.446326,-52.155337,Forward and backward step
9649,1614622480037641,-6.134127,59.052415,-61.310750,Forward and backward step
9650,1614622480053633,-48.249027,65.461204,-70.344091,Forward and backward step
9651,1614622480069626,-91.828794,67.780575,-74.677653,Forward and backward step
...,...,...,...,...,...
13394,1614622539929707,33.844511,272.312505,-45.502403,Forward and backward step
13395,1614622539945700,-35.797665,289.829862,-40.253300,Forward and backward step
13396,1614622539961692,-109.102007,294.224460,-10.772869,Forward and backward step
13397,1614622539977685,-135.530632,286.900130,7.965209,Forward and backward step
13398,1614622539993678,-118.196384,268.833448,13.519493,Forward and backward step

In [6]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=16, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=17, second=6)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-6-64e3e28cbbf9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
15025,1614622566013526,7.782101,185.946441,41.412985,Sideward step
15026,1614622566029519,23.285267,204.013123,47.150378,Sideward step
15027,1614622566045511,19.439994,225.131609,46.173800,Sideward step
15028,1614622566061504,-5.767910,255.893797,46.478981,Sideward step
15029,1614622566077497,-38.422217,292.271305,52.338445,Sideward step
...,...,...,...,...,...
18771,1614622625921524,63.874266,-89.936675,142.488746,Sideward step
18772,1614622625937517,59.113451,-61.860075,149.141680,Sideward step
18773,1614622625953509,42.572671,-28.046082,151.400015,Sideward step
18774,1614622625969502,7.598993,10.406653,147.615778,Sideward step
18775,1614622625985495,-34.027619,49.408713,138.521401,Sideward step

In [7]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=19, second=9)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=20, second=9)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-7-e5ebd074c4e9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
26467,1614622749000376,-17.914092,-7.049668,-14.740215,Pushups
26468,1614622749016368,-21.820401,-9.002823,-16.693370,Pushups
26469,1614622749032361,-10.101472,-11.139086,-15.899901,Pushups
26470,1614622749048354,-0.396735,-14.373999,-13.031205,Pushups
26471,1614622749064346,5.401694,-15.594720,-11.810483,Pushups
...,...,...,...,...,...
30214,1614622808924892,6.805524,2.655070,7.232776,Pushups
30215,1614622808940885,16.693370,2.471962,11.566339,Pushups
30216,1614622808956878,19.195850,0.823987,12.787060,Pushups
30217,1614622808972871,14.190890,0.213626,10.040436,Pushups
30218,1614622808988865,5.157549,-1.983673,2.716106,Pushups

In [8]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=22, second=23)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=23, second=23)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-8-b55a38eee79a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
38598,1614622943008365,88.838025,42.023346,-28.473335,Hip raise step with punches in the air
38599,1614622943024358,11.627375,50.995651,-27.130541,Hip raise step with punches in the air
38600,1614622943040344,-121.492332,49.042496,-16.937514,Hip raise step with punches in the air
38601,1614622943056337,-126.009003,52.704662,-4.913405,Hip raise step with punches in the air
38602,1614622943072330,-48.981460,54.169528,-3.570611,Hip raise step with punches in the air
...,...,...,...,...,...
42345,1614623002933450,-41.229877,25.482567,-5.889982,Hip raise step with punches in the air
42346,1614623002949443,-94.819562,35.248341,-15.350576,Hip raise step with punches in the air
42347,1614623002965437,-131.563287,37.933928,-13.580529,Hip raise step with punches in the air
42348,1614623002981430,-150.911727,32.318608,-11.505303,Hip raise step with punches in the air
42349,1614623002997423,-148.714427,13.336385,-16.144045,Hip raise step with punches in the air

In [9]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=25, second=26)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=26, second=26)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-9-1a09d863ae9a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
50041,1614623126014711,314.732586,-214.328222,74.738689,Front and back scooter
50042,1614623126030704,327.367056,-227.023728,108.735790,Front and back scooter
50043,1614623126046697,341.893645,-233.005264,137.972076,Front and back scooter
50044,1614623126062690,330.724041,-238.742657,164.705882,Front and back scooter
50045,1614623126078683,276.890211,-248.813611,178.316930,Front and back scooter
...,...,...,...,...,...
53787,1614623185924238,-4.119936,0.946059,-11.139086,Front and back scooter
53788,1614623185940231,1.861601,6.256199,-10.040436,Front and back scooter
53789,1614623185956224,3.448539,12.420844,-8.758679,Front and back scooter
53790,1614623185972217,0.091554,18.707561,-7.049668,Front and back scooter
53791,1614623185988210,-3.753719,24.322881,-3.570611,Front and back scooter

In [10]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=27, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=28, second=57)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-10-9e111bdf0e8f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
59482,1614623277004245,-48.126955,110.749981,29.388876,Belly Scooter
59483,1614623277020239,-32.379644,94.575418,32.867933,Belly Scooter
59484,1614623277036232,-17.730983,78.828107,34.393835,Belly Scooter
59485,1614623277052225,-1.373312,61.432822,29.510948,Belly Scooter
59486,1614623277068218,2.594034,42.938888,29.449912,Belly Scooter
...,...,...,...,...,...
63229,1614623336930284,15.960937,-22.308690,3.326467,Belly Scooter
63230,1614623336946277,20.050355,-19.806210,1.434348,Belly Scooter
63231,1614623336962270,27.252613,-15.045396,-2.105745,Belly Scooter
63232,1614623336978263,20.843824,-8.087282,-10.650797,Belly Scooter
63233,1614623336994257,-22.369726,-3.753719,-21.087968,Belly Scooter

In [11]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=28, second=58)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=29, second=58)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-11-a09fb26a9dfc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
63296,1614623338001831,-5.157549,-18.524453,-17.425803,Circular Scooter
63297,1614623338017824,-7.293812,-17.425803,-24.567025,Circular Scooter
63298,1614623338033817,-11.017014,-15.411612,-31.891356,Circular Scooter
63299,1614623338049810,-9.735256,-14.373999,-34.271763,Circular Scooter
63300,1614623338065826,-12.970169,-17.364767,-31.952392,Circular Scooter
...,...,...,...,...,...
67043,1614623397927770,-17.425803,18.585489,-16.205081,Circular Scooter
67044,1614623397943763,1.068132,10.101472,-20.477607,Circular Scooter
67045,1614623397959756,29.388876,4.486152,-19.501030,Circular Scooter
67046,1614623397975750,25.604639,6.927596,-13.702602,Circular Scooter
67047,1614623397991743,1.007095,15.838865,-10.406653,Circular Scooter

In [12]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=31, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=32, second=5)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-12-0ac04b7feb76>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
71237,1614623465002473,-33.417258,-3.509575,15.838865,Cycling Slow
71238,1614623465018467,-26.215000,-13.641566,13.214313,Cycling Slow
71239,1614623465034460,-20.050355,-18.890669,11.810483,Cycling Slow
71240,1614623465050445,-16.449226,-18.036164,14.373999,Cycling Slow
71241,1614623465066438,-10.833906,-18.524453,18.097200,Cycling Slow
...,...,...,...,...,...
74984,1614623524928321,12.664988,-7.232776,10.467689,Cycling Slow
74985,1614623524944315,15.899901,-0.885023,8.209354,Cycling Slow
74986,1614623524960308,20.233463,5.462730,4.180972,Cycling Slow
74987,1614623524976301,20.599680,11.932555,-0.762951,Cycling Slow
74988,1614623524992294,11.566339,19.134813,-4.425116,Cycling Slow

In [13]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=32, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=33, second=6)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-13-0b8f3aadaaa0>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
75052,1614623526015861,-12.420844,29.938201,43.793393,Cycling Fast
75053,1614623526031854,-15.106432,28.595407,43.915465,Cycling Fast
75054,1614623526047847,-12.603952,26.276036,44.769970,Cycling Fast
75055,1614623526063840,-4.486152,22.919051,43.060960,Cycling Fast
75056,1614623526079834,0.701915,19.195850,39.215686,Cycling Fast
...,...,...,...,...,...
78798,1614623585925205,70.893416,118.989853,14.373999,Cycling Fast
78799,1614623585941198,88.838025,100.434882,16.266117,Cycling Fast
78800,1614623585957183,75.349050,77.424277,6.134127,Cycling Fast
78801,1614623585973177,44.953079,42.816815,-9.979400,Cycling Fast
78802,1614623585989170,28.595407,10.711833,-20.111391,Cycling Fast

In [14]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=36, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=37, second=46)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-14-1b9c9b4cf6bb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
92559,1614623806002966,-76.203555,29.633021,14.801251,Medicine_ball
92560,1614623806018951,-69.184405,53.070878,18.829633,Medicine_ball
92561,1614623806034944,-49.591821,81.208515,21.637293,Medicine_ball
92562,1614623806050937,-30.975814,120.943008,15.533684,Medicine_ball
92563,1614623806066930,-36.408026,157.930877,3.997864,Medicine_ball
...,...,...,...,...,...
96306,1614623865927715,-119.050889,67.902647,-140.047303,Medicine_ball
96307,1614623865943708,220.431830,49.530785,66.803998,Medicine_ball
96308,1614623865959701,0.823987,-78.034638,171.663996,Medicine_ball
96309,1614623865975694,14.190890,-77.851530,54.840925,Medicine_ball
96310,1614623865991687,39.765011,-42.816815,-37.872892,Medicine_ball

In [15]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=37, second=47)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=18, minute=38, second=48)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-15-ba8de3496157>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
96374,1614623867015224,-33.356222,159.578851,-24.017700,Medicine ball with burpies
96375,1614623867031217,-66.254673,128.145266,-20.843824,Medicine ball with burpies
96376,1614623867047210,-90.363928,100.617990,7.171740,Medicine ball with burpies
96377,1614623867063203,-37.811856,75.165942,29.022660,Medicine ball with burpies
96378,1614623867079197,56.366827,59.479667,19.928283,Medicine ball with burpies
...,...,...,...,...,...
100183,1614623927931310,67.109178,-209.201190,-73.579004,Medicine ball with burpies
100184,1614623927947303,117.402914,-222.079805,-92.011902,Medicine ball with burpies
100185,1614623927963297,175.936522,-257.969024,-101.106279,Medicine ball with burpies
100186,1614623927979290,105.256733,-311.558709,-72.602426,Medicine ball with burpies
100187,1614623927995283,0.152590,-326.146334,-44.586862,Medicine ball with burpies

In [16]:
df2=pd.read_csv('hand_gyro.csv-sub03-folder02')

In [17]:
df2

        Timestamp (microseconds)  Gyro X (°/s)  Gyro Y (°/s)  Gyro Z (°/s)
0               1614625149138763     29.266804   -344.457160   -140.596628
1               1614625149154761     43.060960   -359.472038   -165.865568
2               1614625149170760     86.701762   -382.055390   -179.659724
3               1614625149186758    135.957885   -402.136263   -187.228199
4               1614625149202757    141.939422   -410.376135   -199.801633
...                          ...           ...           ...           ...
182815          1614628072881516    -16.144045     -8.758679      5.035477
182816          1614628072897506    -17.669947     -7.598993     13.031205
182817          1614628072913497     -8.331426     -1.922637     19.012741
182818          1614628072929487    -18.402380     -4.180972     20.111391
182819          1614628072945477    -16.388190      3.387503     19.989319

[182820 rows x 4 columns]

In [18]:
pd.Timestamp(df2['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-01 18:59:09.138763')

In [19]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=0, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=1, second=51)
end_ts=int(end.timestamp() * 1e6)

DF12= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-19-cedc23365675>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
6370,1614625251015710,-151.033799,112.397955,85.603113,punch ball
6371,1614625251031703,-157.259480,112.458991,75.532158,punch ball
6372,1614625251047697,-151.155871,114.290074,62.775616,punch ball
6373,1614625251063690,-148.592355,113.435569,48.493172,punch ball
6374,1614625251079684,-133.211261,110.566873,33.905547,punch ball
...,...,...,...,...,...
10116,1614625310926216,157.564660,-84.077211,342.687114,punch ball
10117,1614625310942209,173.617151,-102.021820,333.897917,punch ball
10118,1614625310958203,220.248722,-133.394369,299.168383,punch ball
10119,1614625310974197,300.022889,-169.466697,220.187686,punch ball
10120,1614625310990203,380.529488,-210.971237,71.625849,punch ball

In [20]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=2, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=3, second=40)
end_ts=int(end.timestamp() * 1e6)

DF13= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-20-42ae15fc3d48>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
13185,1614625360009441,10.589761,43.610285,2.349889,Squarts Toe ups
13186,1614625360025435,19.501030,38.971542,3.875792,Squarts Toe ups
13187,1614625360041429,16.815442,31.219959,12.787060,Squarts Toe ups
13188,1614625360057422,-1.861601,20.538643,17.486839,Squarts Toe ups
13189,1614625360073416,0.457771,16.327153,16.754406,Squarts Toe ups
...,...,...,...,...,...
16931,1614625419920711,13.336385,-19.501030,-8.453498,Squarts Toe ups
16932,1614625419936704,20.965896,-20.172427,-16.754406,Squarts Toe ups
16933,1614625419952698,16.754406,-17.364767,-23.407340,Squarts Toe ups
16934,1614625419968691,7.843137,-13.214313,-23.651484,Squarts Toe ups
16935,1614625419984685,4.058900,-11.749447,-18.951705,Squarts Toe ups

In [21]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=5, second=10)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=6, second=10)
end_ts=int(end.timestamp() * 1e6)

DF14= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-21-05f6b27f8ab2>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
22564,1614625510012216,-34.149691,51.606012,-16.876478,Weight lifts
22565,1614625510028210,-32.074464,52.521553,-16.876478,Weight lifts
22566,1614625510044203,-17.975128,50.080110,-14.984360,Weight lifts
22567,1614625510060197,-5.035477,45.563439,-13.214313,Weight lifts
22568,1614625510076191,1.800565,39.826047,-13.397421,Weight lifts
...,...,...,...,...,...
26310,1614625569924279,7.476921,204.074159,9.857328,Weight lifts
26311,1614625569940272,9.674220,198.153658,9.735256,Weight lifts
26312,1614625569956266,36.774243,193.270771,1.251240,Weight lifts
26313,1614625569972260,57.343404,188.815137,-7.537957,Weight lifts
26314,1614625569988253,59.113451,178.011749,-8.331426,Weight lifts

In [22]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=7, second=21)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=8, second=21)
end_ts=int(end.timestamp() * 1e6)

DF15= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-22-59c110aae176>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
30755,1614625641015782,-38.727398,88.838025,135.652705,Heavy Weight lifts
30756,1614625641031776,-39.703975,88.838025,121.492332,Heavy Weight lifts
30757,1614625641047770,-43.183032,83.405814,104.036011,Heavy Weight lifts
30758,1614625641063763,-35.980774,77.912566,88.105592,Heavy Weight lifts
30759,1614625641079757,-25.238422,73.517967,83.344778,Heavy Weight lifts
...,...,...,...,...,...
34501,1614625700928042,14.373999,-14.496071,6.744488,Heavy Weight lifts
34502,1614625700944036,1.495384,-6.683452,9.979400,Heavy Weight lifts
34503,1614625700960030,-18.585489,3.326467,14.007782,Heavy Weight lifts
34504,1614625700976024,-23.468376,9.185931,19.012741,Heavy Weight lifts
34505,1614625700992018,-12.909133,12.542916,25.543603,Heavy Weight lifts

In [23]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=9, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=10, second=45)
end_ts=int(end.timestamp() * 1e6)

DF16= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-23-5fc004af0bcf>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
39758,1614625785006543,-9.185931,-151.827268,-65.278096,Forward Lunges on Bosu
39759,1614625785022536,-7.843137,-155.367361,-67.109178,Forward Lunges on Bosu
39760,1614625785038574,-10.711833,-157.564660,-68.268864,Forward Lunges on Bosu
39761,1614625785054568,-16.449226,-158.968490,-68.879225,Forward Lunges on Bosu
39762,1614625785070562,-15.899901,-159.090562,-68.207828,Forward Lunges on Bosu
...,...,...,...,...,...
43505,1614625844934307,-47.882811,-2.532998,-31.342031,Forward Lunges on Bosu
43506,1614625844950301,-34.027619,10.528725,-24.017700,Forward Lunges on Bosu
43507,1614625844966294,-12.726024,19.867247,-16.632334,Forward Lunges on Bosu
43508,1614625844982288,4.852369,26.337072,-8.941787,Forward Lunges on Bosu
43509,1614625844998282,13.336385,30.975814,-2.471962,Forward Lunges on Bosu

In [24]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=11, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=12, second=51)
end_ts=int(end.timestamp() * 1e6)

DF17= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-24-3272f14d181b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
47636,1614625911002845,-17.547875,-49.225605,17.792020,Split squart left on Bosu
47637,1614625911018839,-20.233463,-47.882811,20.477607,Split squart left on Bosu
47638,1614625911034833,-19.623102,-45.380331,21.759365,Split squart left on Bosu
47639,1614625911050826,-15.838865,-42.511635,20.843824,Split squart left on Bosu
47640,1614625911066803,-11.688411,-39.887083,18.829633,Split squart left on Bosu
...,...,...,...,...,...
51383,1614625970929786,-10.406653,102.693217,16.876478,Split squart left on Bosu
51384,1614625970945779,-11.383230,103.364614,17.364767,Split squart left on Bosu
51385,1614625970961773,-14.923323,102.388037,18.158236,Split squart left on Bosu
51386,1614625970977767,-14.557107,100.129702,18.036164,Split squart left on Bosu
51387,1614625970993760,-12.420844,97.261006,16.388190,Split squart left on Bosu

In [25]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=12, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=13, second=57)
end_ts=int(end.timestamp() * 1e6)

DF18= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-25-14524529af3b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
51763,1614625977007239,22.125582,0.946059,7.476921,Split squart right on Bosu
51764,1614625977023233,18.036164,-3.265431,6.439307,Split squart right on Bosu
51765,1614625977039227,13.275349,-7.537957,6.439307,Split squart right on Bosu
51766,1614625977055220,10.101472,-12.115663,6.378271,Split squart right on Bosu
51767,1614625977071214,8.209354,-16.571298,5.035477,Split squart right on Bosu
...,...,...,...,...,...
55510,1614626036934075,-47.333486,26.703288,2.777142,Split squart right on Bosu
55511,1614626036950069,-46.967269,27.130541,-1.434348,Split squart right on Bosu
55512,1614626036966062,-40.436408,26.642252,-6.012055,Split squart right on Bosu
55513,1614626036982056,-30.182345,25.726711,-10.406653,Split squart right on Bosu
55514,1614626036998049,-25.543603,25.116350,-14.435035,Split squart right on Bosu

In [26]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=14, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=15, second=45)
end_ts=int(end.timestamp() * 1e6)

DF19= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-26-2ab3e1100cc5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
58516,1614626085009651,54.718853,-45.441367,-1.251240,plank pie on Bosu
58517,1614626085025644,9.735256,-42.450599,-2.777142,plank pie on Bosu
58518,1614626085041638,-13.946746,-42.267491,-6.073091,plank pie on Bosu
58519,1614626085057632,-13.214313,-48.310063,-14.129854,plank pie on Bosu
58520,1614626085073639,-2.227817,-53.315023,-24.750134,plank pie on Bosu
...,...,...,...,...,...
62262,1614626144920109,-2.227817,32.379644,-4.364080,plank pie on Bosu
62263,1614626144936103,28.107118,24.872206,-3.997864,plank pie on Bosu
62264,1614626144952097,34.576944,17.547875,4.058900,plank pie on Bosu
62265,1614626144968090,25.787747,24.689097,3.753719,plank pie on Bosu
62266,1614626144984084,9.491112,36.652171,-0.579843,plank pie on Bosu

In [27]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=19, second=12)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=20, second=12)
end_ts=int(end.timestamp() * 1e6)

DF20= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-27-884dc8445d69>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
75211,1614626352001764,-3.997864,1.373312,-1.617456,plank top on Bosu
75212,1614626352017755,-2.532998,-0.946059,-0.885023,plank top on Bosu
75213,1614626352033746,1.007095,-3.082322,-0.274662,plank top on Bosu
75214,1614626352049737,4.425116,-4.425116,-0.457771,plank top on Bosu
75215,1614626352065727,10.406653,-4.425116,0.030518,plank top on Bosu
...,...,...,...,...,...
78958,1614626411922990,2.838178,-4.119936,8.270390,plank top on Bosu
78959,1614626411938983,0.396735,-0.946059,10.345617,plank top on Bosu
78960,1614626411954986,-3.509575,8.026246,13.031205,plank top on Bosu
78961,1614626411970978,-8.941787,12.298772,15.960937,plank top on Bosu
78962,1614626411986971,-20.233463,11.078050,17.181659,plank top on Bosu

In [28]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=22, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=23, second=14)
end_ts=int(end.timestamp() * 1e6)

DF21= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-28-492fa303cdda>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
86592,1614626534010063,50.507362,9.430076,-7.537957,dips on Bosu
86593,1614626534026056,47.699702,11.505303,-3.936828,dips on Bosu
86594,1614626534042049,50.019074,18.219272,2.288853,dips on Bosu
86595,1614626534058042,63.813230,25.970855,1.068132,dips on Bosu
86596,1614626534074035,27.618830,21.210040,-2.410925,dips on Bosu
...,...,...,...,...,...
90339,1614626593935644,-2.471962,-4.364080,3.082322,dips on Bosu
90340,1614626593951629,-0.823987,-4.364080,4.119936,dips on Bosu
90341,1614626593967622,5.828946,-2.105745,3.875792,dips on Bosu
90342,1614626593983616,12.787060,0.091554,4.119936,dips on Bosu
90343,1614626593999609,16.388190,0.885023,4.608225,dips on Bosu

In [29]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=24, second=24)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=25, second=24)
end_ts=int(end.timestamp() * 1e6)

DF22= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-29-a9cc1792e7bd>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
94720,1614626664001434,-21.026932,8.880751,-20.050355,moveforward backward on Bosu
94721,1614626664017427,-21.881437,8.026246,-18.402380,moveforward backward on Bosu
94722,1614626664033420,-26.031891,5.889982,-16.388190,moveforward backward on Bosu
94723,1614626664049413,-23.651484,4.364080,-16.266117,moveforward backward on Bosu
94724,1614626664065406,-17.608911,3.021286,-17.730983,moveforward backward on Bosu
...,...,...,...,...,...
98467,1614626723927812,-31.403067,2.594034,-11.200122,moveforward backward on Bosu
98468,1614626723943805,-30.060273,3.204395,-11.200122,moveforward backward on Bosu
98469,1614626723959799,-29.571984,3.753719,-11.749447,moveforward backward on Bosu
98470,1614626723975793,-26.764324,4.608225,-13.214313,moveforward backward on Bosu
98471,1614626723991786,-26.215000,5.828946,-14.984360,moveforward backward on Bosu

In [30]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=26, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=27, second=30)
end_ts=int(end.timestamp() * 1e6)

DF23= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-30-e8db329940eb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
102599,1614626790011886,8.087282,-0.030518,-0.518807,Left leg Hip ups on Bosu
102600,1614626790027893,5.279622,-0.396735,-0.518807,Left leg Hip ups on Bosu
102601,1614626790043886,1.434348,-0.946059,-0.579843,Left leg Hip ups on Bosu
102602,1614626790059880,-0.091554,-1.251240,-0.457771,Left leg Hip ups on Bosu
102603,1614626790075873,0.701915,-1.129168,-0.518807,Left leg Hip ups on Bosu
...,...,...,...,...,...
106345,1614626849921243,1.373312,-1.068132,-0.396735,Left leg Hip ups on Bosu
106346,1614626849937236,1.190204,-1.007095,-0.518807,Left leg Hip ups on Bosu
106347,1614626849953230,0.946059,-0.946059,-0.701915,Left leg Hip ups on Bosu
106348,1614626849969223,1.068132,-1.068132,-0.640879,Left leg Hip ups on Bosu
106349,1614626849985216,1.190204,-1.068132,-0.701915,Left leg Hip ups on Bosu

In [31]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=27, second=31)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=28, second=31)
end_ts=int(end.timestamp() * 1e6)

DF24= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-31-5846fc2475d7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
106413,1614626851008722,1.922637,-1.251240,-0.946059,right leg Hip ups on Bosu
106414,1614626851024715,2.410925,-1.373312,-1.007095,right leg Hip ups on Bosu
106415,1614626851040708,3.509575,-1.556420,-1.068132,right leg Hip ups on Bosu
106416,1614626851056701,3.265431,-1.373312,-0.946059,right leg Hip ups on Bosu
106417,1614626851072694,7.415885,-1.312276,-0.030518,right leg Hip ups on Bosu
...,...,...,...,...,...
110160,1614626910932953,1.251240,142.671855,-17.669947,right leg Hip ups on Bosu
110161,1614626910948945,-4.547189,123.750668,-28.717479,right leg Hip ups on Bosu
110162,1614626910964938,-14.679179,107.087816,-37.628748,right leg Hip ups on Bosu
110163,1614626910980930,-28.717479,87.495232,-46.906233,right leg Hip ups on Bosu
110164,1614626910996923,-34.088655,65.033951,-58.564126,right leg Hip ups on Bosu

In [32]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=29, second=15)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=30, second=13)
end_ts=int(end.timestamp() * 1e6)

DF25= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-32-48af10944a48>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
112916,1614626955008819,-142.183566,-115.510796,-92.500191,V-Shift Swift on Bosu
112917,1614626955024812,-113.313497,-123.018235,-76.752880,V-Shift Swift on Bosu
112918,1614626955040805,-65.033951,-99.092088,-85.297932,V-Shift Swift on Bosu
112919,1614626955056799,-22.430762,-76.813916,-83.161669,V-Shift Swift on Bosu
112920,1614626955072784,13.397421,-74.250401,-72.968643,V-Shift Swift on Bosu
...,...,...,...,...,...
116538,1614627012935245,1.129168,-1.983673,-1.617456,V-Shift Swift on Bosu
116539,1614627012951238,1.556420,-1.007095,-1.983673,V-Shift Swift on Bosu
116540,1614627012967224,-1.922637,-1.983673,-2.227817,V-Shift Swift on Bosu
116541,1614627012983217,-5.584802,-5.645838,-2.044709,V-Shift Swift on Bosu
116542,1614627012999210,-5.157549,-9.002823,-1.434348,V-Shift Swift on Bosu

In [33]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=32, second=50)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=33, second=20)
end_ts=int(end.timestamp() * 1e6)

DF26= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-33-82278fe99667>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
126359,1614627170004125,-46.784161,-165.194171,-50.385290,Freestyle Boxing
126360,1614627170020111,13.275349,-143.770504,-42.816815,Freestyle Boxing
126361,1614627170036104,58.197910,-111.482414,-31.586175,Freestyle Boxing
126362,1614627170052097,20.233463,-106.660563,-28.534371,Freestyle Boxing
126363,1614627170068090,-61.310750,-120.271611,-27.191577,Freestyle Boxing
...,...,...,...,...,...
128230,1614627199926990,-24.444953,-52.338445,100.129702,Freestyle Boxing
128231,1614627199942983,-24.505989,-52.033265,111.726558,Freestyle Boxing
128232,1614627199958976,-30.487526,-52.826734,122.896162,Freestyle Boxing
128233,1614627199974969,-37.628748,-55.146105,133.760586,Freestyle Boxing
128234,1614627199990963,-41.474022,-59.296559,145.052262,Freestyle Boxing

In [34]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=33, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=33, second=55)
end_ts=int(end.timestamp() * 1e6)

DF27= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-34-7ec7962534a8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
129173,1614627215008234,-18.646525,-20.660716,-16.021973,Left_Right_Punches_flip
129174,1614627215024227,-19.928283,-23.712520,-6.073091,Left_Right_Punches_flip
129175,1614627215040220,-18.402380,-24.567025,0.701915,Left_Right_Punches_flip
129176,1614627215056213,-13.275349,-21.393149,3.936828,Left_Right_Punches_flip
129177,1614627215072206,-22.980087,-17.730983,1.617456,Left_Right_Punches_flip
...,...,...,...,...,...
130419,1614627234935339,-98.786908,-8.026246,-100.923171,Left_Right_Punches_flip
130420,1614627234951324,29.327840,4.791333,-81.574731,Left_Right_Punches_flip
130421,1614627234967317,52.460517,-20.965896,-27.557794,Left_Right_Punches_flip
130422,1614627234983310,18.341344,-36.163882,-6.256199,Left_Right_Punches_flip
130423,1614627234999303,-21.149004,-35.919738,-23.590448,Left_Right_Punches_flip

In [35]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=37, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=38, second=5)
end_ts=int(end.timestamp() * 1e6)

DF28= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-35-941e99927124>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
144180,1614627455013488,-173.067826,130.403601,-15.838865,left_Right_Punch
144181,1614627455029482,-170.504311,137.483787,-16.510262,left_Right_Punch
144182,1614627455045475,-157.076371,152.010376,-12.176699,left_Right_Punch
144183,1614627455061468,-127.351797,169.161517,-2.410925,left_Right_Punch
144184,1614627455077461,-102.143893,169.161517,12.298772,left_Right_Punch
...,...,...,...,...,...
146050,1614627484920276,-14.435035,8.026246,5.645838,left_Right_Punch
146051,1614627484936269,7.476921,14.679179,25.421530,left_Right_Punch
146052,1614627484952263,20.172427,12.726024,29.877165,left_Right_Punch
146053,1614627484968256,-6.622416,-3.631647,13.702602,left_Right_Punch
146054,1614627484984249,-32.990005,-19.867247,5.706874,left_Right_Punch

In [36]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=38, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=39, second=6)
end_ts=int(end.timestamp() * 1e6)

DF29= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-36-3dc3ac3eb8a5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
148056,1614627517002044,-146.272984,128.816663,12.909133,one_twos
148057,1614627517018037,-110.505837,155.245289,19.195850,one_twos
148058,1614627517034031,-55.085069,181.490806,16.998550,one_twos
148059,1614627517050024,-34.821088,194.430457,15.533684,one_twos
148060,1614627517066009,-49.103532,195.956359,16.388190,one_twos
...,...,...,...,...,...
149865,1614627545933206,-27.313649,14.862287,-48.981460,one_twos
149866,1614627545949199,-20.294499,9.430076,-47.638666,one_twos
149867,1614627545965192,-15.838865,4.119936,-43.366140,one_twos
149868,1614627545981186,-13.214313,0.335698,-45.197223,one_twos
149869,1614627545997179,-21.087968,-1.983673,-48.493172,one_twos

In [37]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=39, second=19)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=39, second=49)
end_ts=int(end.timestamp() * 1e6)

DF30= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-37-075f6d0c4ad7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
150683,1614627559015356,179.964904,-143.770504,22.796979,hooks
150684,1614627559031349,180.331121,-112.886244,25.787747,hooks
150685,1614627559047342,167.757687,-97.749294,28.839551,hooks
150686,1614627559063335,151.094835,-90.547036,37.628748,hooks
150687,1614627559079328,108.308537,-85.786221,45.136187,hooks
...,...,...,...,...,...
152553,1614627588921808,38.422217,23.956664,165.255207,hooks
152554,1614627588937801,75.471122,17.914092,186.373693,hooks
152555,1614627588953794,106.721599,19.012741,202.121004,hooks
152556,1614627588969787,175.631342,29.816129,212.680247,hooks
152557,1614627588985780,268.406195,34.699016,213.778897,hooks

In [38]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=41, second=20)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=41, second=50)
end_ts=int(end.timestamp() * 1e6)

DF31= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-38-82629abdddcb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
158249,1614627680015977,-42.511635,-33.051041,-36.652171,Upper_cuts
158250,1614627680031971,-81.086442,-71.503777,-49.713893,Upper_cuts
158251,1614627680047964,-74.006256,-102.571145,-59.601740,Upper_cuts
158252,1614627680063957,-41.107805,-126.375219,-64.057374,Upper_cuts
158253,1614627680079950,-11.566339,-144.747082,-64.789807,Upper_cuts
...,...,...,...,...,...
160119,1614627709922237,-24.505989,-56.488899,-47.760739,Upper_cuts
160120,1614627709938263,-9.857328,-55.512322,-38.422217,Upper_cuts
160121,1614627709954256,38.361181,-72.724498,-57.709621,Upper_cuts
160122,1614627709970249,51.972229,-98.176547,-69.489586,Upper_cuts
160123,1614627709986242,27.435721,-107.698177,-64.850843,Upper_cuts

In [39]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=43, second=25)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=44, second=5)
end_ts=int(end.timestamp() * 1e6)

DF32= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-39-5360007f70e6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
166065,1614627805015085,-70.466163,-244.419013,36.346990,run
166066,1614627805031078,-71.320668,-272.007324,59.296559,run
166067,1614627805047071,-115.022507,-332.127871,69.001297,run
166068,1614627805063064,-73.640040,-356.237125,64.057374,run
166069,1614627805079057,149.996185,-311.131456,66.498817,run
...,...,...,...,...,...
168561,1614627844932557,-488.563363,245.639734,-78.400855,run
168562,1614627844948550,-372.655833,289.829862,-48.493172,run
168563,1614627844964542,-362.218662,318.028534,-55.329213,run
168564,1614627844980535,-326.573587,293.614099,-37.018387,run
168565,1614627844996528,-312.413214,290.440223,-7.415885,run

In [40]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=45, second=40)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=19, minute=46, second=10)
end_ts=int(end.timestamp() * 1e6)

DF33= df2.loc[(df2['Timestamp (microseconds)'] >=start_ts) & (df2['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-40-259a10fd93ee>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
174506,1614627940007638,49.042496,270.420386,220.737011,Punch_down_Up_Hooks
174507,1614627940023630,48.249027,330.907149,243.259327,Punch_down_Up_Hooks
174508,1614627940039623,24.567025,368.749523,264.377813,Punch_down_Up_Hooks
174509,1614627940055616,20.477607,400.549325,299.168383,Punch_down_Up_Hooks
174510,1614627940071608,46.845197,428.931106,326.695659,Punch_down_Up_Hooks
...,...,...,...,...,...
176377,1614627969929834,0.701915,-1.007095,-0.640879,Punch_down_Up_Hooks
176378,1614627969945826,0.762951,-1.007095,-0.701915,Punch_down_Up_Hooks
176379,1614627969961819,0.701915,-1.007095,-0.701915,Punch_down_Up_Hooks
176380,1614627969977813,0.701915,-1.007095,-0.701915,Punch_down_Up_Hooks
176381,1614627969993806,0.701915,-1.007095,-0.701915,Punch_down_Up_Hooks

In [41]:
sub03_final_hand_gyro=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub03_final_hand_gyro

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
0,1614622480005655,79.194324,40.558480,-41.840238,Forward and backward step
1,1614622480021648,41.962310,50.446326,-52.155337,Forward and backward step
2,1614622480037641,-6.134127,59.052415,-61.310750,Forward and backward step
3,1614622480053633,-48.249027,65.461204,-70.344091,Forward and backward step
4,1614622480069626,-91.828794,67.780575,-74.677653,Forward and backward step
...,...,...,...,...,...
108666,1614627969929834,0.701915,-1.007095,-0.640879,Punch_down_Up_Hooks
108667,1614627969945826,0.762951,-1.007095,-0.701915,Punch_down_Up_Hooks
108668,1614627969961819,0.701915,-1.007095,-0.701915,Punch_down_Up_Hooks
108669,1614627969977813,0.701915,-1.007095,-0.701915,Punch_down_Up_Hooks
108670,1614627969993806,0.701915,-1.007095,-0.701915,Punch_down_Up_Hooks

In [43]:
sub03_final_hand_gyro.to_csv('final_cleaned_hand_gyro-sub03.csv-sub03')