In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('/Users/shreyasaswar/HARDataset/EXTRACTION/SUB 08/Chest/accel.csv')

In [3]:
df1

        Timestamp (microseconds)  Accel X (g)  Accel Y (g)  Accel Z (g)
0               1614726899074127    -0.104433     0.998123     0.245670
1               1614726899106112    -0.098573     1.011795     0.232975
2               1614726899138096    -0.063416     1.009842     0.264225
3               1614726899170081    -0.068788     1.012772     0.285222
4               1614726899202066    -0.080995     1.008865     0.214908
...                          ...          ...          ...          ...
116394          1614730615002637     0.003967     0.581613     0.827710
116395          1614730615034816     0.011292     0.586007     0.826246
116396          1614730615066996     0.005921     0.584054     0.836011
116397          1614730615099176     0.008362     0.580636     0.822827
116398          1614730615131356     0.017151     0.585519     0.826246

[116399 rows x 4 columns]

In [4]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-02 23:14:59.059326')

In [5]:
start = pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=15, second=44)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=16, second=44)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-5-4956bfeff194>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

       Timestamp (microseconds)  Sample (V)             Activity_Label
11213          1614726944003392    0.001991  Forward and backward step
11214          1614726944007400    0.002003  Forward and backward step
11215          1614726944011408    0.001997  Forward and backward step
11216          1614726944015417    0.001985  Forward and backward step
11217          1614726944019425    0.001985  Forward and backward step
...                         ...         ...                        ...
26176          1614727003981367    0.002434  Forward and backward step
26177          1614727003985376    0.002416  Forward and backward step
26178          1614727003989384    0.002409  Forward and backward step
26179          1614727003993393    0.002409  Forward and backward step
26180          1614727003997402    0.002403  Forward and backward step

[14968 rows x 3 columns]

In [6]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=17, second=10)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=18, second=10)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-6-09e0aaf923ef>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

       Timestamp (microseconds)  Sample (V) Activity_Label
32667          1614727030000806    0.002169  Sideward step
32668          1614727030004815    0.002169  Sideward step
32669          1614727030008823    0.002169  Sideward step
32670          1614727030012832    0.002188  Sideward step
32671          1614727030016841    0.002200  Sideward step
...                         ...         ...            ...
47630          1614727089981017    0.001665  Sideward step
47631          1614727089985026    0.001652  Sideward step
47632          1614727089989034    0.001646  Sideward step
47633          1614727089993043    0.001640  Sideward step
47634          1614727089997052    0.001677  Sideward step

[14968 rows x 3 columns]

In [7]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=18, second=41)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=19, second=41)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-7-627d81f73f0e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

       Timestamp (microseconds)  Sample (V) Activity_Label
55369          1614727121003327    0.002317        Pushups
55370          1614727121007335    0.002237        Pushups
55371          1614727121011344    0.002219        Pushups
55372          1614727121015353    0.002237        Pushups
55373          1614727121019362    0.002243        Pushups
...                         ...         ...            ...
70331          1614727180980291    0.002102        Pushups
70332          1614727180984300    0.002046        Pushups
70333          1614727180988309    0.001720        Pushups
70334          1614727180992318    0.001603        Pushups
70335          1614727180996327    0.001880        Pushups

[14967 rows x 3 columns]

In [8]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=20, second=34)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=21, second=40)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-8-41405f570efc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Sample (V),Activity_Label
83558,1614727234002884,0.003456,Hip raise step with punches in the air
83559,1614727234006893,0.003554,Hip raise step with punches in the air
83560,1614727234010902,0.003610,Hip raise step with punches in the air
83561,1614727234014911,0.003585,Hip raise step with punches in the air
83562,1614727234018920,0.003536,Hip raise step with punches in the air
...,...,...,...
100017,1614727299981249,0.001893,Hip raise step with punches in the air
100018,1614727299985258,0.001899,Hip raise step with punches in the air
100019,1614727299989266,0.001905,Hip raise step with punches in the air
100020,1614727299993275,0.001905,Hip raise step with punches in the air
100021,1614727299997284,0.001862,Hip raise step with punches in the air

In [9]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=23, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=24, second=46)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-9-cd1b68069753>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

        Timestamp (microseconds)  Sample (V)          Activity_Label
131455          1614727426002957    0.001579  Front and back scooter
131456          1614727426006966    0.001579  Front and back scooter
131457          1614727426010975    0.001536  Front and back scooter
131458          1614727426014984    0.001505  Front and back scooter
131459          1614727426018993    0.001542  Front and back scooter
...                          ...         ...                     ...
146418          1614727485983321    0.002102  Front and back scooter
146419          1614727485987330    0.002089  Front and back scooter
146420          1614727485991338    0.002089  Front and back scooter
146421          1614727485995347    0.002083  Front and back scooter
146422          1614727485999356    0.002077  Front and back scooter

[14968 rows x 3 columns]

In [10]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=25, second=28)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=26, second=28)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-10-19a768872a8f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

        Timestamp (microseconds)  Sample (V) Activity_Label
156900          1614727528001522    0.002114  Belly Scooter
156901          1614727528005530    0.002126  Belly Scooter
156902          1614727528009539    0.002157  Belly Scooter
156903          1614727528013548    0.002163  Belly Scooter
156904          1614727528017557    0.002157  Belly Scooter
...                          ...         ...            ...
171863          1614727587982735    0.002213  Belly Scooter
171864          1614727587986744    0.002169  Belly Scooter
171865          1614727587990752    0.002108  Belly Scooter
171866          1614727587994761    0.002016  Belly Scooter
171867          1614727587998770    0.001985  Belly Scooter

[14968 rows x 3 columns]

In [11]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=26, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=27, second=48)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-11-6e43ca39f9c9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

        Timestamp (microseconds)  Sample (V)    Activity_Label
176857          1614727608001598    0.002053  Circular Scooter
176858          1614727608005607    0.002077  Circular Scooter
176859          1614727608009616    0.002077  Circular Scooter
176860          1614727608013625    0.002071  Circular Scooter
176861          1614727608017634    0.002053  Circular Scooter
...                          ...         ...               ...
191820          1614727667982267    0.003111  Circular Scooter
191821          1614727667986276    0.002619  Circular Scooter
191822          1614727667990285    0.001665  Circular Scooter
191823          1614727667994293    0.001345  Circular Scooter
191824          1614727667998302    0.001806  Circular Scooter

[14968 rows x 3 columns]

In [12]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=28, second=38)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=29, second=38)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-12-62c8015393b6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

        Timestamp (microseconds)  Sample (V) Activity_Label
204298          1614727718000767    0.001911   Cycling Slow
204299          1614727718004776    0.001923   Cycling Slow
204300          1614727718008785    0.001917   Cycling Slow
204301          1614727718012794    0.001911   Cycling Slow
204302          1614727718016802    0.001899   Cycling Slow
...                          ...         ...            ...
219261          1614727777980612    0.002169   Cycling Slow
219262          1614727777984621    0.002163   Cycling Slow
219263          1614727777988629    0.002157   Cycling Slow
219264          1614727777992638    0.002157   Cycling Slow
219265          1614727777996647    0.002151   Cycling Slow

[14968 rows x 3 columns]

In [13]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=29, second=39)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=30, second=39)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-13-a7753a0faf12>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

        Timestamp (microseconds)  Sample (V) Activity_Label
219516          1614727779002797    0.001326   Cycling Fast
219517          1614727779006806    0.001357   Cycling Fast
219518          1614727779010814    0.001363   Cycling Fast
219519          1614727779014823    0.001376   Cycling Fast
219520          1614727779018832    0.001382   Cycling Fast
...                          ...         ...            ...
234480          1614727838983110    0.002034   Cycling Fast
234481          1614727838987118    0.002065   Cycling Fast
234482          1614727838991127    0.002089   Cycling Fast
234483          1614727838995135    0.002114   Cycling Fast
234484          1614727838999115    0.002120   Cycling Fast

[14969 rows x 3 columns]

In [14]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=32, second=10)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=33, second=10)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-14-c83eecb4c88d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
257189          1614727930003279    0.002046  Medicine_ball
257190          1614727930007288    0.002053  Medicine_ball
257191          1614727930011296    0.002071  Medicine_ball
257192          1614727930015304    0.002053  Medicine_ball
257193          1614727930019312    0.002034  Medicine_ball
...                          ...         ...            ...
272153          1614727989981871    0.001646  Medicine_ball
272154          1614727989985880    0.001628  Medicine_ball
272155          1614727989989888    0.001640  Medicine_ball
272156          1614727989993896    0.001603  Medicine_ball
272157          1614727989997904    0.001542  Medicine_ball

[14969 rows x 3 columns]

In [15]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=34, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=35, second=5)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-15-39cde526a6ce>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

        Timestamp (microseconds)  Sample (V)              Activity_Label
285880          1614728045001241    0.001277  Medicine ball with burpies
285881          1614728045005250    0.001265  Medicine ball with burpies
285882          1614728045009258    0.001289  Medicine ball with burpies
285883          1614728045013266    0.001363  Medicine ball with burpies
285884          1614728045017274    0.001431  Medicine ball with burpies
...                          ...         ...                         ...
300845          1614728104982712    0.002096  Medicine ball with burpies
300846          1614728104986721    0.002028  Medicine ball with burpies
300847          1614728104990729    0.002028  Medicine ball with burpies
300848          1614728104994737    0.002046  Medicine ball with burpies
300849          1614728104998746    0.002022  Medicine ball with burpies

[14970 rows x 3 columns]

In [16]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=35, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=36, second=45)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-16-73853a894c47>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
310830          1614728145003692    0.000668     punch ball
310831          1614728145007701    0.000779     punch ball
310832          1614728145011709    0.000797     punch ball
310833          1614728145015717    0.000735     punch ball
310834          1614728145019725    0.000588     punch ball
...                          ...         ...            ...
325794          1614728204981218    0.002089     punch ball
325795          1614728204985226    0.002089     punch ball
325796          1614728204989235    0.002089     punch ball
325797          1614728204993243    0.002089     punch ball
325798          1614728204997251    0.002083     punch ball

[14969 rows x 3 columns]

In [17]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=37, second=41)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=38, second=41)
end_ts=int(end.timestamp() * 1e6)

DF13= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-17-2756ef5b03ba>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

        Timestamp (microseconds)  Sample (V)   Activity_Label
339771          1614728261002238    0.001425  Squarts Toe ups
339772          1614728261006246    0.001419  Squarts Toe ups
339773          1614728261010254    0.001425  Squarts Toe ups
339774          1614728261014263    0.001431  Squarts Toe ups
339775          1614728261018271    0.001419  Squarts Toe ups
...                          ...         ...              ...
354736          1614728320983221    0.001979  Squarts Toe ups
354737          1614728320987229    0.001997  Squarts Toe ups
354738          1614728320991237    0.002009  Squarts Toe ups
354739          1614728320995246    0.002003  Squarts Toe ups
354740          1614728320999254    0.001997  Squarts Toe ups

[14970 rows x 3 columns]

In [18]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=40, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=41, second=57)
end_ts=int(end.timestamp() * 1e6)

DF14= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-18-9b2eac7a4fe1>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

        Timestamp (microseconds)  Sample (V) Activity_Label
388672          1614728457000002    0.001880   Weight lifts
388673          1614728457004010    0.001874   Weight lifts
388674          1614728457008018    0.001886   Weight lifts
388675          1614728457012026    0.001886   Weight lifts
388676          1614728457016035    0.001899   Weight lifts
...                          ...         ...            ...
403638          1614728516983500    0.001923   Weight lifts
403639          1614728516987508    0.001929   Weight lifts
403640          1614728516991516    0.001948   Weight lifts
403641          1614728516995524    0.001954   Weight lifts
403642          1614728516999531    0.001973   Weight lifts

[14971 rows x 3 columns]

In [19]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=42, second=25)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=43, second=25)
end_ts=int(end.timestamp() * 1e6)

DF15= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-19-adc01cb99e89>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

        Timestamp (microseconds)  Sample (V)      Activity_Label
410629          1614728545002486    0.001099  Heavy Weight lifts
410630          1614728545006494    0.001092  Heavy Weight lifts
410631          1614728545010502    0.001092  Heavy Weight lifts
410632          1614728545014510    0.001068  Heavy Weight lifts
410633          1614728545018518    0.001049  Heavy Weight lifts
...                          ...         ...                 ...
425595          1614728604983348    0.002053  Heavy Weight lifts
425596          1614728604987356    0.002053  Heavy Weight lifts
425597          1614728604991364    0.002053  Heavy Weight lifts
425598          1614728604995371    0.002028  Heavy Weight lifts
425599          1614728604999379    0.002046  Heavy Weight lifts

[14971 rows x 3 columns]

In [20]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=44, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=45, second=48)
end_ts=int(end.timestamp() * 1e6)

DF16= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-20-8bf7d648a5da>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

        Timestamp (microseconds)  Sample (V)          Activity_Label
446309          1614728688002070    0.002034  Forward Lunges on Bosu
446310          1614728688006077    0.002040  Forward Lunges on Bosu
446311          1614728688010085    0.002046  Forward Lunges on Bosu
446312          1614728688014093    0.002046  Forward Lunges on Bosu
446313          1614728688018101    0.002053  Forward Lunges on Bosu
...                          ...         ...                     ...
461275          1614728747982780    0.002822  Forward Lunges on Bosu
461276          1614728747986787    0.002957  Forward Lunges on Bosu
461277          1614728747990795    0.002890  Forward Lunges on Bosu
461278          1614728747994803    0.002717  Forward Lunges on Bosu
461279          1614728747998811    0.002520  Forward Lunges on Bosu

[14971 rows x 3 columns]

In [21]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=46, second=20)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=47, second=20)
end_ts=int(end.timestamp() * 1e6)

DF17= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-21-44bf7fb31c51>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
469264          1614728780000459    0.002065  Split squart left on Bosu
469265          1614728780004467    0.002059  Split squart left on Bosu
469266          1614728780008475    0.002089  Split squart left on Bosu
469267          1614728780012483    0.002126  Split squart left on Bosu
469268          1614728780016491    0.002102  Split squart left on Bosu
...                          ...         ...                        ...
484230          1614728839980741    0.002157  Split squart left on Bosu
484231          1614728839984749    0.002151  Split squart left on Bosu
484232          1614728839988757    0.002139  Split squart left on Bosu
484233          1614728839992765    0.002108  Split squart left on Bosu
484234          1614728839996772    0.002071  Split squart left on Bosu

[14971 rows x 3 columns]

In [22]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=47, second=31)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=48, second=31)
end_ts=int(end.timestamp() * 1e6)

DF18= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-22-73b9289dba2c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

        Timestamp (microseconds)  Sample (V)              Activity_Label
486980          1614728851002154    0.001966  Split squart right on Bosu
486981          1614728851006162    0.001966  Split squart right on Bosu
486982          1614728851010170    0.001966  Split squart right on Bosu
486983          1614728851014177    0.001973  Split squart right on Bosu
486984          1614728851018185    0.001966  Split squart right on Bosu
...                          ...         ...                         ...
501946          1614728910983138    0.002625  Split squart right on Bosu
501947          1614728910987146    0.002625  Split squart right on Bosu
501948          1614728910991153    0.002613  Split squart right on Bosu
501949          1614728910995161    0.002619  Split squart right on Bosu
501950          1614728910999169    0.002613  Split squart right on Bosu

[14971 rows x 3 columns]

In [23]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=49, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=50, second=53)
end_ts=int(end.timestamp() * 1e6)

DF19= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-23-05a6e8a85865>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
522410          1614728993000121    0.001788  plank pie on Bosu
522411          1614728993004129    0.001837  plank pie on Bosu
522412          1614728993008136    0.001929  plank pie on Bosu
522413          1614728993012144    0.001923  plank pie on Bosu
522414          1614728993016152    0.001868  plank pie on Bosu
...                          ...         ...                ...
537376          1614729052983955    0.002403  plank pie on Bosu
537377          1614729052987963    0.002200  plank pie on Bosu
537378          1614729052991972    0.001868  plank pie on Bosu
537379          1614729052995980    0.002016  plank pie on Bosu
537380          1614729052999988    0.002188  plank pie on Bosu

[14971 rows x 3 columns]

In [24]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=51, second=26)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=52, second=26)
end_ts=int(end.timestamp() * 1e6)

DF20= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-24-51871b372dd3>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
545614          1614729086001582    0.002508  plank top on Bosu
545615          1614729086005590    0.002446  plank top on Bosu
545616          1614729086009597    0.002366  plank top on Bosu
545617          1614729086013605    0.002317  plank top on Bosu
545618          1614729086017613    0.002305  plank top on Bosu
...                          ...         ...                ...
560580          1614729145983879    0.001868  plank top on Bosu
560581          1614729145987887    0.001880  plank top on Bosu
560582          1614729145991894    0.001880  plank top on Bosu
560583          1614729145995902    0.001899  plank top on Bosu
560584          1614729145999910    0.001905  plank top on Bosu

[14971 rows x 3 columns]

In [25]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=54, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=55, second=14)
end_ts=int(end.timestamp() * 1e6)

DF21= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-25-99e1737acf5b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

        Timestamp (microseconds)  Sample (V) Activity_Label
587531          1614729254000157    0.002151   dips on Bosu
587532          1614729254004164    0.002145   dips on Bosu
587533          1614729254008172    0.002151   dips on Bosu
587534          1614729254012180    0.002145   dips on Bosu
587535          1614729254016188    0.002145   dips on Bosu
...                          ...         ...            ...
602496          1614729313980762    0.001751   dips on Bosu
602497          1614729313984770    0.001745   dips on Bosu
602498          1614729313988779    0.001745   dips on Bosu
602499          1614729313992787    0.001745   dips on Bosu
602500          1614729313996795    0.001739   dips on Bosu

[14970 rows x 3 columns]

In [26]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=56, second=28)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=57, second=28)
end_ts=int(end.timestamp() * 1e6)

DF22= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-26-611e956c39ce>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

        Timestamp (microseconds)  Sample (V)                Activity_Label
620964          1614729388002027    0.001979  moveforward backward on Bosu
620965          1614729388006035    0.001973  moveforward backward on Bosu
620966          1614729388010044    0.002016  moveforward backward on Bosu
620967          1614729388014052    0.002022  moveforward backward on Bosu
620968          1614729388018060    0.002053  moveforward backward on Bosu
...                          ...         ...                           ...
635929          1614729447982005   -0.001751  moveforward backward on Bosu
635930          1614729447986013   -0.001726  moveforward backward on Bosu
635931          1614729447990021   -0.001696  moveforward backward on Bosu
635932          1614729447994030   -0.001634  moveforward backward on Bosu
635933          1614729447998038   -0.001603  moveforward backward on Bosu

[14970 rows x 3 columns]

In [27]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=58, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=59, second=33)
end_ts=int(end.timestamp() * 1e6)

DF23= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-27-bd0add6f83f7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)            Activity_Label
657141          1614729533000849    0.002243  Left leg Hip ups on Bosu
657142          1614729533004858    0.002231  Left leg Hip ups on Bosu
657143          1614729533008866    0.002231  Left leg Hip ups on Bosu
657144          1614729533012874    0.002262  Left leg Hip ups on Bosu
657145          1614729533016883    0.002268  Left leg Hip ups on Bosu
...                          ...         ...                       ...
667116          1614729572982662    0.002249  Left leg Hip ups on Bosu
667117          1614729572986670    0.002237  Left leg Hip ups on Bosu
667118          1614729572990678    0.002237  Left leg Hip ups on Bosu
667119          1614729572994687    0.002243  Left leg Hip ups on Bosu
667120          1614729572998695    0.002317  Left leg Hip ups on Bosu

[9980 rows x 3 columns]

In [28]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=23, minute=59, second=41)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=0, second=41)
end_ts=int(end.timestamp() * 1e6)

DF24= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-28-9a8589f42154>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
669117          1614729581003195    0.001776  right leg Hip ups on Bosu
669118          1614729581007204    0.001757  right leg Hip ups on Bosu
669119          1614729581011212    0.001732  right leg Hip ups on Bosu
669120          1614729581015220    0.001769  right leg Hip ups on Bosu
669121          1614729581019229    0.001806  right leg Hip ups on Bosu
...                          ...         ...                        ...
684081          1614729640982339    0.002305  right leg Hip ups on Bosu
684082          1614729640986347    0.002305  right leg Hip ups on Bosu
684083          1614729640990355    0.002305  right leg Hip ups on Bosu
684084          1614729640994363    0.002305  right leg Hip ups on Bosu
684085          1614729640998372    0.002311  right leg Hip ups on Bosu

[14969 rows x 3 columns]

In [29]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=1, second=39)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=2, second=39)
end_ts=int(end.timestamp() * 1e6)

DF25= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-29-5305ae272a4e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

        Timestamp (microseconds)  Sample (V)         Activity_Label
698557          1614729699003665    0.001911  V-Shift Swift on Bosu
698558          1614729699007673    0.001899  V-Shift Swift on Bosu
698559          1614729699011681    0.001899  V-Shift Swift on Bosu
698560          1614729699015689    0.001893  V-Shift Swift on Bosu
698561          1614729699019696    0.001893  V-Shift Swift on Bosu
...                          ...         ...                    ...
713522          1614729758981404    0.001825  V-Shift Swift on Bosu
713523          1614729758985412    0.001794  V-Shift Swift on Bosu
713524          1614729758989420    0.001782  V-Shift Swift on Bosu
713525          1614729758993427    0.001812  V-Shift Swift on Bosu
713526          1614729758997435    0.001812  V-Shift Swift on Bosu

[14970 rows x 3 columns]

In [30]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=4, second=50)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=5, second=20)
end_ts=int(end.timestamp() * 1e6)

DF26= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-30-62e7ea01958b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

        Timestamp (microseconds)  Sample (V)    Activity_Label
746212          1614729890000692    0.002022  Freestyle Boxing
746213          1614729890004700    0.001923  Freestyle Boxing
746214          1614729890008708    0.001862  Freestyle Boxing
746215          1614729890012715    0.001874  Freestyle Boxing
746216          1614729890016723    0.001886  Freestyle Boxing
...                          ...         ...               ...
753692          1614729919980229    0.001209  Freestyle Boxing
753693          1614729919984237    0.001443  Freestyle Boxing
753694          1614729919988245    0.001640  Freestyle Boxing
753695          1614729919992252    0.001862  Freestyle Boxing
753696          1614729919996260    0.001905  Freestyle Boxing

[7485 rows x 3 columns]

In [31]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=5, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=6, second=5)
end_ts=int(end.timestamp() * 1e6)

DF27= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-31-4d4ae45a50a9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

        Timestamp (microseconds)  Sample (V)           Activity_Label
757440          1614729935002105    0.002465  Left_Right_Punches_flip
757441          1614729935006113    0.002465  Left_Right_Punches_flip
757442          1614729935010121    0.002459  Left_Right_Punches_flip
757443          1614729935014129    0.002459  Left_Right_Punches_flip
757444          1614729935018137    0.002453  Left_Right_Punches_flip
...                          ...         ...                      ...
764920          1614729964981520    0.002742  Left_Right_Punches_flip
764921          1614729964985528    0.002668  Left_Right_Punches_flip
764922          1614729964989536    0.002650  Left_Right_Punches_flip
764923          1614729964993544    0.002686  Left_Right_Punches_flip
764924          1614729964997552    0.002650  Left_Right_Punches_flip

[7485 rows x 3 columns]

In [32]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=6, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=7, second=0)
end_ts=int(end.timestamp() * 1e6)

DF28= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-32-b6ae49724534>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

        Timestamp (microseconds)  Sample (V)    Activity_Label
771163          1614729990002970    0.003431  left_Right_Punch
771164          1614729990006978    0.003228  left_Right_Punch
771165          1614729990010985    0.003031  left_Right_Punch
771166          1614729990014993    0.002699  left_Right_Punch
771167          1614729990019001    0.002514  left_Right_Punch
...                          ...         ...               ...
778643          1614730019982293    0.002145  left_Right_Punch
778644          1614730019986301    0.002163  left_Right_Punch
778645          1614730019990309    0.002169  left_Right_Punch
778646          1614730019994317    0.002176  left_Right_Punch
778647          1614730019998324    0.002176  left_Right_Punch

[7485 rows x 3 columns]

In [33]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=7, second=25)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=7, second=55)
end_ts=int(end.timestamp() * 1e6)

DF29= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-33-3e47b134e312>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

        Timestamp (microseconds)  Sample (V) Activity_Label
784886          1614730045003591    0.001646       one_twos
784887          1614730045007599    0.001652       one_twos
784888          1614730045011607    0.001671       one_twos
784889          1614730045015615    0.001689       one_twos
784890          1614730045019622    0.001702       one_twos
...                          ...         ...            ...
792366          1614730074982426    0.001296       one_twos
792367          1614730074986434    0.001289       one_twos
792368          1614730074990442    0.001265       one_twos
792369          1614730074994450    0.001252       one_twos
792370          1614730074998458    0.001246       one_twos

[7485 rows x 3 columns]

In [34]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=8, second=20)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=8, second=50)
end_ts=int(end.timestamp() * 1e6)

DF30= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-34-527a7c96d521>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

        Timestamp (microseconds)  Sample (V) Activity_Label
798609          1614730100003511    0.001659          hooks
798610          1614730100007518    0.001677          hooks
798611          1614730100011526    0.001708          hooks
798612          1614730100015503    0.001677          hooks
798613          1614730100019510    0.001677          hooks
...                          ...         ...            ...
806089          1614730129982040    0.001302          hooks
806090          1614730129986047    0.001363          hooks
806091          1614730129990055    0.001400          hooks
806092          1614730129994063    0.001357          hooks
806093          1614730129998071    0.001265          hooks

[7485 rows x 3 columns]

In [35]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=9, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=10, second=0)
end_ts=int(end.timestamp() * 1e6)

DF31= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-35-41bc27625cdc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

        Timestamp (microseconds)  Sample (V) Activity_Label
816074          1614730170000068    0.001486     Upper_cuts
816075          1614730170004076    0.001474     Upper_cuts
816076          1614730170008084    0.001462     Upper_cuts
816077          1614730170012092    0.001431     Upper_cuts
816078          1614730170016100    0.001406     Upper_cuts
...                          ...         ...            ...
823555          1614730199982820    0.003394     Upper_cuts
823556          1614730199986827    0.003388     Upper_cuts
823557          1614730199990835    0.003382     Upper_cuts
823558          1614730199994843    0.003382     Upper_cuts
823559          1614730199998851    0.003382     Upper_cuts

[7486 rows x 3 columns]

In [36]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=10, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=11, second=0)
end_ts=int(end.timestamp() * 1e6)

DF32= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-36-b64c1217bae8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

        Timestamp (microseconds)  Sample (V) Activity_Label
831045          1614730230001763    0.002446            run
831046          1614730230005771    0.002446            run
831047          1614730230009779    0.002440            run
831048          1614730230013787    0.002434            run
831049          1614730230017795    0.002440            run
...                          ...         ...            ...
838526          1614730259983812    0.001585            run
838527          1614730259987820    0.001566            run
838528          1614730259991828    0.001560            run
838529          1614730259995835    0.001548            run
838530          1614730259999843    0.001529            run

[7486 rows x 3 columns]

In [37]:
start=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=11, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=3, hour=0, minute=12, second=14)
end_ts=int(end.timestamp() * 1e6)

DF33= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-37-20115ab86b87>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

        Timestamp (microseconds)  Sample (V)       Activity_Label
850009          1614730306003738    0.001652  Punch_down_Up_Hooks
850010          1614730306007745    0.001628  Punch_down_Up_Hooks
850011          1614730306011753    0.001622  Punch_down_Up_Hooks
850012          1614730306015761    0.001609  Punch_down_Up_Hooks
850013          1614730306019769    0.001597  Punch_down_Up_Hooks
...                          ...         ...                  ...
856990          1614730333981639    0.001689  Punch_down_Up_Hooks
856991          1614730333985646    0.001702  Punch_down_Up_Hooks
856992          1614730333989654    0.001714  Punch_down_Up_Hooks
856993          1614730333993662    0.001708  Punch_down_Up_Hooks
856994          1614730333997670    0.001708  Punch_down_Up_Hooks

[6986 rows x 3 columns]

In [40]:
sub08_final_chest_elec=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub08_final_chest_elec

        Timestamp (microseconds)  Sample (V)             Activity_Label
0               1614726944003392    0.001991  Forward and backward step
1               1614726944007400    0.002003  Forward and backward step
2               1614726944011408    0.001997  Forward and backward step
3               1614726944015417    0.001985  Forward and backward step
4               1614726944019425    0.001985  Forward and backward step
...                          ...         ...                        ...
430120          1614730333981639    0.001689        Punch_down_Up_Hooks
430121          1614730333985646    0.001702        Punch_down_Up_Hooks
430122          1614730333989654    0.001714        Punch_down_Up_Hooks
430123          1614730333993662    0.001708        Punch_down_Up_Hooks
430124          1614730333997670    0.001708        Punch_down_Up_Hooks

[430125 rows x 3 columns]

In [41]:
sub08_final_chest_elec.to_csv('final_cleaned_chest_elec-sub08.csv-sub08')