In [5]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [6]:
df1=pd.read_csv('/Users/shreyasaswar/HARDataset/EXTRACTION/SUB 07/chest/elec.csv')

In [7]:
df1

         Timestamp (microseconds)  Sample (V)
0                1614720292790344    0.002379
1                1614720292794348    0.002268
2                1614720292798352    0.002169
3                1614720292802356    0.002089
4                1614720292806360    0.002071
...                           ...         ...
1007715          1614724331984483    0.002373
1007716          1614724331988491    0.002286
1007717          1614724331992498    0.002163
1007718          1614724331996505    0.002046
1007719          1614724332000513    0.002071

[1007720 rows x 2 columns]

In [8]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-02 21:24:52.790344')

In [9]:
start = pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=27, second=1)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=28, second=1)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3799124589.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

       Timestamp (microseconds)  Sample (V)             Activity_Label
31991          1614720421001216    0.001874  Forward and backward step
31992          1614720421005224    0.001893  Forward and backward step
31993          1614720421009232    0.001893  Forward and backward step
31994          1614720421013239    0.001899  Forward and backward step
31995          1614720421017247    0.001929  Forward and backward step
...                         ...         ...                        ...
46957          1614720480982750    0.001732  Forward and backward step
46958          1614720480986758    0.001757  Forward and backward step
46959          1614720480990766    0.001776  Forward and backward step
46960          1614720480994773    0.001776  Forward and backward step
46961          1614720480998781    0.001788  Forward and backward step

[14971 rows x 3 columns]

In [10]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=28, second=24)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=29, second=24)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1812762020.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

       Timestamp (microseconds)  Sample (V) Activity_Label
52701          1614720504003633    0.001874  Sideward step
52702          1614720504007640    0.001862  Sideward step
52703          1614720504011648    0.001868  Sideward step
52704          1614720504015655    0.001880  Sideward step
52705          1614720504019663    0.001856  Sideward step
...                         ...         ...            ...
67666          1614720563981005    0.001917  Sideward step
67667          1614720563985013    0.001899  Sideward step
67668          1614720563989021    0.001886  Sideward step
67669          1614720563993029    0.001862  Sideward step
67670          1614720563997037    0.001831  Sideward step

[14970 rows x 3 columns]

In [11]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=30, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=31, second=6)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3142598602.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

       Timestamp (microseconds)  Sample (V) Activity_Label
78151          1614720606003396    0.002077        Pushups
78152          1614720606007404    0.002071        Pushups
78153          1614720606011412    0.001991        Pushups
78154          1614720606015420    0.001905        Pushups
78155          1614720606019427    0.001911        Pushups
...                         ...         ...            ...
93116          1614720665981989    0.002237        Pushups
93117          1614720665985997    0.001991        Pushups
93118          1614720665990005    0.001572        Pushups
93119          1614720665994013    0.001714        Pushups
93120          1614720665998021    0.001954        Pushups

[14970 rows x 3 columns]

In [12]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=31, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=32, second=55)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/2035253662.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Sample (V),Activity_Label
105347,1614720715002533,0.002157,Hip raise step with punches in the air
105348,1614720715006541,0.002040,Hip raise step with punches in the air
105349,1614720715010549,0.001831,Hip raise step with punches in the air
105350,1614720715014557,0.001788,Hip raise step with punches in the air
105351,1614720715018564,0.001812,Hip raise step with punches in the air
...,...,...,...
120312,1614720774983089,0.001505,Hip raise step with punches in the air
120313,1614720774987097,0.001456,Hip raise step with punches in the air
120314,1614720774991106,0.001412,Hip raise step with punches in the air
120315,1614720774995114,0.001449,Hip raise step with punches in the air
120316,1614720774999122,0.001511,Hip raise step with punches in the air

In [13]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=34, second=12)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=35, second=12)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3801562877.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

        Timestamp (microseconds)  Sample (V)          Activity_Label
139527          1614720852001429    0.002102  Front and back scooter
139528          1614720852005437    0.002114  Front and back scooter
139529          1614720852009446    0.002157  Front and back scooter
139530          1614720852013454    0.002151  Front and back scooter
139531          1614720852017462    0.002114  Front and back scooter
...                          ...         ...                     ...
154492          1614720911983543    0.002003  Front and back scooter
154493          1614720911987551    0.001991  Front and back scooter
154494          1614720911991560    0.001979  Front and back scooter
154495          1614720911995568    0.001960  Front and back scooter
154496          1614720911999576    0.001942  Front and back scooter

[14970 rows x 3 columns]

In [14]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=36, second=10)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=37, second=10)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3213495643.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

        Timestamp (microseconds)  Sample (V) Activity_Label
168967          1614720970000821    0.001868  Belly Scooter
168968          1614720970004829    0.001862  Belly Scooter
168969          1614720970008837    0.001856  Belly Scooter
168970          1614720970012848    0.001856  Belly Scooter
168971          1614720970016856    0.001849  Belly Scooter
...                          ...         ...            ...
183932          1614721029982782    0.002397  Belly Scooter
183933          1614721029986790    0.002545  Belly Scooter
183934          1614721029990799    0.002477  Belly Scooter
183935          1614721029994807    0.002151  Belly Scooter
183936          1614721029998815    0.001812  Belly Scooter

[14970 rows x 3 columns]

In [15]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=38, second=12)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=39, second=12)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1737299949.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

        Timestamp (microseconds)  Sample (V)    Activity_Label
199405          1614721092000811    0.002009  Circular Scooter
199406          1614721092004819    0.002016  Circular Scooter
199407          1614721092008828    0.002022  Circular Scooter
199408          1614721092012836    0.002040  Circular Scooter
199409          1614721092016844    0.002053  Circular Scooter
...                          ...         ...               ...
214369          1614721151980260    0.002114  Circular Scooter
214370          1614721151984268    0.002108  Circular Scooter
214371          1614721151988276    0.002102  Circular Scooter
214372          1614721151992284    0.002096  Circular Scooter
214373          1614721151996293    0.002108  Circular Scooter

[14969 rows x 3 columns]

In [16]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=40, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=41, second=30)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3512200316.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

        Timestamp (microseconds)  Sample (V) Activity_Label
233834          1614721230002843    0.001720   Cycling Slow
233835          1614721230006852    0.001714   Cycling Slow
233836          1614721230010860    0.001726   Cycling Slow
233837          1614721230014868    0.001720   Cycling Slow
233838          1614721230018877    0.001708   Cycling Slow
...                          ...         ...            ...
248798          1614721289981010    0.001973   Cycling Slow
248799          1614721289985018    0.001979   Cycling Slow
248800          1614721289989027    0.001979   Cycling Slow
248801          1614721289993035    0.002003   Cycling Slow
248802          1614721289997043    0.002009   Cycling Slow

[14969 rows x 3 columns]

In [17]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=41, second=31)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=42, second=31)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1942892779.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

        Timestamp (microseconds)  Sample (V) Activity_Label
249053          1614721291003068    0.002108   Cycling Fast
249054          1614721291007076    0.002114   Cycling Fast
249055          1614721291011084    0.002071   Cycling Fast
249056          1614721291015092    0.002034   Cycling Fast
249057          1614721291019101    0.002059   Cycling Fast
...                          ...         ...            ...
264018          1614721350981057    0.001929   Cycling Fast
264019          1614721350985065    0.001923   Cycling Fast
264020          1614721350989072    0.001936   Cycling Fast
264021          1614721350993080    0.001954   Cycling Fast
264022          1614721350997088    0.001966   Cycling Fast

[14970 rows x 3 columns]

In [18]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=43, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=44, second=35)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3814872367.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
279993          1614721415002593    0.001529  Medicine_ball
279994          1614721415006601    0.001468  Medicine_ball
279995          1614721415010609    0.001394  Medicine_ball
279996          1614721415014617    0.001443  Medicine_ball
279997          1614721415018624    0.001554  Medicine_ball
...                          ...         ...            ...
294959          1614721474981594    0.001689  Medicine_ball
294960          1614721474985602    0.001616  Medicine_ball
294961          1614721474989610    0.001782  Medicine_ball
294962          1614721474993618    0.002059  Medicine_ball
294963          1614721474997625    0.002133  Medicine_ball

[14971 rows x 3 columns]

In [19]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=44, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=45, second=45)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1051799127.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

        Timestamp (microseconds)  Sample (V)              Activity_Label
297459          1614721485000718    0.001954  Medicine ball with burpies
297460          1614721485004726    0.001973  Medicine ball with burpies
297461          1614721485008734    0.002016  Medicine ball with burpies
297462          1614721485012742    0.002003  Medicine ball with burpies
297463          1614721485016749    0.001948  Medicine ball with burpies
...                          ...         ...                         ...
312425          1614721544980330    0.002009  Medicine ball with burpies
312426          1614721544984337    0.002003  Medicine ball with burpies
312427          1614721544988345    0.001960  Medicine ball with burpies
312428          1614721544992353    0.001917  Medicine ball with burpies
312429          1614721544996361    0.001874  Medicine ball with burpies

[14971 rows x 3 columns]

In [20]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=47, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=48, second=5)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3380979360.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
332392          1614721625003509    0.002071     punch ball
332393          1614721625007517    0.002071     punch ball
332394          1614721625011525    0.002096     punch ball
332395          1614721625015533    0.002083     punch ball
332396          1614721625019540    0.002089     punch ball
...                          ...         ...            ...
347357          1614721684981889    0.001960     punch ball
347358          1614721684985897    0.001985     punch ball
347359          1614721684989905    0.002003     punch ball
347360          1614721684993912    0.002016     punch ball
347361          1614721684997920    0.002022     punch ball

[14970 rows x 3 columns]

In [21]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=49, second=50)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=50, second=50)
end_ts=int(end.timestamp() * 1e6)

DF13= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1612414173.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

        Timestamp (microseconds)  Sample (V)   Activity_Label
373560          1614721790002977    0.002083  Squarts Toe ups
373561          1614721790006985    0.002083  Squarts Toe ups
373562          1614721790010994    0.002083  Squarts Toe ups
373563          1614721790015002    0.002071  Squarts Toe ups
373564          1614721790019012    0.002089  Squarts Toe ups
...                          ...         ...              ...
388524          1614721849982029    0.002206  Squarts Toe ups
388525          1614721849986037    0.002206  Squarts Toe ups
388526          1614721849990045    0.002194  Squarts Toe ups
388527          1614721849994053    0.002213  Squarts Toe ups
388528          1614721849998062    0.002237  Squarts Toe ups

[14969 rows x 3 columns]

In [22]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=51, second=38)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=52, second=38)
end_ts=int(end.timestamp() * 1e6)

DF14= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1850055648.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

        Timestamp (microseconds)  Sample (V) Activity_Label
400504          1614721898001995    0.001966   Weight lifts
400505          1614721898006003    0.001966   Weight lifts
400506          1614721898010011    0.001973   Weight lifts
400507          1614721898014020    0.001979   Weight lifts
400508          1614721898018028    0.001979   Weight lifts
...                          ...         ...            ...
415467          1614721957980181    0.002286   Weight lifts
415468          1614721957984190    0.002237   Weight lifts
415469          1614721957988198    0.002120   Weight lifts
415470          1614721957992206    0.001948   Weight lifts
415471          1614721957996214    0.001745   Weight lifts

[14968 rows x 3 columns]

In [23]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=54, second=0)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=55, second=0)
end_ts=int(end.timestamp() * 1e6)

DF15= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1060923929.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

        Timestamp (microseconds)  Sample (V)      Activity_Label
435929          1614722040002663    0.002299  Heavy Weight lifts
435930          1614722040006672    0.002311  Heavy Weight lifts
435931          1614722040010680    0.002329  Heavy Weight lifts
435932          1614722040014689    0.002323  Heavy Weight lifts
435933          1614722040018698    0.002311  Heavy Weight lifts
...                          ...         ...                 ...
450892          1614722099982167    0.002077  Heavy Weight lifts
450893          1614722099986176    0.002126  Heavy Weight lifts
450894          1614722099990184    0.002120  Heavy Weight lifts
450895          1614722099994193    0.002077  Heavy Weight lifts
450896          1614722099998202    0.002083  Heavy Weight lifts

[14968 rows x 3 columns]

In [24]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=56, second=32)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=57, second=32)
end_ts=int(end.timestamp() * 1e6)

DF16= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1473733007.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

        Timestamp (microseconds)  Sample (V)          Activity_Label
473848          1614722192001770    0.001874  Forward Lunges on Bosu
473849          1614722192005778    0.001893  Forward Lunges on Bosu
473850          1614722192009787    0.001948  Forward Lunges on Bosu
473851          1614722192013796    0.002034  Forward Lunges on Bosu
473852          1614722192017805    0.002169  Forward Lunges on Bosu
...                          ...         ...                     ...
488811          1614722251982342    0.001560  Forward Lunges on Bosu
488812          1614722251986351    0.001566  Forward Lunges on Bosu
488813          1614722251990359    0.001566  Forward Lunges on Bosu
488814          1614722251994368    0.001572  Forward Lunges on Bosu
488815          1614722251998377    0.001566  Forward Lunges on Bosu

[14968 rows x 3 columns]

In [25]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=58, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=59, second=6)
end_ts=int(end.timestamp() * 1e6)

DF17= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3859480605.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
497298          1614722286002879    0.001991  Split squart left on Bosu
497299          1614722286006888    0.001991  Split squart left on Bosu
497300          1614722286010896    0.001985  Split squart left on Bosu
497301          1614722286014905    0.001985  Split squart left on Bosu
497302          1614722286018914    0.001991  Split squart left on Bosu
...                          ...         ...                        ...
512260          1614722345980388    0.001874  Split squart left on Bosu
512261          1614722345984397    0.001886  Split squart left on Bosu
512262          1614722345988406    0.001899  Split squart left on Bosu
512263          1614722345992415    0.001886  Split squart left on Bosu
512264          1614722345996423    0.001893  Split squart left on Bosu

[14967 rows x 3 columns]

In [26]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=21, minute=59, second=27)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=0, second=27)
end_ts=int(end.timestamp() * 1e6)

DF18= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/238586185.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

        Timestamp (microseconds)  Sample (V)              Activity_Label
517504          1614722367002064    0.001942  Split squart right on Bosu
517505          1614722367006073    0.001942  Split squart right on Bosu
517506          1614722367010082    0.001936  Split squart right on Bosu
517507          1614722367014091    0.001929  Split squart right on Bosu
517508          1614722367018099    0.001929  Split squart right on Bosu
...                          ...         ...                         ...
532466          1614722426981532    0.002022  Split squart right on Bosu
532467          1614722426985540    0.002028  Split squart right on Bosu
532468          1614722426989549    0.002022  Split squart right on Bosu
532469          1614722426993558    0.002022  Split squart right on Bosu
532470          1614722426997567    0.002009  Split squart right on Bosu

[14967 rows x 3 columns]

In [27]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=2, second=27)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=3, second=27)
end_ts=int(end.timestamp() * 1e6)

DF19= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/2115299968.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
562405          1614722547003910    0.002293  plank pie on Bosu
562406          1614722547007919    0.002551  plank pie on Bosu
562407          1614722547011928    0.002379  plank pie on Bosu
562408          1614722547015937    0.002280  plank pie on Bosu
562409          1614722547019947    0.002459  plank pie on Bosu
...                          ...         ...                ...
577365          1614722606980312    0.001302  plank pie on Bosu
577366          1614722606984321    0.001234  plank pie on Bosu
577367          1614722606988330    0.001080  plank pie on Bosu
577368          1614722606992340    0.001031  plank pie on Bosu
577369          1614722606996349    0.001080  plank pie on Bosu

[14965 rows x 3 columns]

In [28]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=4, second=20)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=5, second=20)
end_ts=int(end.timestamp() * 1e6)

DF20= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3705483204.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
590591          1614722660003772    0.001216  plank top on Bosu
590592          1614722660007782    0.001302  plank top on Bosu
590593          1614722660011791    0.001345  plank top on Bosu
590594          1614722660015800    0.001326  plank top on Bosu
590595          1614722660019809    0.001302  plank top on Bosu
...                          ...         ...                ...
605552          1614722719982261    0.002003  plank top on Bosu
605553          1614722719986271    0.001973  plank top on Bosu
605554          1614722719990280    0.001954  plank top on Bosu
605555          1614722719994289    0.001936  plank top on Bosu
605556          1614722719998298    0.001929  plank top on Bosu

[14966 rows x 3 columns]

In [29]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=6, second=36)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=7, second=36)
end_ts=int(end.timestamp() * 1e6)

DF21= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/749266904.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

        Timestamp (microseconds)  Sample (V) Activity_Label
624515          1614722796002068    0.002089   dips on Bosu
624516          1614722796006076    0.002034   dips on Bosu
624517          1614722796010085    0.001985   dips on Bosu
624518          1614722796014099    0.001936   dips on Bosu
624519          1614722796018108    0.001843   dips on Bosu
...                          ...         ...            ...
639477          1614722855981718    0.002126   dips on Bosu
639478          1614722855985727    0.002096   dips on Bosu
639479          1614722855989736    0.002102   dips on Bosu
639480          1614722855993744    0.002108   dips on Bosu
639481          1614722855997753    0.002102   dips on Bosu

[14967 rows x 3 columns]

In [30]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=8, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=9, second=37)
end_ts=int(end.timestamp() * 1e6)

DF22= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3342656394.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

        Timestamp (microseconds)  Sample (V)                Activity_Label
654699          1614722917003201    0.001566  moveforward backward on Bosu
654700          1614722917007209    0.001554  moveforward backward on Bosu
654701          1614722917011218    0.001566  moveforward backward on Bosu
654702          1614722917015227    0.001548  moveforward backward on Bosu
654703          1614722917019236    0.001505  moveforward backward on Bosu
...                          ...         ...                           ...
669661          1614722976981752    0.002053  moveforward backward on Bosu
669662          1614722976985761    0.002071  moveforward backward on Bosu
669663          1614722976989770    0.002120  moveforward backward on Bosu
669664          1614722976993779    0.002151  moveforward backward on Bosu
669665          1614722976997788    0.002114  moveforward backward on Bosu

[14967 rows x 3 columns]

In [31]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=11, second=1)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=12, second=1)
end_ts=int(end.timestamp() * 1e6)

DF23= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/735060598.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)            Activity_Label
690620          1614723061001279    0.001572  Left leg Hip ups on Bosu
690621          1614723061005288    0.001579  Left leg Hip ups on Bosu
690622          1614723061009297    0.001572  Left leg Hip ups on Bosu
690623          1614723061013306    0.001591  Left leg Hip ups on Bosu
690624          1614723061017315    0.001609  Left leg Hip ups on Bosu
...                          ...         ...                       ...
705582          1614723120980533    0.002120  Left leg Hip ups on Bosu
705583          1614723120984542    0.002120  Left leg Hip ups on Bosu
705584          1614723120988551    0.002126  Left leg Hip ups on Bosu
705585          1614723120992560    0.002126  Left leg Hip ups on Bosu
705586          1614723120996568    0.002126  Left leg Hip ups on Bosu

[14967 rows x 3 columns]

In [32]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=12, second=6)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=13, second=6)
end_ts=int(end.timestamp() * 1e6)

DF24= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3074852332.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
706835          1614723126003692    0.001905  right leg Hip ups on Bosu
706836          1614723126007701    0.001893  right leg Hip ups on Bosu
706837          1614723126011709    0.001874  right leg Hip ups on Bosu
706838          1614723126015718    0.001880  right leg Hip ups on Bosu
706839          1614723126019727    0.001905  right leg Hip ups on Bosu
...                          ...         ...                        ...
721796          1614723185983566    0.002219  right leg Hip ups on Bosu
721797          1614723185987575    0.002151  right leg Hip ups on Bosu
721798          1614723185991584    0.002065  right leg Hip ups on Bosu
721799          1614723185995594    0.001985  right leg Hip ups on Bosu
721800          1614723185999603    0.001979  right leg Hip ups on Bosu

[14966 rows x 3 columns]

In [33]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=14, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=15, second=46)
end_ts=int(end.timestamp() * 1e6)

DF25= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1908702827.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

        Timestamp (microseconds)  Sample (V)         Activity_Label
746744          1614723286002655    0.002317  V-Shift Swift on Bosu
746745          1614723286006664    0.002163  V-Shift Swift on Bosu
746746          1614723286010673    0.002059  V-Shift Swift on Bosu
746747          1614723286014682    0.002003  V-Shift Swift on Bosu
746748          1614723286018692    0.001911  V-Shift Swift on Bosu
...                          ...         ...                    ...
761705          1614723345980503    0.001997  V-Shift Swift on Bosu
761706          1614723345984512    0.001960  V-Shift Swift on Bosu
761707          1614723345988521    0.002040  V-Shift Swift on Bosu
761708          1614723345992530    0.002083  V-Shift Swift on Bosu
761709          1614723345996540    0.002053  V-Shift Swift on Bosu

[14966 rows x 3 columns]

In [34]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=18, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=19, second=24)
end_ts=int(end.timestamp() * 1e6)

DF26= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1983084487.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

        Timestamp (microseconds)  Sample (V)    Activity_Label
809107          1614723536000977    0.002742  Freestyle Boxing
809108          1614723536004985    0.002699  Freestyle Boxing
809109          1614723536008994    0.002656  Freestyle Boxing
809110          1614723536013002    0.002693  Freestyle Boxing
809111          1614723536017010    0.002625  Freestyle Boxing
...                          ...         ...               ...
816088          1614723563983011    0.002003  Freestyle Boxing
816089          1614723563987019    0.002003  Freestyle Boxing
816090          1614723563991027    0.002003  Freestyle Boxing
816091          1614723563995036    0.002003  Freestyle Boxing
816092          1614723563999044    0.002003  Freestyle Boxing

[6986 rows x 3 columns]

In [35]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=19, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=20, second=6)
end_ts=int(end.timestamp() * 1e6)

DF27= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/743417893.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

        Timestamp (microseconds)  Sample (V)           Activity_Label
819336          1614723577001691    0.001856  Left_Right_Punches_flip
819337          1614723577005700    0.001831  Left_Right_Punches_flip
819338          1614723577009708    0.001763  Left_Right_Punches_flip
819339          1614723577013716    0.001751  Left_Right_Punches_flip
819340          1614723577017725    0.001831  Left_Right_Punches_flip
...                          ...         ...                      ...
826566          1614723605980575    0.002126  Left_Right_Punches_flip
826567          1614723605984583    0.002114  Left_Right_Punches_flip
826568          1614723605988592    0.002083  Left_Right_Punches_flip
826569          1614723605992600    0.002108  Left_Right_Punches_flip
826570          1614723605996608    0.002120  Left_Right_Punches_flip

[7235 rows x 3 columns]

In [36]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=21, second=23)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=21, second=53)
end_ts=int(end.timestamp() * 1e6)

DF28= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/1645307430.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

        Timestamp (microseconds)  Sample (V)    Activity_Label
845782          1614723683000909    0.001616  left_Right_Punch
845783          1614723683004918    0.002003  left_Right_Punch
845784          1614723683008926    0.002502  left_Right_Punch
845785          1614723683012934    0.002816  left_Right_Punch
845786          1614723683016943    0.002779  left_Right_Punch
...                          ...         ...               ...
853262          1614723712981502    0.002557  left_Right_Punch
853263          1614723712985510    0.002551  left_Right_Punch
853264          1614723712989519    0.002551  left_Right_Punch
853265          1614723712993527    0.002551  left_Right_Punch
853266          1614723712997535    0.002545  left_Right_Punch

[7485 rows x 3 columns]

In [37]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=22, second=52)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=23, second=22)
end_ts=int(end.timestamp() * 1e6)

DF29= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/648734257.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

        Timestamp (microseconds)  Sample (V) Activity_Label
867988          1614723772003402    0.001702       one_twos
867989          1614723772007411    0.001880       one_twos
867990          1614723772011419    0.002028       one_twos
867991          1614723772015427    0.001985       one_twos
867992          1614723772019436    0.001782       one_twos
...                          ...         ...            ...
875468          1614723801983293    0.001843       one_twos
875469          1614723801987301    0.001849       one_twos
875470          1614723801991310    0.001843       one_twos
875471          1614723801995318    0.001843       one_twos
875472          1614723801999298    0.001831       one_twos

[7485 rows x 3 columns]

In [38]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=25, second=4)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=25, second=34)
end_ts=int(end.timestamp() * 1e6)

DF30= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/684493562.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

        Timestamp (microseconds)  Sample (V) Activity_Label
900922          1614723904001600    0.002034          hooks
900923          1614723904005608    0.002034          hooks
900924          1614723904009616    0.002016          hooks
900925          1614723904013625    0.002022          hooks
900926          1614723904017633    0.002016          hooks
...                          ...         ...            ...
908402          1614723933981193    0.001948          hooks
908403          1614723933985201    0.001905          hooks
908404          1614723933989209    0.001843          hooks
908405          1614723933993217    0.001899          hooks
908406          1614723933997224    0.001979          hooks

[7485 rows x 3 columns]

In [39]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=25, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=26, second=5)
end_ts=int(end.timestamp() * 1e6)

DF31= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3646905167.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

        Timestamp (microseconds)  Sample (V) Activity_Label
908657          1614723935003214    0.001769     Upper_cuts
908658          1614723935007222    0.001880     Upper_cuts
908659          1614723935011230    0.001905     Upper_cuts
908660          1614723935015237    0.001893     Upper_cuts
908661          1614723935019245    0.001899     Upper_cuts
...                          ...         ...            ...
916137          1614723964982202    0.002219     Upper_cuts
916138          1614723964986209    0.002243     Upper_cuts
916139          1614723964990217    0.002256     Upper_cuts
916140          1614723964994225    0.002256     Upper_cuts
916141          1614723964998233    0.002262     Upper_cuts

[7485 rows x 3 columns]

In [40]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=28, second=41)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=29, second=9)
end_ts=int(end.timestamp() * 1e6)

DF32= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3323214970.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

        Timestamp (microseconds)  Sample (V) Activity_Label
955066          1614724121000836    0.002477            run
955067          1614724121004844    0.002545            run
955068          1614724121008852    0.002502            run
955069          1614724121012859    0.002409            run
955070          1614724121016867    0.002262            run
...                          ...         ...            ...
962048          1614724148981670    0.002059            run
962049          1614724148985677    0.002108            run
962050          1614724148989685    0.002145            run
962051          1614724148993692    0.002200            run
962052          1614724148997699    0.002237            run

[6987 rows x 3 columns]

In [41]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=30, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=22, minute=31, second=0)
end_ts=int(end.timestamp() * 1e6)

DF33= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7943/3430374305.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

        Timestamp (microseconds)  Sample (V)       Activity_Label
982266          1614724230001793    0.001973  Punch_down_Up_Hooks
982267          1614724230005800    0.001893  Punch_down_Up_Hooks
982268          1614724230009807    0.001849  Punch_down_Up_Hooks
982269          1614724230013815    0.001856  Punch_down_Up_Hooks
982270          1614724230017822    0.001837  Punch_down_Up_Hooks
...                          ...         ...                  ...
989747          1614724259980772    0.001776  Punch_down_Up_Hooks
989748          1614724259984779    0.001794  Punch_down_Up_Hooks
989749          1614724259988786    0.001825  Punch_down_Up_Hooks
989750          1614724259992794    0.001819  Punch_down_Up_Hooks
989751          1614724259996801    0.001806  Punch_down_Up_Hooks

[7486 rows x 3 columns]

In [42]:
sub07_final_chest_elec=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub07_final_chest_elec

        Timestamp (microseconds)  Sample (V)             Activity_Label
0               1614720421001216    0.001874  Forward and backward step
1               1614720421005224    0.001893  Forward and backward step
2               1614720421009232    0.001893  Forward and backward step
3               1614720421013239    0.001899  Forward and backward step
4               1614720421017247    0.001929  Forward and backward step
...                          ...         ...                        ...
432841          1614724259980772    0.001776        Punch_down_Up_Hooks
432842          1614724259984779    0.001794        Punch_down_Up_Hooks
432843          1614724259988786    0.001825        Punch_down_Up_Hooks
432844          1614724259992794    0.001819        Punch_down_Up_Hooks
432845          1614724259996801    0.001806        Punch_down_Up_Hooks

[432846 rows x 3 columns]

In [43]:
sub07_final_chest_elec.to_csv('final_cleaned_chest_elec.csv-sub07')