In [2]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [3]:
df1=pd.read_csv('chest_elec.csv-sub04')

In [4]:
df1

         Timestamp (microseconds)  Sample (V)
0                1614633808693847    0.002176
1                1614633808697852    0.002108
2                1614633808701856    0.002077
3                1614633808705861    0.002046
4                1614633808709865    0.002009
...                           ...         ...
1485833          1614639763480191    0.010300
1485834          1614639763484197    0.015494
1485835          1614639763488204   -0.001031
1485836          1614639763492210   -0.007001
1485837          1614639763496216    0.007573

[1485838 rows x 2 columns]

In [5]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-01 21:23:28.693847')

In [6]:
start = pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=25, second=10)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=26, second=10)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-6-3d38c8629409>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

       Timestamp (microseconds)  Sample (V)             Activity_Label
25279          1614633910003668    0.001831  Forward and backward step
25280          1614633910007676    0.001831  Forward and backward step
25281          1614633910011684    0.001837  Forward and backward step
25282          1614633910015691    0.001831  Forward and backward step
25283          1614633910019699    0.001831  Forward and backward step
...                         ...         ...                        ...
40244          1614633969980309    0.001659  Forward and backward step
40245          1614633969984317    0.001646  Forward and backward step
40246          1614633969988325    0.001640  Forward and backward step
40247          1614633969992333    0.001640  Forward and backward step
40248          1614633969996340    0.001628  Forward and backward step

[14970 rows x 3 columns]

In [7]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=27, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=28, second=30)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-7-52059c829f89>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

       Timestamp (microseconds)  Sample (V) Activity_Label
60211          1614634050003489    0.001652  Sideward step
60212          1614634050007496    0.001646  Sideward step
60213          1614634050011504    0.001659  Sideward step
60214          1614634050015512    0.001659  Sideward step
60215          1614634050019520    0.001671  Sideward step
...                         ...         ...            ...
75176          1614634109980922    0.002662  Sideward step
75177          1614634109984930    0.002680  Sideward step
75178          1614634109988938    0.002680  Sideward step
75179          1614634109992946    0.002699  Sideward step
75180          1614634109996954    0.002711  Sideward step

[14970 rows x 3 columns]

In [8]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=30, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=31, second=46)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-8-f8e0ccbe6746>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

        Timestamp (microseconds)  Sample (V) Activity_Label
109114          1614634246002222    0.001985        Pushups
109115          1614634246006230    0.002077        Pushups
109116          1614634246010238    0.002120        Pushups
109117          1614634246014247    0.001966        Pushups
109118          1614634246018255    0.001954        Pushups
...                          ...         ...            ...
124078          1614634305980114    0.001548        Pushups
124079          1614634305984122    0.001542        Pushups
124080          1614634305988130    0.001542        Pushups
124081          1614634305992138    0.001529        Pushups
124082          1614634305996147    0.001560        Pushups

[14969 rows x 3 columns]

In [9]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=32, second=59)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=33, second=59)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-9-1a263aaffc52>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Sample (V),Activity_Label
142297,1614634379003829,0.001696,Hip raise step with punches in the air
142298,1614634379007837,0.001671,Hip raise step with punches in the air
142299,1614634379011845,0.001665,Hip raise step with punches in the air
142300,1614634379015854,0.001702,Hip raise step with punches in the air
142301,1614634379019862,0.001739,Hip raise step with punches in the air
...,...,...,...
157261,1614634438982514,0.001929,Hip raise step with punches in the air
157262,1614634438986522,0.001929,Hip raise step with punches in the air
157263,1614634438990531,0.001905,Hip raise step with punches in the air
157264,1614634438994539,0.001911,Hip raise step with punches in the air
157265,1614634438998547,0.001948,Hip raise step with punches in the air

In [10]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=35, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=56, second=57)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-10-fe9bf6b8c53a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

        Timestamp (microseconds)  Sample (V)          Activity_Label
186704          1614634557000400    0.001954  Front and back scooter
186705          1614634557004408    0.001942  Front and back scooter
186706          1614634557008417    0.001942  Front and back scooter
186707          1614634557012425    0.001954  Front and back scooter
186708          1614634557016433    0.001948  Front and back scooter
...                          ...         ...                     ...
501054          1614635816983184    0.001812  Front and back scooter
501055          1614635816987193    0.001806  Front and back scooter
501056          1614635816991201    0.001812  Front and back scooter
501057          1614635816995209    0.001812  Front and back scooter
501058          1614635816999218    0.001800  Front and back scooter

[314355 rows x 3 columns]

In [11]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=38, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=39, second=14)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-11-2faf8a20483c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

        Timestamp (microseconds)  Sample (V) Activity_Label
220883          1614634694003162    0.001929  Belly Scooter
220884          1614634694007171    0.001905  Belly Scooter
220885          1614634694011180    0.001917  Belly Scooter
220886          1614634694015189    0.001936  Belly Scooter
220887          1614634694019198    0.001923  Belly Scooter
...                          ...         ...            ...
235846          1614634753983251    0.001966  Belly Scooter
235847          1614634753987260    0.002022  Belly Scooter
235848          1614634753991269    0.002009  Belly Scooter
235849          1614634753995278    0.001929  Belly Scooter
235850          1614634753999286    0.001837  Belly Scooter

[14968 rows x 3 columns]

In [12]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=40, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=41, second=48)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-12-60737e03973e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

        Timestamp (microseconds)  Sample (V)    Activity_Label
259301          1614634848003519    0.002065  Circular Scooter
259302          1614634848007528    0.002046  Circular Scooter
259303          1614634848011537    0.001979  Circular Scooter
259304          1614634848015545    0.001917  Circular Scooter
259305          1614634848019554    0.001936  Circular Scooter
...                          ...         ...               ...
274264          1614634907980217    0.001849  Circular Scooter
274265          1614634907984225    0.001862  Circular Scooter
274266          1614634907988233    0.001874  Circular Scooter
274267          1614634907992241    0.001856  Circular Scooter
274268          1614634907996250    0.001849  Circular Scooter

[14968 rows x 3 columns]

In [13]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=43, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=44, second=45)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-13-d5a9abd75cb5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

        Timestamp (microseconds)  Sample (V) Activity_Label
303460          1614635025003870    0.001886   Cycling Slow
303461          1614635025007878    0.001893   Cycling Slow
303462          1614635025011886    0.001893   Cycling Slow
303463          1614635025015895    0.001880   Cycling Slow
303464          1614635025019903    0.001874   Cycling Slow
...                          ...         ...            ...
318424          1614635084982463    0.001948   Cycling Slow
318425          1614635084986472    0.001948   Cycling Slow
318426          1614635084990480    0.001954   Cycling Slow
318427          1614635084994488    0.001948   Cycling Slow
318428          1614635084998497    0.001954   Cycling Slow

[14969 rows x 3 columns]

In [14]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=44, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=45, second=47)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-14-8fcf22320788>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

        Timestamp (microseconds)  Sample (V) Activity_Label
318678          1614635086000482    0.001973   Cycling Fast
318679          1614635086004490    0.001960   Cycling Fast
318680          1614635086008499    0.001966   Cycling Fast
318681          1614635086012507    0.001960   Cycling Fast
318682          1614635086016515    0.001960   Cycling Fast
...                          ...         ...            ...
333893          1614635146980351    0.001474   Cycling Fast
333894          1614635146984358    0.001560   Cycling Fast
333895          1614635146988366    0.001714   Cycling Fast
333896          1614635146992374    0.001874   Cycling Fast
333897          1614635146996382    0.001991   Cycling Fast

[15220 rows x 3 columns]

In [15]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=51, second=38)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=52, second=38)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-15-8df243a5d488>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
421469          1614635498000522    0.001849  Medicine_ball
421470          1614635498004531    0.001843  Medicine_ball
421471          1614635498008539    0.001843  Medicine_ball
421472          1614635498012548    0.001849  Medicine_ball
421473          1614635498016557    0.001856  Medicine_ball
...                          ...         ...            ...
436433          1614635557982983    0.001646  Medicine_ball
436434          1614635557986992    0.001640  Medicine_ball
436435          1614635557991000    0.001609  Medicine_ball
436436          1614635557995008    0.001628  Medicine_ball
436437          1614635557999016    0.001659  Medicine_ball

[14969 rows x 3 columns]

In [16]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=54, second=44)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=55, second=44)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-16-8be34a03a87a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

        Timestamp (microseconds)  Sample (V)              Activity_Label
467874          1614635684002300    0.002071  Medicine ball with burpies
467875          1614635684006308    0.002200  Medicine ball with burpies
467876          1614635684010316    0.002206  Medicine ball with burpies
467877          1614635684014325    0.002053  Medicine ball with burpies
467878          1614635684018333    0.001966  Medicine ball with burpies
...                          ...         ...                         ...
482839          1614635743980526    0.001782  Medicine ball with burpies
482840          1614635743984534    0.001788  Medicine ball with burpies
482841          1614635743988542    0.001782  Medicine ball with burpies
482842          1614635743992550    0.001782  Medicine ball with burpies
482843          1614635743996557    0.001800  Medicine ball with burpies

[14970 rows x 3 columns]

In [17]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=59, second=23)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=0, second=23)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-17-25756dd2fa72>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
537483          1614635963001132    0.002022     punch ball
537484          1614635963005140    0.001905     punch ball
537485          1614635963009148    0.001776     punch ball
537486          1614635963013157    0.001720     punch ball
537487          1614635963017165    0.001726     punch ball
...                          ...         ...            ...
552448          1614636022983429    0.002114     punch ball
552449          1614636022987437    0.002120     punch ball
552450          1614636022991445    0.002139     punch ball
552451          1614636022995453    0.002163     punch ball
552452          1614636022999462    0.002157     punch ball

[14970 rows x 3 columns]

In [18]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=1, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=2, second=53)
end_ts=int(end.timestamp() * 1e6)

DF13= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-18-342a22046a2f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

        Timestamp (microseconds)  Sample (V)   Activity_Label
574908          1614636113000593    0.001954  Squarts Toe ups
574909          1614636113004601    0.001954  Squarts Toe ups
574910          1614636113008608    0.001936  Squarts Toe ups
574911          1614636113012616    0.001936  Squarts Toe ups
574912          1614636113016624    0.001954  Squarts Toe ups
...                          ...         ...              ...
589874          1614636172981210    0.001874  Squarts Toe ups
589875          1614636172985218    0.001893  Squarts Toe ups
589876          1614636172989226    0.001880  Squarts Toe ups
589877          1614636172993234    0.001862  Squarts Toe ups
589878          1614636172997242    0.001849  Squarts Toe ups

[14971 rows x 3 columns]

In [19]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=4, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=5, second=14)
end_ts=int(end.timestamp() * 1e6)

DF14= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-19-efed7ad5654b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

        Timestamp (microseconds)  Sample (V) Activity_Label
610090          1614636254000626    0.001776   Weight lifts
610091          1614636254004634    0.001782   Weight lifts
610092          1614636254008642    0.001794   Weight lifts
610093          1614636254012650    0.001794   Weight lifts
610094          1614636254016657    0.001794   Weight lifts
...                          ...         ...            ...
625057          1614636313980985    0.001973   Weight lifts
625058          1614636313984993    0.001954   Weight lifts
625059          1614636313989000    0.001979   Weight lifts
625060          1614636313993007    0.001997   Weight lifts
625061          1614636313997015    0.002009   Weight lifts

[14972 rows x 3 columns]

In [20]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=7, second=9)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=8, second=9)
end_ts=int(end.timestamp() * 1e6)

DF15= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-20-4d5f32b10006>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

        Timestamp (microseconds)  Sample (V)      Activity_Label
653758          1614636429002011    0.001714  Heavy Weight lifts
653759          1614636429006019    0.001714  Heavy Weight lifts
653760          1614636429010027    0.001696  Heavy Weight lifts
653761          1614636429014034    0.001708  Heavy Weight lifts
653762          1614636429018042    0.001732  Heavy Weight lifts
...                          ...         ...                 ...
668725          1614636488982587    0.001825  Heavy Weight lifts
668726          1614636488986595    0.001831  Heavy Weight lifts
668727          1614636488990602    0.001831  Heavy Weight lifts
668728          1614636488994609    0.001812  Heavy Weight lifts
668729          1614636488998617    0.001776  Heavy Weight lifts

[14972 rows x 3 columns]

In [21]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=14, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=15, second=55)
end_ts=int(end.timestamp() * 1e6)

DF16= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-21-d6b23d4b248d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

        Timestamp (microseconds)  Sample (V)          Activity_Label
770042          1614636895002754    0.001862  Forward Lunges on Bosu
770043          1614636895006761    0.001862  Forward Lunges on Bosu
770044          1614636895010769    0.001862  Forward Lunges on Bosu
770045          1614636895014776    0.001856  Forward Lunges on Bosu
770046          1614636895018783    0.001862  Forward Lunges on Bosu
...                          ...         ...                     ...
785010          1614636954983745    0.002428  Forward Lunges on Bosu
785011          1614636954987753    0.002422  Forward Lunges on Bosu
785012          1614636954991760    0.002403  Forward Lunges on Bosu
785013          1614636954995767    0.002403  Forward Lunges on Bosu
785014          1614636954999775    0.002391  Forward Lunges on Bosu

[14973 rows x 3 columns]

In [22]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=16, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=17, second=55)
end_ts=int(end.timestamp() * 1e6)

DF17= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-22-6adae08cd25e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
799988          1614637015003528    0.001831  Split squart left on Bosu
799989          1614637015007536    0.001825  Split squart left on Bosu
799990          1614637015011543    0.001800  Split squart left on Bosu
799991          1614637015015550    0.001794  Split squart left on Bosu
799992          1614637015019558    0.001794  Split squart left on Bosu
...                          ...         ...                        ...
814955          1614637074980486    0.002139  Split squart left on Bosu
814956          1614637074984493    0.002133  Split squart left on Bosu
814957          1614637074988500    0.002133  Split squart left on Bosu
814958          1614637074992508    0.002126  Split squart left on Bosu
814959          1614637074996515    0.002120  Split squart left on Bosu

[14972 rows x 3 columns]

In [23]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=19, second=21)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=20, second=21)
end_ts=int(end.timestamp() * 1e6)

DF18= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-23-e19844cdc036>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

        Timestamp (microseconds)  Sample (V)              Activity_Label
836421          1614637161001058    0.001794  Split squart right on Bosu
836422          1614637161005066    0.001794  Split squart right on Bosu
836423          1614637161009073    0.001788  Split squart right on Bosu
836424          1614637161013080    0.001782  Split squart right on Bosu
836425          1614637161017088    0.001776  Split squart right on Bosu
...                          ...         ...                         ...
851389          1614637220982416    0.001585  Split squart right on Bosu
851390          1614637220986423    0.001579  Split squart right on Bosu
851391          1614637220990430    0.001579  Split squart right on Bosu
851392          1614637220994438    0.001572  Split squart right on Bosu
851393          1614637220998445    0.001572  Split squart right on Bosu

[14973 rows x 3 columns]

In [24]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=23, second=9)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=24, second=9)
end_ts=int(end.timestamp() * 1e6)

DF19= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-24-684b72347a9e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
893314          1614637389000819    0.001726  plank pie on Bosu
893315          1614637389004827    0.001788  plank pie on Bosu
893316          1614637389008834    0.001812  plank pie on Bosu
893317          1614637389012842    0.001800  plank pie on Bosu
893318          1614637389016850    0.001751  plank pie on Bosu
...                          ...         ...                ...
908280          1614637448981956    0.001862  plank pie on Bosu
908281          1614637448985964    0.001856  plank pie on Bosu
908282          1614637448989972    0.001837  plank pie on Bosu
908283          1614637448993980    0.001825  plank pie on Bosu
908284          1614637448997987    0.001825  plank pie on Bosu

[14971 rows x 3 columns]

In [25]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=25, second=24)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=26, second=24)
end_ts=int(end.timestamp() * 1e6)

DF20= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-25-852bfb15d311>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
926999          1614637524000064    0.001806  plank top on Bosu
927000          1614637524004072    0.001812  plank top on Bosu
927001          1614637524008080    0.001806  plank top on Bosu
927002          1614637524012087    0.001812  plank top on Bosu
927003          1614637524016095    0.001806  plank top on Bosu
...                          ...         ...                ...
941966          1614637583982217    0.001652  plank top on Bosu
941967          1614637583986225    0.001683  plank top on Bosu
941968          1614637583990233    0.001776  plank top on Bosu
941969          1614637583994241    0.001843  plank top on Bosu
941970          1614637583998249    0.001868  plank top on Bosu

[14972 rows x 3 columns]

In [26]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=27, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=28, second=35)
end_ts=int(end.timestamp() * 1e6)

DF21= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-26-cb68e292d666>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

        Timestamp (microseconds)  Sample (V) Activity_Label
959687          1614637655001052    0.001308   dips on Bosu
959688          1614637655005060    0.001357   dips on Bosu
959689          1614637655009068    0.001443   dips on Bosu
959690          1614637655013075    0.001566   dips on Bosu
959691          1614637655017083    0.001665   dips on Bosu
...                          ...         ...            ...
974653          1614637714980297    0.002317   dips on Bosu
974654          1614637714984305    0.002323   dips on Bosu
974655          1614637714988313    0.002311   dips on Bosu
974656          1614637714992321    0.002305   dips on Bosu
974657          1614637714996328    0.002305   dips on Bosu

[14971 rows x 3 columns]

In [27]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=33, second=32)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=34, second=32)
end_ts=int(end.timestamp() * 1e6)

DF22= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-27-1227f9f501be>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

         Timestamp (microseconds)  Sample (V)                Activity_Label
1048764          1614638012003786    0.002053  moveforward backward on Bosu
1048765          1614638012007794    0.002059  moveforward backward on Bosu
1048766          1614638012011801    0.002077  moveforward backward on Bosu
1048767          1614638012015809    0.002077  moveforward backward on Bosu
1048768          1614638012019817    0.002096  moveforward backward on Bosu
...                           ...         ...                           ...
1063730          1614638071982603    0.001363  moveforward backward on Bosu
1063731          1614638071986611    0.001400  moveforward backward on Bosu
1063732          1614638071990618    0.001449  moveforward backward on Bosu
1063733          1614638071994626    0.001523  moveforward backward on Bosu
1063734          1614638071998634    0.001634  moveforward backward on Bosu

[14971 rows x 3 columns]

In [28]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=37, second=34)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=38, second=34)
end_ts=int(end.timestamp() * 1e6)

DF23= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-28-7fff4b8f5380>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

         Timestamp (microseconds)  Sample (V)            Activity_Label
1109149          1614638254001721    0.002526  Left leg Hip ups on Bosu
1109150          1614638254005729    0.002520  Left leg Hip ups on Bosu
1109151          1614638254009737    0.002526  Left leg Hip ups on Bosu
1109152          1614638254013745    0.002533  Left leg Hip ups on Bosu
1109153          1614638254017753    0.002539  Left leg Hip ups on Bosu
...                           ...         ...                       ...
1124116          1614638313983326    0.001659  Left leg Hip ups on Bosu
1124117          1614638313987333    0.001652  Left leg Hip ups on Bosu
1124118          1614638313991341    0.001665  Left leg Hip ups on Bosu
1124119          1614638313995349    0.001659  Left leg Hip ups on Bosu
1124120          1614638313999357    0.001665  Left leg Hip ups on Bosu

[14972 rows x 3 columns]

In [29]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=38, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=39, second=37)
end_ts=int(end.timestamp() * 1e6)

DF24= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-29-4d5cadf793a1>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

         Timestamp (microseconds)  Sample (V)             Activity_Label
1124869          1614638317001114    0.001880  right leg Hip ups on Bosu
1124870          1614638317005122    0.001899  right leg Hip ups on Bosu
1124871          1614638317009130    0.001917  right leg Hip ups on Bosu
1124872          1614638317013137    0.001948  right leg Hip ups on Bosu
1124873          1614638317017145    0.001979  right leg Hip ups on Bosu
...                           ...         ...                        ...
1139835          1614638376981885    0.001702  right leg Hip ups on Bosu
1139836          1614638376985893    0.001714  right leg Hip ups on Bosu
1139837          1614638376989901    0.001720  right leg Hip ups on Bosu
1139838          1614638376993909    0.001720  right leg Hip ups on Bosu
1139839          1614638376997916    0.001708  right leg Hip ups on Bosu

[14971 rows x 3 columns]

In [30]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=41, second=15)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=42, second=15)
end_ts=int(end.timestamp() * 1e6)

DF25= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-30-a540218100cb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

         Timestamp (microseconds)  Sample (V)         Activity_Label
1164292          1614638475002963    0.001572  V-Shift Swift on Bosu
1164293          1614638475006971    0.001572  V-Shift Swift on Bosu
1164294          1614638475010978    0.001579  V-Shift Swift on Bosu
1164295          1614638475014986    0.001585  V-Shift Swift on Bosu
1164296          1614638475018994    0.001572  V-Shift Swift on Bosu
...                           ...         ...                    ...
1179258          1614638534981871    0.002089  V-Shift Swift on Bosu
1179259          1614638534985879    0.002096  V-Shift Swift on Bosu
1179260          1614638534989887    0.002089  V-Shift Swift on Bosu
1179261          1614638534993895    0.002083  V-Shift Swift on Bosu
1179262          1614638534997902    0.002077  V-Shift Swift on Bosu

[14971 rows x 3 columns]

In [31]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=46, second=32)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=47, second=2)
end_ts=int(end.timestamp() * 1e6)

DF26= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-31-916a4eaa5c39>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

         Timestamp (microseconds)  Sample (V)    Activity_Label
1243391          1614638792000269    0.001923  Freestyle Boxing
1243392          1614638792004276    0.001893  Freestyle Boxing
1243393          1614638792008283    0.001862  Freestyle Boxing
1243394          1614638792012291    0.001819  Freestyle Boxing
1243395          1614638792016298    0.001812  Freestyle Boxing
...                           ...         ...               ...
1250873          1614638821983923    0.002213  Freestyle Boxing
1250874          1614638821987930    0.002200  Freestyle Boxing
1250875          1614638821991937    0.002114  Freestyle Boxing
1250876          1614638821995945    0.001997  Freestyle Boxing
1250877          1614638821999952    0.001868  Freestyle Boxing

[7487 rows x 3 columns]

In [32]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=47, second=16)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=47, second=46)
end_ts=int(end.timestamp() * 1e6)

DF27= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-32-92c4cac6bc70>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

         Timestamp (microseconds)  Sample (V)           Activity_Label
1254371          1614638836001428    0.002668  Left_Right_Punches_flip
1254372          1614638836005436    0.002674  Left_Right_Punches_flip
1254373          1614638836009443    0.002686  Left_Right_Punches_flip
1254374          1614638836013450    0.002680  Left_Right_Punches_flip
1254375          1614638836017458    0.002680  Left_Right_Punches_flip
...                           ...         ...                      ...
1261853          1614638865983526    0.002569  Left_Right_Punches_flip
1261854          1614638865987533    0.002686  Left_Right_Punches_flip
1261855          1614638865991541    0.002853  Left_Right_Punches_flip
1261856          1614638865995548    0.002982  Left_Right_Punches_flip
1261857          1614638865999555    0.003043  Left_Right_Punches_flip

[7487 rows x 3 columns]

In [33]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=48, second=26)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=48, second=56)
end_ts=int(end.timestamp() * 1e6)

DF28= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-33-d75b5df38f45>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

         Timestamp (microseconds)  Sample (V)    Activity_Label
1271840          1614638906002594    0.002773  left_Right_Punch
1271841          1614638906006601    0.002871  left_Right_Punch
1271842          1614638906010608    0.002920  left_Right_Punch
1271843          1614638906014616    0.002890  left_Right_Punch
1271844          1614638906018623    0.002840  left_Right_Punch
...                           ...         ...               ...
1279322          1614638935983623    0.002409  left_Right_Punch
1279323          1614638935987630    0.002397  left_Right_Punch
1279324          1614638935991638    0.002336  left_Right_Punch
1279325          1614638935995645    0.002286  left_Right_Punch
1279326          1614638935999652    0.002280  left_Right_Punch

[7487 rows x 3 columns]

In [34]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=49, second=31)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=50, second=1)
end_ts=int(end.timestamp() * 1e6)

DF29= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-34-3d7f9acec8fc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

         Timestamp (microseconds)  Sample (V) Activity_Label
1288061          1614638971000633    0.001511       one_twos
1288062          1614638971004640    0.001529       one_twos
1288063          1614638971008647    0.001536       one_twos
1288064          1614638971012654    0.001554       one_twos
1288065          1614638971016661    0.001585       one_twos
...                           ...         ...            ...
1295543          1614639000980542    0.003702       one_twos
1295544          1614639000984549    0.003653       one_twos
1295545          1614639000988556    0.003622       one_twos
1295546          1614639000992563    0.003603       one_twos
1295547          1614639000996570    0.003610       one_twos

[7487 rows x 3 columns]

In [35]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=56, second=22)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=56, second=52)
end_ts=int(end.timestamp() * 1e6)

DF30= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-35-22e49b85a5da>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

         Timestamp (microseconds)  Sample (V) Activity_Label
1390630          1614639382002292    0.001886          hooks
1390631          1614639382006300    0.002022          hooks
1390632          1614639382010307    0.001905          hooks
1390633          1614639382014314    0.001671          hooks
1390634          1614639382018322    0.001714          hooks
...                           ...         ...            ...
1398111          1614639411980142    0.002237          hooks
1398112          1614639411984150    0.002243          hooks
1398113          1614639411988157    0.002182          hooks
1398114          1614639411992164    0.002040          hooks
1398115          1614639411996172    0.001831          hooks

[7486 rows x 3 columns]

In [36]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=57, second=36)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=58, second=6)
end_ts=int(end.timestamp() * 1e6)

DF31= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-36-de95453b069c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

         Timestamp (microseconds)  Sample (V) Activity_Label
1409097          1614639456002203    0.001929     Upper_cuts
1409098          1614639456006210    0.001929     Upper_cuts
1409099          1614639456010217    0.001936     Upper_cuts
1409100          1614639456014221    0.001929     Upper_cuts
1409101          1614639456018228    0.001923     Upper_cuts
...                           ...         ...            ...
1416579          1614639485983476    0.002083     Upper_cuts
1416580          1614639485987484    0.002096     Upper_cuts
1416581          1614639485991491    0.002108     Upper_cuts
1416582          1614639485995498    0.002114     Upper_cuts
1416583          1614639485999506    0.002114     Upper_cuts

[7487 rows x 3 columns]

In [37]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=58, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=59, second=21)
end_ts=int(end.timestamp() * 1e6)

DF32= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-37-7bf0b3c45ee8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

         Timestamp (microseconds)  Sample (V) Activity_Label
1427814          1614639531003051    0.001591            run
1427815          1614639531007059    0.001597            run
1427816          1614639531011066    0.001603            run
1427817          1614639531015073    0.001616            run
1427818          1614639531019081    0.001628            run
...                           ...         ...            ...
1435296          1614639560983646    0.001634            run
1435297          1614639560987653    0.001628            run
1435298          1614639560991660    0.001622            run
1435299          1614639560995667    0.001640            run
1435300          1614639560999673    0.001652            run

[7487 rows x 3 columns]

In [38]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=0, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=1, second=25)
end_ts=int(end.timestamp() * 1e6)

DF33= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-38-4d2dd6dd4003>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

         Timestamp (microseconds)  Sample (V)       Activity_Label
1458760          1614639655001793    0.002003  Punch_down_Up_Hooks
1458761          1614639655005800    0.001788  Punch_down_Up_Hooks
1458762          1614639655009807    0.001548  Punch_down_Up_Hooks
1458763          1614639655013814    0.001320  Punch_down_Up_Hooks
1458764          1614639655017821    0.001185  Punch_down_Up_Hooks
...                           ...         ...                  ...
1466242          1614639684981923    0.000514  Punch_down_Up_Hooks
1466243          1614639684985930    0.000489  Punch_down_Up_Hooks
1466244          1614639684989936    0.000483  Punch_down_Up_Hooks
1466245          1614639684993943    0.000471  Punch_down_Up_Hooks
1466246          1614639684997950    0.000465  Punch_down_Up_Hooks

[7487 rows x 3 columns]

In [41]:
sub04_final_chest_elec=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub04_final_chest_elec

        Timestamp (microseconds)  Sample (V)             Activity_Label
0               1614633910003668    0.001831  Forward and backward step
1               1614633910007676    0.001831  Forward and backward step
2               1614633910011684    0.001837  Forward and backward step
3               1614633910015691    0.001831  Forward and backward step
4               1614633910019699    0.001831  Forward and backward step
...                          ...         ...                        ...
733789          1614639684981923    0.000514        Punch_down_Up_Hooks
733790          1614639684985930    0.000489        Punch_down_Up_Hooks
733791          1614639684989936    0.000483        Punch_down_Up_Hooks
733792          1614639684993943    0.000471        Punch_down_Up_Hooks
733793          1614639684997950    0.000465        Punch_down_Up_Hooks

[733794 rows x 3 columns]

In [42]:
sub04_final_chest_elec.to_csv('final_cleaned_chest_elec-sub04.csv-sub04')