In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('hand_gyro.csv-sub04')

In [3]:
df1

        Timestamp (microseconds)  Gyro X (°/s)  Gyro Y (°/s)  Gyro Z (°/s)
0               1614633802283294    159.029526    -86.457618    122.285801
1               1614633802299294    144.625010    -81.330587    103.486687
2               1614633802315294    108.857862    -73.640040     75.959411
3               1614633802331294     77.241169    -65.094987     38.971542
4               1614633802347293     55.268177    -53.620203      2.044709
...                          ...           ...           ...           ...
378555          1614639858978028     -0.518807      0.274662      0.640879
378556          1614639858994026     -0.579843      0.274662      0.701915
378557          1614639859010023     -0.640879      0.274662      0.640879
378558          1614639859026021     -0.640879      0.335698      0.701915
378559          1614639859042018     -0.579843      0.274662      0.701915

[378560 rows x 4 columns]

In [4]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-01 21:23:22.283294')

In [5]:
start = pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=25, second=10)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=26, second=10)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

<ipython-input-5-3d38c8629409>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
6733,1614633910007185,3.265431,-17.730983,-142.854963,Forward and backward step
6734,1614633910023184,-5.218585,-19.806210,-134.981308,Forward and backward step
6735,1614633910039184,-12.848096,-19.989319,-131.136034,Forward and backward step
6736,1614633910055183,-22.980087,-19.928283,-130.647745,Forward and backward step
6737,1614633910071182,-30.670634,-23.956664,-131.074998,Forward and backward step
...,...,...,...,...,...
10478,1614633969924492,27.557794,-94.636454,4.608225,Forward and backward step
10479,1614633969940492,3.753719,-100.129702,-8.148318,Forward and backward step
10480,1614633969956512,-16.510262,-104.341192,-18.951705,Forward and backward step
10481,1614633969972511,-30.060273,-104.219120,-22.796979,Forward and backward step
10482,1614633969988511,-39.703975,-99.275196,-21.881437,Forward and backward step

In [6]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=27, second=30)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=28, second=30)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

<ipython-input-6-52059c829f89>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
15483,1614634050000634,20.538643,-5.645838,14.496071,Sideward step
15484,1614634050016634,16.449226,-3.570611,15.106432,Sideward step
15485,1614634050032633,16.083009,-1.922637,16.510262,Sideward step
15486,1614634050048632,17.242695,-0.396735,18.158236,Sideward step
15487,1614634050064632,19.989319,1.373312,18.646525,Sideward step
...,...,...,...,...,...
19229,1614634109933727,-85.969329,34.821088,24.078737,Sideward step
19230,1614634109949727,-81.391623,37.628748,19.562066,Sideward step
19231,1614634109965726,-73.212787,38.910506,12.115663,Sideward step
19232,1614634109981725,-65.278096,40.375372,1.983673,Sideward step
19233,1614634109997725,-62.348363,43.305104,-9.002823,Sideward step

In [7]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=30, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=31, second=46)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

<ipython-input-7-f8e0ccbe6746>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
27734,1614634246007712,10.589761,60.822461,67.902647,Pushups
27735,1614634246023711,7.476921,60.273136,58.503090,Pushups
27736,1614634246039711,-1.312276,60.761425,48.920424,Pushups
27737,1614634246055710,-11.505303,65.644312,46.295872,Pushups
27738,1614634246071709,-16.632334,71.931029,47.516594,Pushups
...,...,...,...,...,...
31479,1614634305925264,22.919051,19.867247,-5.401694,Pushups
31480,1614634305941253,25.299458,23.224231,-6.195163,Pushups
31481,1614634305957253,27.130541,25.848783,-7.476921,Pushups
31482,1614634305973252,31.158923,28.290227,-8.087282,Pushups
31483,1614634305989251,29.633021,29.144732,-13.092241,Pushups

In [8]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=32, second=59)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=33, second=59)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

<ipython-input-8-1a263aaffc52>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
36047,1614634379010341,-11.261158,-13.580529,41.168841,Hip raise step with punches in the air
36048,1614634379026340,-14.068818,-14.007782,40.863661,Hip raise step with punches in the air
36049,1614634379042339,-13.763638,-13.458457,41.107805,Hip raise step with punches in the air
36050,1614634379058339,-12.909133,-11.627375,41.046769,Hip raise step with punches in the air
36051,1614634379074338,-9.430076,-9.308003,39.703975,Hip raise step with punches in the air
...,...,...,...,...,...
39792,1614634438928136,0.335698,16.815442,25.665675,Hip raise step with punches in the air
39793,1614634438944136,1.922637,18.341344,26.215000,Hip raise step with punches in the air
39794,1614634438960135,3.570611,19.562066,25.665675,Hip raise step with punches in the air
39795,1614634438976134,4.486152,20.782788,25.726711,Hip raise step with punches in the air
39796,1614634438992134,4.730297,22.369726,24.750134,Hip raise step with punches in the air

In [9]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=35, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=56, second=57)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

<ipython-input-9-fe9bf6b8c53a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
47172,1614634557004955,-23.041123,-32.257572,-11.261158,Front and back scooter
47173,1614634557020955,-27.801938,-21.393149,-6.683452,Front and back scooter
47174,1614634557036955,-26.581216,-13.275349,-4.119936,Front and back scooter
47175,1614634557052954,-20.294499,-9.613184,-3.143359,Front and back scooter
47176,1614634557068954,-14.435035,-6.927596,-5.523766,Front and back scooter
...,...,...,...,...,...
125919,1614635816922221,-0.335698,0.946059,0.823987,Front and back scooter
125920,1614635816938263,-0.274662,0.823987,0.885023,Front and back scooter
125921,1614635816954262,-0.091554,0.762951,0.946059,Front and back scooter
125922,1614635816970262,-0.152590,0.762951,1.007095,Front and back scooter
125923,1614635816986262,-0.213626,0.823987,1.251240,Front and back scooter

In [10]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=38, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=39, second=14)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

<ipython-input-10-2faf8a20483c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
55735,1614634694010687,21.149004,22.003510,-1.922637,Belly Scooter
55736,1614634694026687,18.158236,17.975128,-8.453498,Belly Scooter
55737,1614634694042687,24.750134,9.979400,-14.251926,Belly Scooter
55738,1614634694058687,29.694057,9.002823,-12.970169,Belly Scooter
55739,1614634694074687,31.158923,11.444266,-8.270390,Belly Scooter
...,...,...,...,...,...
59480,1614634753930267,-12.848096,-31.158923,20.599680,Belly Scooter
59481,1614634753946267,-3.082322,-34.027619,25.665675,Belly Scooter
59482,1614634753962267,6.500343,-33.539330,31.219959,Belly Scooter
59483,1614634753978266,13.275349,-30.792706,31.219959,Belly Scooter
59484,1614634753994266,8.941787,-26.581216,24.505989,Belly Scooter

In [11]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=40, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=41, second=48)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

<ipython-input-11-60737e03973e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
65360,1614634848009613,-3.692683,3.204395,-1.678492,Circular Scooter
65361,1614634848025612,-2.288853,3.570611,-1.434348,Circular Scooter
65362,1614634848041612,-0.762951,3.692683,-0.701915,Circular Scooter
65363,1614634848057612,-0.518807,3.814755,-0.396735,Circular Scooter
65364,1614634848073612,-1.373312,3.448539,0.091554,Circular Scooter
...,...,...,...,...,...
69105,1614634907929120,71.137560,-50.995651,-11.078050,Circular Scooter
69106,1614634907945119,84.809644,-104.707408,16.266117,Circular Scooter
69107,1614634907961119,91.767758,-161.654078,42.267491,Circular Scooter
69108,1614634907977119,100.617990,-219.943542,63.630121,Circular Scooter
69109,1614634907993119,102.021820,-286.533913,102.998398,Circular Scooter

In [12]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=43, second=45)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=44, second=45)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

<ipython-input-12-d5a9abd75cb5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
76423,1614635025015803,50.202182,10.406653,33.173114,Cycling Slow
76424,1614635025031803,75.165942,13.519493,42.572671,Cycling Slow
76425,1614635025047803,90.547036,15.716793,46.662089,Cycling Slow
76426,1614635025063802,102.571145,19.012741,46.540017,Cycling Slow
76427,1614635025079802,104.097047,28.229191,46.662089,Cycling Slow
...,...,...,...,...,...
80168,1614635084934761,-13.092241,3.143359,2.777142,Cycling Slow
80169,1614635084950760,-12.848096,3.143359,8.209354,Cycling Slow
80170,1614635084966760,-11.200122,2.777142,12.664988,Cycling Slow
80171,1614635084982760,-10.772869,2.166781,16.205081,Cycling Slow
80172,1614635084998760,-10.040436,0.640879,19.439994,Cycling Slow

In [13]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=44, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=45, second=47)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

<ipython-input-13-8fcf22320788>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
80235,1614635086006751,-37.872892,-9.796292,-18.829633,Cycling Fast
80236,1614635086022750,-31.891356,-6.500343,-3.021286,Cycling Fast
80237,1614635086038750,-29.388876,-3.326467,11.139086,Cycling Fast
80238,1614635086054750,-27.862974,1.556420,20.294499,Cycling Fast
80239,1614635086070750,-24.505989,2.716106,26.031891,Cycling Fast
...,...,...,...,...,...
84043,1614635146932672,-48.310063,42.999924,24.444953,Cycling Fast
84044,1614635146948671,-43.121996,32.318608,22.369726,Cycling Fast
84045,1614635146964670,-37.079423,17.608911,21.759365,Cycling Fast
84046,1614635146980670,-30.487526,-3.326467,22.247654,Cycling Fast
84047,1614635146996669,-27.374685,-28.778515,21.149004,Cycling Fast

In [14]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=51, second=38)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=52, second=38)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

<ipython-input-14-8df243a5d488>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
105986,1614635498007497,-17.914092,-2.777142,-0.457771,Medicine_ball
105987,1614635498023497,-17.914092,-3.387503,-0.152590,Medicine_ball
105988,1614635498039497,-13.153277,-3.936828,0.091554,Medicine_ball
105989,1614635498055497,-7.721065,-3.936828,-0.213626,Medicine_ball
105990,1614635498071497,-4.119936,-3.082322,-0.396735,Medicine_ball
...,...,...,...,...,...
109731,1614635557925412,-136.629282,172.518502,84.321355,Medicine_ball
109732,1614635557941412,-144.136721,160.738537,77.546349,Medicine_ball
109733,1614635557957411,-151.400015,147.737850,71.869993,Medicine_ball
109734,1614635557973410,-150.789654,131.502251,72.419318,Medicine_ball
109735,1614635557989410,-146.334020,113.313497,77.912566,Medicine_ball

In [15]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=54, second=44)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=55, second=44)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

<ipython-input-15-8be34a03a87a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
117612,1614635684015997,115.999084,-92.805371,-17.242695,Medicine ball with burpies
117613,1614635684031996,140.108339,-105.683986,-14.557107,Medicine ball with burpies
117614,1614635684047995,160.677501,-120.637827,-16.754406,Medicine ball with burpies
117615,1614635684063995,174.105440,-132.478828,-23.407340,Medicine ball with burpies
117616,1614635684079994,169.222553,-135.286488,-30.365454,Medicine ball with burpies
...,...,...,...,...,...
121357,1614635743933182,180.880446,-40.192264,43.976501,Medicine ball with burpies
121358,1614635743949181,234.103914,-14.740215,66.437781,Medicine ball with burpies
121359,1614635743965180,291.783017,-8.392462,84.199283,Medicine ball with burpies
121360,1614635743981170,305.149920,-35.065232,72.480354,Medicine ball with burpies
121361,1614635743997170,267.917906,-90.547036,103.303578,Medicine ball with burpies

In [16]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=21, minute=59, second=23)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=0, second=23)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

<ipython-input-16-25756dd2fa72>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
135049,1614635963002309,-51.178759,84.626535,34.393835,punch ball
135050,1614635963018309,-54.047456,84.809644,27.740902,punch ball
135051,1614635963034309,-64.911879,81.513695,21.515221,punch ball
135052,1614635963050310,-69.977874,75.654231,16.021973,punch ball
135053,1614635963066310,-71.564813,73.151751,8.209354,punch ball
...,...,...,...,...,...
138794,1614636022920859,65.156023,86.335546,-10.772869,punch ball
138795,1614636022936858,-32.135500,77.912566,-69.306477,punch ball
138796,1614636022952858,-66.010529,72.541390,-29.388876,punch ball
138797,1614636022968857,-34.454871,45.380331,-27.374685,punch ball
138798,1614636022984856,22.003510,2.655070,-35.675593,punch ball

In [17]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=1, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=2, second=53)
end_ts=int(end.timestamp() * 1e6)

DF13= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

<ipython-input-17-342a22046a2f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
144425,1614636113012491,-34.271763,36.591135,-6.378271,Squarts Toe ups
144426,1614636113028491,-44.159609,42.145418,-7.049668,Squarts Toe ups
144427,1614636113044490,-48.126955,46.295872,-7.537957,Squarts Toe ups
144428,1614636113060489,-46.234836,48.065919,-7.721065,Squarts Toe ups
144429,1614636113076489,-36.041810,50.080110,-5.645838,Squarts Toe ups
...,...,...,...,...,...
148170,1614636172929646,16.815442,-26.947433,-17.853056,Squarts Toe ups
148171,1614636172945645,25.055314,-26.764324,-17.303731,Squarts Toe ups
148172,1614636172961645,22.491798,-25.604639,-16.021973,Squarts Toe ups
148173,1614636172977644,8.514534,-25.970855,-12.603952,Squarts Toe ups
148174,1614636172993643,-3.509575,-25.909819,-9.369039,Squarts Toe ups

In [18]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=4, second=14)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=5, second=14)
end_ts=int(end.timestamp() * 1e6)

DF14= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

<ipython-input-18-efed7ad5654b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
153238,1614636254014306,22.003510,-96.650645,-50.507362,Weight lifts
153239,1614636254030305,24.078737,-88.044556,-48.920424,Weight lifts
153240,1614636254046295,22.064546,-80.903334,-49.530785,Weight lifts
153241,1614636254062294,19.745174,-73.762112,-45.868620,Weight lifts
153242,1614636254078293,19.867247,-67.109178,-43.793393,Weight lifts
...,...,...,...,...,...
156983,1614636313932061,-88.410773,82.307164,29.205768,Weight lifts
156984,1614636313948061,-64.545663,87.434195,26.886397,Weight lifts
156985,1614636313964060,-61.921111,88.105592,25.482567,Weight lifts
156986,1614636313980059,-51.972229,93.171588,29.205768,Weight lifts
156987,1614636313996059,-59.479667,104.951553,36.224918,Weight lifts

In [19]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=7, second=9)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=8, second=9)
end_ts=int(end.timestamp() * 1e6)

DF15= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

<ipython-input-19-4d5f32b10006>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
164175,1614636429001326,-20.294499,-18.890669,-9.308003,Heavy Weight lifts
164176,1614636429017326,-6.256199,-21.942473,-10.223545,Heavy Weight lifts
164177,1614636429033326,7.660029,-24.383917,-11.322194,Heavy Weight lifts
164178,1614636429049327,10.040436,-24.505989,-11.505303,Heavy Weight lifts
164179,1614636429065327,7.110704,-24.750134,-10.955978,Heavy Weight lifts
...,...,...,...,...,...
167920,1614636488920929,44.892042,169.100481,122.835126,Heavy Weight lifts
167921,1614636488936928,51.300832,171.786069,130.647745,Heavy Weight lifts
167922,1614636488952928,54.291600,178.683146,136.385138,Heavy Weight lifts
167923,1614636488968928,52.155337,183.260853,141.329061,Heavy Weight lifts
167924,1614636488984928,50.934615,189.547570,145.174334,Heavy Weight lifts

In [20]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=14, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=15, second=55)
end_ts=int(end.timestamp() * 1e6)

DF16= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

<ipython-input-20-d6b23d4b248d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
193301,1614636895008767,-11.322194,-7.354849,-36.224918,Forward Lunges on Bosu
193302,1614636895024767,-15.106432,-5.157549,-34.821088,Forward Lunges on Bosu
193303,1614636895040766,-19.623102,-2.166781,-33.356222,Forward Lunges on Bosu
193304,1614636895056766,-22.613870,0.640879,-31.891356,Forward Lunges on Bosu
193305,1614636895072766,-25.116350,3.326467,-30.121309,Forward Lunges on Bosu
...,...,...,...,...,...
197046,1614636954926870,-12.359808,-11.200122,-4.242008,Forward Lunges on Bosu
197047,1614636954942870,-7.965209,-11.810483,-1.434348,Forward Lunges on Bosu
197048,1614636954958870,1.312276,-13.824674,0.518807,Forward Lunges on Bosu
197049,1614636954974869,7.721065,-16.632334,0.579843,Forward Lunges on Bosu
197050,1614636954990869,10.650797,-19.256886,0.274662,Forward Lunges on Bosu

In [21]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=16, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=17, second=55)
end_ts=int(end.timestamp() * 1e6)

DF17= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

<ipython-input-21-6adae08cd25e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
200801,1614637015004768,16.021973,-7.476921,-5.157549,Split squart left on Bosu
200802,1614637015020768,18.036164,-5.035477,-6.012055,Split squart left on Bosu
200803,1614637015036767,16.815442,-3.265431,-7.232776,Split squart left on Bosu
200804,1614637015052766,16.571298,-2.410925,-8.758679,Split squart left on Bosu
200805,1614637015068766,15.899901,-2.471962,-10.528725,Split squart left on Bosu
...,...,...,...,...,...
204546,1614637074922964,-23.590448,78.950179,47.211414,Split squart left on Bosu
204547,1614637074938964,-4.913405,77.302205,51.606012,Split squart left on Bosu
204548,1614637074954963,19.989319,74.128328,52.521553,Split squart left on Bosu
204549,1614637074970963,38.239109,68.574044,49.286641,Split squart left on Bosu
204550,1614637074986963,47.089342,63.324941,43.610285,Split squart left on Bosu

In [22]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=19, second=21)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=20, second=21)
end_ts=int(end.timestamp() * 1e6)

DF18= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

<ipython-input-22-e19844cdc036>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
209926,1614637161000967,4.242008,-8.758679,-11.017014,Split squart right on Bosu
209927,1614637161016966,6.378271,-10.223545,-12.970169,Split squart right on Bosu
209928,1614637161032966,9.674220,-11.688411,-14.679179,Split squart right on Bosu
209929,1614637161048966,11.505303,-13.275349,-16.876478,Split squart right on Bosu
209930,1614637161064966,11.566339,-14.373999,-17.975128,Split squart right on Bosu
...,...,...,...,...,...
213672,1614637220935955,1.373312,3.326467,-1.617456,Split squart right on Bosu
213673,1614637220951954,0.518807,4.547189,-0.579843,Split squart right on Bosu
213674,1614637220967954,1.678492,4.669261,-0.457771,Split squart right on Bosu
213675,1614637220983954,-1.312276,3.692683,-0.579843,Split squart right on Bosu
213676,1614637220999954,-6.134127,3.326467,-0.396735,Split squart right on Bosu

In [23]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=23, second=9)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=24, second=9)
end_ts=int(end.timestamp() * 1e6)

DF19= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

<ipython-input-23-684b72347a9e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
224176,1614637389000480,-75.226978,-6.561379,26.642252,plank pie on Bosu
224177,1614637389016481,-50.690471,-17.486839,24.078737,plank pie on Bosu
224178,1614637389032481,-42.206455,-7.537957,9.185931,plank pie on Bosu
224179,1614637389048481,-40.253300,2.838178,-2.777142,plank pie on Bosu
224180,1614637389064514,-52.704662,7.476921,-1.434348,plank pie on Bosu
...,...,...,...,...,...
227921,1614637448920968,-30.731670,-12.420844,59.601740,plank pie on Bosu
227922,1614637448936968,-35.065232,-16.937514,57.465476,plank pie on Bosu
227923,1614637448952969,-37.445640,-16.876478,56.916152,plank pie on Bosu
227924,1614637448968969,-31.891356,-20.416571,57.709621,plank pie on Bosu
227925,1614637448984969,-21.881437,-26.215000,56.733043,plank pie on Bosu

In [24]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=25, second=24)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=26, second=24)
end_ts=int(end.timestamp() * 1e6)

DF20= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

<ipython-input-24-852bfb15d311>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
232614,1614637524009404,30.304417,-13.153277,-15.716793,plank top on Bosu
232615,1614637524025404,12.542916,-11.810483,-26.031891,plank top on Bosu
232616,1614637524041404,9.857328,-16.144045,-30.731670,plank top on Bosu
232617,1614637524057405,7.476921,-21.759365,-31.586175,plank top on Bosu
232618,1614637524073405,8.270390,-23.956664,-30.548562,plank top on Bosu
...,...,...,...,...,...
236359,1614637583930042,-12.787060,-3.692683,6.561379,plank top on Bosu
236360,1614637583946045,-4.791333,-3.143359,7.965209,plank top on Bosu
236361,1614637583962045,0.640879,-2.471962,8.941787,plank top on Bosu
236362,1614637583978045,0.091554,-1.739528,12.115663,plank top on Bosu
236363,1614637583994045,0.396735,-1.312276,10.345617,plank top on Bosu

In [25]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=27, second=35)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=28, second=35)
end_ts=int(end.timestamp() * 1e6)

DF21= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

<ipython-input-25-cb68e292d666>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
240801,1614637655002114,2.349889,1.678492,1.556420,dips on Bosu
240802,1614637655018115,9.735256,2.471962,3.021286,dips on Bosu
240803,1614637655034115,13.824674,1.983673,1.739528,dips on Bosu
240804,1614637655050115,13.519493,1.373312,-1.861601,dips on Bosu
240805,1614637655066115,4.608225,1.068132,-5.218585,dips on Bosu
...,...,...,...,...,...
244546,1614637714922143,-7.171740,40.314336,-5.279622,dips on Bosu
244547,1614637714938143,-3.570611,37.628748,-2.471962,dips on Bosu
244548,1614637714954143,-1.251240,33.173114,-0.640879,dips on Bosu
244549,1614637714970143,1.373312,29.022660,-2.105745,dips on Bosu
244550,1614637714986144,2.960250,27.252613,-4.913405,dips on Bosu

In [26]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=33, second=32)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=34, second=32)
end_ts=int(end.timestamp() * 1e6)

DF22= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

<ipython-input-26-1227f9f501be>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
263114,1614638012010960,95.735103,-152.498665,-6.866560,moveforward backward on Bosu
263115,1614638012026960,90.730144,-154.390784,-7.537957,moveforward backward on Bosu
263116,1614638012042961,85.236896,-154.818036,-8.148318,moveforward backward on Bosu
263117,1614638012058961,79.865721,-153.292134,-9.124895,moveforward backward on Bosu
263118,1614638012074961,77.790494,-148.897536,-9.674220,moveforward backward on Bosu
...,...,...,...,...,...
266859,1614638071930988,94.636454,-191.500725,2.349889,moveforward backward on Bosu
266860,1614638071947021,92.988479,-199.618524,3.509575,moveforward backward on Bosu
266861,1614638071963021,94.453346,-209.140154,5.828946,moveforward backward on Bosu
266862,1614638071979022,91.828794,-220.981155,9.063859,moveforward backward on Bosu
266863,1614638071995022,78.767071,-239.963378,9.063859,moveforward backward on Bosu

In [27]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=37, second=34)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=38, second=34)
end_ts=int(end.timestamp() * 1e6)

DF23= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

<ipython-input-27-7fff4b8f5380>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
278239,1614638254010578,34.271763,-150.789654,29.388876,Left leg Hip ups on Bosu
278240,1614638254026580,26.337072,-136.202029,25.787747,Left leg Hip ups on Bosu
278241,1614638254042581,14.373999,-127.290761,19.623102,Left leg Hip ups on Bosu
278242,1614638254058581,9.308003,-122.529946,10.772869,Left leg Hip ups on Bosu
278243,1614638254074581,13.824674,-116.731518,6.378271,Left leg Hip ups on Bosu
...,...,...,...,...,...
281984,1614638313930240,-5.828946,-1.800565,2.227817,Left leg Hip ups on Bosu
281985,1614638313946240,-2.044709,-0.885023,-2.960250,Left leg Hip ups on Bosu
281986,1614638313962240,-3.936828,0.030518,-5.767910,Left leg Hip ups on Bosu
281987,1614638313978240,-9.185931,0.152590,-6.927596,Left leg Hip ups on Bosu
281988,1614638313994239,-11.017014,-0.701915,-8.392462,Left leg Hip ups on Bosu

In [28]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=38, second=37)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=39, second=37)
end_ts=int(end.timestamp() * 1e6)

DF24= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

<ipython-input-28-4d5cadf793a1>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
282176,1614638317002212,109.956512,24.994278,-7.598993,right leg Hip ups on Bosu
282177,1614638317018212,94.575418,10.833906,-9.124895,right leg Hip ups on Bosu
282178,1614638317034212,21.271077,-7.049668,-12.237736,right leg Hip ups on Bosu
282179,1614638317050212,-10.467689,-12.176699,-10.589761,right leg Hip ups on Bosu
282180,1614638317066223,24.078737,-6.683452,8.209354,right leg Hip ups on Bosu
...,...,...,...,...,...
285921,1614638376921517,5.523766,-1.800565,0.518807,right leg Hip ups on Bosu
285922,1614638376937517,4.425116,-5.279622,0.640879,right leg Hip ups on Bosu
285923,1614638376953517,5.157549,-5.035477,1.007095,right leg Hip ups on Bosu
285924,1614638376969516,17.486839,-1.007095,1.312276,right leg Hip ups on Bosu
285925,1614638376985516,21.454185,1.312276,1.434348,right leg Hip ups on Bosu

In [29]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=41, second=15)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=42, second=15)
end_ts=int(end.timestamp() * 1e6)

DF25= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

<ipython-input-29-a540218100cb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
292051,1614638475001015,1.739528,-37.384604,10.650797,V-Shift Swift on Bosu
292052,1614638475017015,-4.486152,-35.065232,9.613184,V-Shift Swift on Bosu
292053,1614638475033015,0.457771,-30.609598,9.674220,V-Shift Swift on Bosu
292054,1614638475049016,3.936828,-26.153964,5.767910,V-Shift Swift on Bosu
292055,1614638475065016,8.209354,-21.515221,1.739528,V-Shift Swift on Bosu
...,...,...,...,...,...
295796,1614638534920639,-6.683452,-7.843137,-1.861601,V-Shift Swift on Bosu
295797,1614638534936638,-7.965209,-13.702602,-4.058900,V-Shift Swift on Bosu
295798,1614638534952638,-13.519493,-22.552834,-9.613184,V-Shift Swift on Bosu
295799,1614638534968638,-23.163195,-32.928969,-17.486839,V-Shift Swift on Bosu
295800,1614638534984649,-22.308690,-43.183032,-24.567025,V-Shift Swift on Bosu

In [30]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=46, second=32)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=47, second=2)
end_ts=int(end.timestamp() * 1e6)

DF26= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

<ipython-input-30-916a4eaa5c39>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
311864,1614638792005039,-16.205081,12.664988,-1.251240,Freestyle Boxing
311865,1614638792021039,-15.350576,18.219272,8.941787,Freestyle Boxing
311866,1614638792037038,-14.923323,27.740902,17.303731,Freestyle Boxing
311867,1614638792053038,-18.524453,38.666361,23.224231,Freestyle Boxing
311868,1614638792069038,-20.599680,44.342718,29.327840,Freestyle Boxing
...,...,...,...,...,...
313734,1614638821924253,24.139773,-15.716793,-6.317235,Freestyle Boxing
313735,1614638821940253,22.980087,-20.477607,-2.166781,Freestyle Boxing
313736,1614638821956253,18.219272,-21.149004,1.495384,Freestyle Boxing
313737,1614638821972252,11.383230,-17.608911,6.866560,Freestyle Boxing
313738,1614638821988252,1.861601,-13.092241,12.848096,Freestyle Boxing

In [31]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=47, second=16)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=47, second=46)
end_ts=int(end.timestamp() * 1e6)

DF27= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

<ipython-input-31-92c4cac6bc70>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
314614,1614638836003812,-9.124895,25.970855,82.368200,Left_Right_Punches_flip
314615,1614638836019812,-6.378271,12.115663,72.846571,Left_Right_Punches_flip
314616,1614638836035812,-12.603952,-1.739528,56.855116,Left_Right_Punches_flip
314617,1614638836051812,-21.332113,-16.510262,36.346990,Left_Right_Punches_flip
314618,1614638836067812,-34.332799,-33.173114,14.312963,Left_Right_Punches_flip
...,...,...,...,...,...
316484,1614638865922792,37.384604,42.938888,-5.951019,Left_Right_Punches_flip
316485,1614638865938791,34.210727,52.277409,-7.354849,Left_Right_Punches_flip
316486,1614638865954791,36.896315,60.700389,-10.223545,Left_Right_Punches_flip
316487,1614638865970790,43.060960,69.977874,-12.787060,Left_Right_Punches_flip
316488,1614638865986789,47.028305,75.959411,-15.045396,Left_Right_Punches_flip

In [32]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=48, second=26)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=48, second=56)
end_ts=int(end.timestamp() * 1e6)

DF28= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

<ipython-input-32-d75b5df38f45>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
318989,1614638906001202,30.548562,-161.837186,-2.105745,left_Right_Punch
318990,1614638906017201,24.078737,-185.091936,-1.129168,left_Right_Punch
318991,1614638906033200,-5.035477,-205.905241,1.434348,left_Right_Punch
318992,1614638906049200,-38.056001,-225.741970,1.739528,left_Right_Punch
318993,1614638906065199,-65.766384,-243.808652,2.532998,left_Right_Punch
...,...,...,...,...,...
320860,1614638935935943,-2.532998,-19.317922,13.519493,left_Right_Punch
320861,1614638935951943,1.190204,-21.881437,13.031205,left_Right_Punch
320862,1614638935967942,1.312276,-20.294499,15.594720,left_Right_Punch
320863,1614638935983941,-1.922637,-17.242695,19.867247,left_Right_Punch
320864,1614638935999940,-5.462730,-15.289540,24.078737,left_Right_Punch

In [33]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=49, second=31)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=50, second=1)
end_ts=int(end.timestamp() * 1e6)

DF29= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

<ipython-input-33-3d7f9acec8fc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
323052,1614638971006292,17.730983,142.549783,103.486687,one_twos
323053,1614638971022291,23.468376,147.371633,110.444800,one_twos
323054,1614638971038291,23.773556,151.827268,113.435569,one_twos
323055,1614638971054290,26.031891,156.954299,114.961471,one_twos
323056,1614638971070289,28.900587,159.761959,113.496605,one_twos
...,...,...,...,...,...
324922,1614639000924821,19.745174,36.469062,16.327153,one_twos
324923,1614639000940820,20.294499,33.539330,11.078050,one_twos
324924,1614639000956819,21.820401,32.440681,3.448539,one_twos
324925,1614639000972818,23.407340,31.647211,-4.669261,one_twos
324926,1614639000988818,24.444953,27.557794,-10.223545,one_twos

In [34]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=56, second=22)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=56, second=52)
end_ts=int(end.timestamp() * 1e6)

DF30= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

<ipython-input-34-22e49b85a5da>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
348741,1614639382005989,120.515755,-358.495460,-225.803006,hooks
348742,1614639382021988,99.336233,-314.610513,-186.923018,hooks
348743,1614639382037988,72.724498,-263.218128,-79.072251,hooks
348744,1614639382053987,193.942168,-111.604486,-26.642252,hooks
348745,1614639382069986,212.314031,-1.373312,-38.971542,hooks
...,...,...,...,...,...
350611,1614639411924466,39.093614,59.967956,-13.153277,hooks
350612,1614639411940466,-61.493858,0.823987,-18.158236,hooks
350613,1614639411956465,-158.175021,-37.445640,-46.478981,hooks
350614,1614639411972464,-153.902495,-40.314336,-60.395209,hooks
350615,1614639411988464,-107.148852,-29.144732,-63.080797,hooks

In [35]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=57, second=36)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=58, second=6)
end_ts=int(end.timestamp() * 1e6)

DF31= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

<ipython-input-35-de95453b069c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
353366,1614639456002307,58.258946,-85.420005,-105.745022,Upper_cuts
353367,1614639456018306,58.442054,-94.087129,-84.077211,Upper_cuts
353368,1614639456034305,48.371099,-108.674754,-63.630121,Upper_cuts
353369,1614639456050305,30.304417,-125.337606,-47.577630,Upper_cuts
353370,1614639456066304,13.641566,-138.643473,-35.492485,Upper_cuts
...,...,...,...,...,...
355236,1614639485920906,105.622950,-55.146105,-33.600366,Upper_cuts
355237,1614639485936905,163.973449,-62.287327,-58.503090,Upper_cuts
355238,1614639485952904,212.985428,-73.823148,-74.189364,Upper_cuts
355239,1614639485968904,240.939956,-95.735103,-79.926757,Upper_cuts
355240,1614639485984924,248.447395,-111.543450,-80.109865,Upper_cuts

In [36]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=58, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=22, minute=59, second=21)
end_ts=int(end.timestamp() * 1e6)

DF32= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

<ipython-input-36-7bf0b3c45ee8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
358054,1614639531006278,-10.711833,-42.023346,39.093614,run
358055,1614639531022277,30.670634,-20.538643,34.088655,run
358056,1614639531038276,71.442741,-7.598993,29.083696,run
358057,1614639531054276,73.090715,-9.430076,25.604639,run
358058,1614639531070275,46.662089,-16.754406,20.477607,run
...,...,...,...,...,...
359924,1614639560924409,-34.576944,66.193637,63.935302,run
359925,1614639560940409,-23.468376,73.395895,83.405814,run
359926,1614639560956408,-24.933242,82.246128,110.505837,run
359927,1614639560972407,-56.244755,65.705348,147.249561,run
359928,1614639560988407,-94.026093,67.780575,151.155871,run

In [37]:
start=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=0, second=55)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=1, hour=23, minute=1, second=25)
end_ts=int(end.timestamp() * 1e6)

DF33= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

<ipython-input-37-4d2dd6dd4003>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
365805,1614639655011571,51.178759,-143.099107,74.677653,Punch_down_Up_Hooks
365806,1614639655027569,79.743648,-158.297093,58.686198,Punch_down_Up_Hooks
365807,1614639655043568,93.904021,-163.790341,36.224918,Punch_down_Up_Hooks
365808,1614639655059566,103.364614,-157.137407,15.960937,Punch_down_Up_Hooks
365809,1614639655075564,104.402228,-142.244602,-1.129168,Punch_down_Up_Hooks
...,...,...,...,...,...
367675,1614639684927994,129.976349,51.911192,15.045396,Punch_down_Up_Hooks
367676,1614639684943992,134.798199,73.579004,6.317235,Punch_down_Up_Hooks
367677,1614639684959991,134.187839,81.940948,-2.532998,Punch_down_Up_Hooks
367678,1614639684975989,132.478828,73.273823,-9.063859,Punch_down_Up_Hooks
367679,1614639684991987,131.502251,53.803311,-15.533684,Punch_down_Up_Hooks

In [38]:
sub04_final_hand_gyro=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub04_final_hand_gyro

,Timestamp (microseconds),Gyro X (°/s),Gyro Y (°/s),Gyro Z (°/s),Activity_Label
0,1614633910007185,3.265431,-17.730983,-142.854963,Forward and backward step
1,1614633910023184,-5.218585,-19.806210,-134.981308,Forward and backward step
2,1614633910039184,-12.848096,-19.989319,-131.136034,Forward and backward step
3,1614633910055183,-22.980087,-19.928283,-130.647745,Forward and backward step
4,1614633910071182,-30.670634,-23.956664,-131.074998,Forward and backward step
...,...,...,...,...,...
183813,1614639684927994,129.976349,51.911192,15.045396,Punch_down_Up_Hooks
183814,1614639684943992,134.798199,73.579004,6.317235,Punch_down_Up_Hooks
183815,1614639684959991,134.187839,81.940948,-2.532998,Punch_down_Up_Hooks
183816,1614639684975989,132.478828,73.273823,-9.063859,Punch_down_Up_Hooks
183817,1614639684991987,131.502251,53.803311,-15.533684,Punch_down_Up_Hooks

In [39]:
sub04_final_hand_gyro.to_csv('final_cleaned_hand_gyro-sub04.csv-sub04')