In [1]:
from datetime import datetime
import time
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('/Users/shreyasaswar/HARDataset/EXTRACTION/Sub06/Chest/elec.csv')

In [3]:
df1

         Timestamp (microseconds)  Sample (V)
0                1614701951186859    0.002446
1                1614701951190864    0.002373
2                1614701951194870    0.002323
3                1614701951198875    0.002274
4                1614701951202880    0.002237
...                           ...         ...
1372617          1614707452166582    0.001394
1372618          1614707452170589    0.001499
1372619          1614707452174596    0.001628
1372620          1614707452178604    0.001751
1372621          1614707452182611    0.001788

[1372622 rows x 2 columns]

In [4]:
pd.Timestamp(df1['Timestamp (microseconds)'][0], unit='us')

Timestamp('2021-03-02 16:19:11.186859')

In [5]:
start = pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=20, second=11)
start_ts = int(start.timestamp() * 1e6)

end = pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=21, second=11)
end_ts = int(end.timestamp() * 1e6)

DF1 = df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF1['Activity_Label'] = 'Forward and backward step'
DF1

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/1467598705.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['Activity_Label'] = 'Forward and backward step'

       Timestamp (microseconds)  Sample (V)             Activity_Label
14923          1614702011002789    0.002071  Forward and backward step
14924          1614702011006797    0.002071  Forward and backward step
14925          1614702011010806    0.002065  Forward and backward step
14926          1614702011014814    0.002065  Forward and backward step
14927          1614702011018822    0.002059  Forward and backward step
...                         ...         ...                        ...
29886          1614702070981518    0.001837  Forward and backward step
29887          1614702070985527    0.001843  Forward and backward step
29888          1614702070989536    0.001849  Forward and backward step
29889          1614702070993545    0.001862  Forward and backward step
29890          1614702070997497    0.001862  Forward and backward step

[14968 rows x 3 columns]

In [6]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=21, second=29)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=22, second=29)
end_ts=int(end.timestamp() * 1e6)

DF2= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF2['Activity_Label']='Sideward step'
DF2

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3605118494.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['Activity_Label']='Sideward step'

       Timestamp (microseconds)  Sample (V) Activity_Label
34382          1614702089003460    0.001794  Sideward step
34383          1614702089007468    0.001800  Sideward step
34384          1614702089011476    0.001806  Sideward step
34385          1614702089015484    0.001788  Sideward step
34386          1614702089019493    0.001776  Sideward step
...                         ...         ...            ...
49345          1614702148981433    0.002016  Sideward step
49346          1614702148985441    0.002003  Sideward step
49347          1614702148989449    0.001997  Sideward step
49348          1614702148993457    0.002016  Sideward step
49349          1614702148997466    0.002028  Sideward step

[14968 rows x 3 columns]

In [7]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=23, second=58)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=24, second=58)
end_ts=int(end.timestamp() * 1e6)

DF3= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF3['Activity_Label']='Pushups'
DF3

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/1405272342.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF3['Activity_Label']='Pushups'

       Timestamp (microseconds)  Sample (V) Activity_Label
71554          1614702238003915    0.001893        Pushups
71555          1614702238007924    0.001893        Pushups
71556          1614702238011932    0.001893        Pushups
71557          1614702238015940    0.001905        Pushups
71558          1614702238019949    0.001905        Pushups
...                         ...         ...            ...
86517          1614702297982010    0.001997        Pushups
86518          1614702297986019    0.002003        Pushups
86519          1614702297990027    0.001985        Pushups
86520          1614702297994035    0.001991        Pushups
86521          1614702297998044    0.001991        Pushups

[14968 rows x 3 columns]

In [8]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=25, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=26, second=51)
end_ts=int(end.timestamp() * 1e6)

DF4= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF4['Activity_Label']='Hip raise step with punches in the air'
DF4

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3130744190.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF4['Activity_Label']='Hip raise step with punches in the air'

,Timestamp (microseconds),Sample (V),Activity_Label
99744,1614702351001283,0.001923,Hip raise step with punches in the air
99745,1614702351005292,0.001905,Hip raise step with punches in the air
99746,1614702351009300,0.001899,Hip raise step with punches in the air
99747,1614702351013308,0.001899,Hip raise step with punches in the air
99748,1614702351017316,0.001893,Hip raise step with punches in the air
...,...,...,...
114707,1614702410981222,0.002317,Hip raise step with punches in the air
114708,1614702410985231,0.002317,Hip raise step with punches in the air
114709,1614702410989240,0.002336,Hip raise step with punches in the air
114710,1614702410993249,0.002348,Hip raise step with punches in the air
114711,1614702410997257,0.002336,Hip raise step with punches in the air

In [9]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=28, second=58)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=29, second=58)
end_ts=int(end.timestamp() * 1e6)

DF5= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF5['Activity_Label']='Front and back scooter'
DF5

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/401023599.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['Activity_Label']='Front and back scooter'

        Timestamp (microseconds)  Sample (V)          Activity_Label
146393          1614702538003977    0.001954  Front and back scooter
146394          1614702538007986    0.001960  Front and back scooter
146395          1614702538011994    0.001948  Front and back scooter
146396          1614702538016003    0.001948  Front and back scooter
146397          1614702538020012    0.001942  Front and back scooter
...                          ...         ...                     ...
161354          1614702597980076    0.001923  Front and back scooter
161355          1614702597984085    0.001917  Front and back scooter
161356          1614702597988094    0.001911  Front and back scooter
161357          1614702597992103    0.001905  Front and back scooter
161358          1614702597996111    0.001911  Front and back scooter

[14966 rows x 3 columns]

In [10]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=32, second=41)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=33, second=41)
end_ts=int(end.timestamp() * 1e6)

DF6= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF6['Activity_Label']='Belly Scooter'
DF6

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/918887502.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF6['Activity_Label']='Belly Scooter'

        Timestamp (microseconds)  Sample (V) Activity_Label
202020          1614702761000321    0.002022  Belly Scooter
202021          1614702761004330    0.002046  Belly Scooter
202022          1614702761008339    0.002046  Belly Scooter
202023          1614702761012347    0.002034  Belly Scooter
202024          1614702761016356    0.002028  Belly Scooter
...                          ...         ...            ...
216984          1614702820983869    0.001966  Belly Scooter
216985          1614702820987878    0.002003  Belly Scooter
216986          1614702820991887    0.001991  Belly Scooter
216987          1614702820995895    0.001917  Belly Scooter
216988          1614702820999904    0.001874  Belly Scooter

[14969 rows x 3 columns]

In [11]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=34, second=25)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=35, second=25)
end_ts=int(end.timestamp() * 1e6)

DF7= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF7['Activity_Label']='Circular Scooter'
DF7

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3491516695.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF7['Activity_Label']='Circular Scooter'

        Timestamp (microseconds)  Sample (V)    Activity_Label
227966          1614702865003847    0.001997  Circular Scooter
227967          1614702865007855    0.001991  Circular Scooter
227968          1614702865011863    0.001973  Circular Scooter
227969          1614702865015872    0.001960  Circular Scooter
227970          1614702865019880    0.001979  Circular Scooter
...                          ...         ...               ...
242930          1614702924983387    0.002016  Circular Scooter
242931          1614702924987395    0.002040  Circular Scooter
242932          1614702924991403    0.002065  Circular Scooter
242933          1614702924995411    0.002040  Circular Scooter
242934          1614702924999420    0.002003  Circular Scooter

[14969 rows x 3 columns]

In [12]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=37, second=48)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=38, second=48)
end_ts=int(end.timestamp() * 1e6)

DF8= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF8['Activity_Label']='Cycling Slow'
DF8

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3456713375.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF8['Activity_Label']='Cycling Slow'

        Timestamp (microseconds)  Sample (V) Activity_Label
278611          1614703068003333    0.001923   Cycling Slow
278612          1614703068007341    0.001911   Cycling Slow
278613          1614703068011349    0.001917   Cycling Slow
278614          1614703068015358    0.001899   Cycling Slow
278615          1614703068019366    0.001886   Cycling Slow
...                          ...         ...            ...
293574          1614703127981672    0.001837   Cycling Slow
293575          1614703127985680    0.001819   Cycling Slow
293576          1614703127989688    0.001837   Cycling Slow
293577          1614703127993697    0.001843   Cycling Slow
293578          1614703127997705    0.001849   Cycling Slow

[14968 rows x 3 columns]

In [13]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=38, second=49)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=39, second=49)
end_ts=int(end.timestamp() * 1e6)

DF9= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF9['Activity_Label']='Cycling Fast'
DF9

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/4248853590.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF9['Activity_Label']='Cycling Fast'

        Timestamp (microseconds)  Sample (V) Activity_Label
293829          1614703129003790    0.001640   Cycling Fast
293830          1614703129007799    0.001646   Cycling Fast
293831          1614703129011807    0.001646   Cycling Fast
293832          1614703129015815    0.001646   Cycling Fast
293833          1614703129019824    0.001646   Cycling Fast
...                          ...         ...            ...
308793          1614703188980426    0.001917   Cycling Fast
308794          1614703188984434    0.001929   Cycling Fast
308795          1614703188988442    0.001923   Cycling Fast
308796          1614703188992449    0.001905   Cycling Fast
308797          1614703188996457    0.001905   Cycling Fast

[14969 rows x 3 columns]

In [14]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=42, second=57)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=43, second=57)
end_ts=int(end.timestamp() * 1e6)

DF10= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF10['Activity_Label']='Medicine_ball'
DF10

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3066484689.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF10['Activity_Label']='Medicine_ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
355707          1614703377000527    0.001985  Medicine_ball
355708          1614703377004534    0.002071  Medicine_ball
355709          1614703377008542    0.002102  Medicine_ball
355710          1614703377012550    0.002065  Medicine_ball
355711          1614703377016558    0.002046  Medicine_ball
...                          ...         ...            ...
370674          1614703436983626    0.002133  Medicine_ball
370675          1614703436987634    0.002133  Medicine_ball
370676          1614703436991642    0.002102  Medicine_ball
370677          1614703436995649    0.002096  Medicine_ball
370678          1614703436999657    0.002157  Medicine_ball

[14972 rows x 3 columns]

In [15]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=45, second=54)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=46, second=54)
end_ts=int(end.timestamp() * 1e6)

DF11= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF11['Activity_Label']='Medicine ball with burpies'
DF11

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/320470156.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF11['Activity_Label']='Medicine ball with burpies'

        Timestamp (microseconds)  Sample (V)              Activity_Label
399874          1614703554002349    0.001776  Medicine ball with burpies
399875          1614703554006357    0.001763  Medicine ball with burpies
399876          1614703554010364    0.001745  Medicine ball with burpies
399877          1614703554014371    0.001732  Medicine ball with burpies
399878          1614703554018379    0.001714  Medicine ball with burpies
...                          ...         ...                         ...
414841          1614703613980402    0.001616  Medicine ball with burpies
414842          1614703613984409    0.001874  Medicine ball with burpies
414843          1614703613988416    0.002009  Medicine ball with burpies
414844          1614703613992424    0.002022  Medicine ball with burpies
414845          1614703613996431    0.002046  Medicine ball with burpies

[14972 rows x 3 columns]

In [16]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=48, second=52)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=49, second=52)
end_ts=int(end.timestamp() * 1e6)

DF12= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF12['Activity_Label']='punch ball'
DF12

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/94154255.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF12['Activity_Label']='punch ball'

        Timestamp (microseconds)  Sample (V) Activity_Label
444292          1614703732000003    0.001769     punch ball
444293          1614703732004011    0.001769     punch ball
444294          1614703732008018    0.001763     punch ball
444295          1614703732012025    0.001769     punch ball
444296          1614703732016033    0.001763     punch ball
...                          ...         ...            ...
459260          1614703791982521    0.002539     punch ball
459261          1614703791986528    0.002539     punch ball
459262          1614703791990535    0.002551     punch ball
459263          1614703791994543    0.002576     punch ball
459264          1614703791998550    0.002588     punch ball

[14973 rows x 3 columns]

In [17]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=53, second=54)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=54, second=44)
end_ts=int(end.timestamp() * 1e6)

DF13= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF13['Activity_Label']='Squarts Toe ups'
DF13

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/350091205.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF13['Activity_Label']='Squarts Toe ups'

        Timestamp (microseconds)  Sample (V)   Activity_Label
519652          1614704034000144    0.002145  Squarts Toe ups
519653          1614704034004151    0.002182  Squarts Toe ups
519654          1614704034008159    0.002194  Squarts Toe ups
519655          1614704034012167    0.002176  Squarts Toe ups
519656          1614704034016175    0.002169  Squarts Toe ups
...                          ...         ...              ...
532124          1614704083982724    0.002286  Squarts Toe ups
532125          1614704083986732    0.002256  Squarts Toe ups
532126          1614704083990739    0.002231  Squarts Toe ups
532127          1614704083994747    0.002231  Squarts Toe ups
532128          1614704083998755    0.002225  Squarts Toe ups

[12477 rows x 3 columns]

In [18]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=57, second=4)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=58, second=4)
end_ts=int(end.timestamp() * 1e6)

DF14= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF14['Activity_Label']='Weight lifts'
DF14

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/4131406319.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF14['Activity_Label']='Weight lifts'

        Timestamp (microseconds)  Sample (V) Activity_Label
567063          1614704224002755    0.001837   Weight lifts
567064          1614704224006763    0.001849   Weight lifts
567065          1614704224010771    0.001849   Weight lifts
567066          1614704224014779    0.001862   Weight lifts
567067          1614704224018787    0.001868   Weight lifts
...                          ...         ...            ...
582030          1614704283982730    0.001874   Weight lifts
582031          1614704283986738    0.001874   Weight lifts
582032          1614704283990745    0.001942   Weight lifts
582033          1614704283994753    0.001997   Weight lifts
582034          1614704283998760    0.002053   Weight lifts

[14972 rows x 3 columns]

In [19]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=16, minute=59, second=12)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=0, second=12)
end_ts=int(end.timestamp() * 1e6)

DF15= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF15['Activity_Label']='Heavy Weight lifts'
DF15

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/1701179341.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF15['Activity_Label']='Heavy Weight lifts'

        Timestamp (microseconds)  Sample (V)      Activity_Label
599003          1614704352000635    0.001991  Heavy Weight lifts
599004          1614704352004642    0.001991  Heavy Weight lifts
599005          1614704352008649    0.001979  Heavy Weight lifts
599006          1614704352012657    0.001973  Heavy Weight lifts
599007          1614704352016664    0.001960  Heavy Weight lifts
...                          ...         ...                 ...
613970          1614704411980426    0.001942  Heavy Weight lifts
613971          1614704411984434    0.001929  Heavy Weight lifts
613972          1614704411988441    0.001936  Heavy Weight lifts
613973          1614704411992448    0.001942  Heavy Weight lifts
613974          1614704411996456    0.001948  Heavy Weight lifts

[14972 rows x 3 columns]

In [20]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=1, second=24)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=2, second=24)
end_ts=int(end.timestamp() * 1e6)

DF16= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF16['Activity_Label']='Forward Lunges on Bosu'
DF16

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3834292623.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF16['Activity_Label']='Forward Lunges on Bosu'

        Timestamp (microseconds)  Sample (V)          Activity_Label
631942          1614704484003452    0.001936  Forward Lunges on Bosu
631943          1614704484007460    0.001942  Forward Lunges on Bosu
631944          1614704484011468    0.001991  Forward Lunges on Bosu
631945          1614704484015475    0.002059  Forward Lunges on Bosu
631946          1614704484019483    0.002139  Forward Lunges on Bosu
...                          ...         ...                     ...
646908          1614704543981079    0.001849  Forward Lunges on Bosu
646909          1614704543985087    0.001862  Forward Lunges on Bosu
646910          1614704543989094    0.001849  Forward Lunges on Bosu
646911          1614704543993102    0.001843  Forward Lunges on Bosu
646912          1614704543997110    0.001843  Forward Lunges on Bosu

[14971 rows x 3 columns]

In [21]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=3, second=56)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=4, second=56)
end_ts=int(end.timestamp() * 1e6)

DF17= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF17['Activity_Label']='Split squart left on Bosu'
DF17

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/1283130038.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF17['Activity_Label']='Split squart left on Bosu'

        Timestamp (microseconds)  Sample (V)             Activity_Label
669870          1614704636002030    0.001880  Split squart left on Bosu
669871          1614704636006038    0.001911  Split squart left on Bosu
669872          1614704636010046    0.001991  Split squart left on Bosu
669873          1614704636014053    0.002083  Split squart left on Bosu
669874          1614704636018061    0.002188  Split squart left on Bosu
...                          ...         ...                        ...
684837          1614704695983146    0.001831  Split squart left on Bosu
684838          1614704695987154    0.001837  Split squart left on Bosu
684839          1614704695991161    0.001837  Split squart left on Bosu
684840          1614704695995169    0.001837  Split squart left on Bosu
684841          1614704695999177    0.001843  Split squart left on Bosu

[14972 rows x 3 columns]

In [22]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=5, second=3)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=6, second=3)
end_ts=int(end.timestamp() * 1e6)

DF18= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF18['Activity_Label']='Split squart right on Bosu'
DF18

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2413034056.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF18['Activity_Label']='Split squart right on Bosu'

        Timestamp (microseconds)  Sample (V)              Activity_Label
686588          1614704703000361    0.001782  Split squart right on Bosu
686589          1614704703004369    0.001788  Split squart right on Bosu
686590          1614704703008377    0.001782  Split squart right on Bosu
686591          1614704703012385    0.001788  Split squart right on Bosu
686592          1614704703016392    0.001788  Split squart right on Bosu
...                          ...         ...                         ...
701555          1614704762981050    0.001862  Split squart right on Bosu
701556          1614704762985057    0.001862  Split squart right on Bosu
701557          1614704762989065    0.001868  Split squart right on Bosu
701558          1614704762993073    0.001874  Split squart right on Bosu
701559          1614704762997081    0.001874  Split squart right on Bosu

[14972 rows x 3 columns]

In [23]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=10, second=46)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=11, second=46)
end_ts=int(end.timestamp() * 1e6)

DF19= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF19['Activity_Label']='plank pie on Bosu'
DF19

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3004267059.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF19['Activity_Label']='plank pie on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
772177          1614705046001684    0.001929  plank pie on Bosu
772178          1614705046005691    0.001923  plank pie on Bosu
772179          1614705046009698    0.001929  plank pie on Bosu
772180          1614705046013706    0.001966  plank pie on Bosu
772181          1614705046017713    0.001991  plank pie on Bosu
...                          ...         ...                ...
787145          1614705105983163    0.001991  plank pie on Bosu
787146          1614705105987171    0.001991  plank pie on Bosu
787147          1614705105991178    0.001985  plank pie on Bosu
787148          1614705105995185    0.001985  plank pie on Bosu
787149          1614705105999193    0.001979  plank pie on Bosu

[14973 rows x 3 columns]

In [24]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=13, second=8)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=14, second=8)
end_ts=int(end.timestamp() * 1e6)

DF20= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF20['Activity_Label']='plank top on Bosu'
DF20

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3471018148.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF20['Activity_Label']='plank top on Bosu'

        Timestamp (microseconds)  Sample (V)     Activity_Label
807612          1614705188000103    0.001579  plank top on Bosu
807613          1614705188004110    0.001585  plank top on Bosu
807614          1614705188008117    0.001597  plank top on Bosu
807615          1614705188012125    0.001597  plank top on Bosu
807616          1614705188016132    0.001579  plank top on Bosu
...                          ...         ...                ...
822580          1614705247981033    0.001794  plank top on Bosu
822581          1614705247985040    0.001776  plank top on Bosu
822582          1614705247989048    0.001757  plank top on Bosu
822583          1614705247993055    0.001788  plank top on Bosu
822584          1614705247997062    0.001800  plank top on Bosu

[14973 rows x 3 columns]

In [25]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=17, second=5)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=18, second=5)
end_ts=int(end.timestamp() * 1e6)

DF21= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF21['Activity_Label']='dips on Bosu'
DF21

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2824986417.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF21['Activity_Label']='dips on Bosu'

        Timestamp (microseconds)  Sample (V) Activity_Label
866754          1614705425001361    0.001837   dips on Bosu
866755          1614705425005369    0.001843   dips on Bosu
866756          1614705425009376    0.001849   dips on Bosu
866757          1614705425013383    0.001831   dips on Bosu
866758          1614705425017391    0.001831   dips on Bosu
...                          ...         ...            ...
881721          1614705484981685    0.001769   dips on Bosu
881722          1614705484985693    0.001757   dips on Bosu
881723          1614705484989700    0.001763   dips on Bosu
881724          1614705484993708    0.001757   dips on Bosu
881725          1614705484997716    0.001763   dips on Bosu

[14972 rows x 3 columns]

In [26]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=18, second=51)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=19, second=51)
end_ts=int(end.timestamp() * 1e6)

DF22= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF22['Activity_Label']='moveforward backward on Bosu'
DF22

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/993683544.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['Activity_Label']='moveforward backward on Bosu'

        Timestamp (microseconds)  Sample (V)                Activity_Label
893205          1614705531003400    0.002219  moveforward backward on Bosu
893206          1614705531007408    0.002194  moveforward backward on Bosu
893207          1614705531011415    0.002194  moveforward backward on Bosu
893208          1614705531015422    0.002188  moveforward backward on Bosu
893209          1614705531019430    0.002176  moveforward backward on Bosu
...                          ...         ...                           ...
908172          1614705590981636    0.001652  moveforward backward on Bosu
908173          1614705590985643    0.001659  moveforward backward on Bosu
908174          1614705590989650    0.001659  moveforward backward on Bosu
908175          1614705590993658    0.001659  moveforward backward on Bosu
908176          1614705590997665    0.001659  moveforward backward on Bosu

[14972 rows x 3 columns]

In [27]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=25, second=42)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=26, second=42)
end_ts=int(end.timestamp() * 1e6)

DF23= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF23['Activity_Label']='Left leg Hip ups on Bosu'
DF23

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2655689294.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF23['Activity_Label']='Left leg Hip ups on Bosu'

         Timestamp (microseconds)  Sample (V)            Activity_Label
995766           1614705942002735    0.001794  Left leg Hip ups on Bosu
995767           1614705942006742    0.001788  Left leg Hip ups on Bosu
995768           1614705942010749    0.001776  Left leg Hip ups on Bosu
995769           1614705942014757    0.001788  Left leg Hip ups on Bosu
995770           1614705942018764    0.001788  Left leg Hip ups on Bosu
...                           ...         ...                       ...
1010734          1614706001982418    0.001837  Left leg Hip ups on Bosu
1010735          1614706001986425    0.001825  Left leg Hip ups on Bosu
1010736          1614706001990432    0.001831  Left leg Hip ups on Bosu
1010737          1614706001994440    0.001825  Left leg Hip ups on Bosu
1010738          1614706001998447    0.001831  Left leg Hip ups on Bosu

[14973 rows x 3 columns]

In [28]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=28, second=22)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=29, second=22)
end_ts=int(end.timestamp() * 1e6)

DF24= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF24['Activity_Label']='right leg Hip ups on Bosu'
DF24

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/4149294849.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF24['Activity_Label']='right leg Hip ups on Bosu'

         Timestamp (microseconds)  Sample (V)             Activity_Label
1035694          1614706102001899    0.001677  right leg Hip ups on Bosu
1035695          1614706102005907    0.001671  right leg Hip ups on Bosu
1035696          1614706102009914    0.001677  right leg Hip ups on Bosu
1035697          1614706102013921    0.001683  right leg Hip ups on Bosu
1035698          1614706102017929    0.001683  right leg Hip ups on Bosu
...                           ...         ...                        ...
1050662          1614706161982010    0.001720  right leg Hip ups on Bosu
1050663          1614706161986017    0.001732  right leg Hip ups on Bosu
1050664          1614706161990020    0.001732  right leg Hip ups on Bosu
1050665          1614706161994028    0.001720  right leg Hip ups on Bosu
1050666          1614706161998035    0.001726  right leg Hip ups on Bosu

[14973 rows x 3 columns]

In [29]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=31, second=13)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=32, second=13)
end_ts=int(end.timestamp() * 1e6)

DF25= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF25['Activity_Label']='V-Shift Swift on Bosu'
DF25

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3954647066.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF25['Activity_Label']='V-Shift Swift on Bosu'

         Timestamp (microseconds)  Sample (V)         Activity_Label
1078366          1614706273000564    0.001942  V-Shift Swift on Bosu
1078367          1614706273004572    0.001929  V-Shift Swift on Bosu
1078368          1614706273008579    0.001917  V-Shift Swift on Bosu
1078369          1614706273012586    0.001917  V-Shift Swift on Bosu
1078370          1614706273016594    0.001905  V-Shift Swift on Bosu
...                           ...         ...                    ...
1093334          1614706332983390    0.001332  V-Shift Swift on Bosu
1093335          1614706332987398    0.001376  V-Shift Swift on Bosu
1093336          1614706332991405    0.001357  V-Shift Swift on Bosu
1093337          1614706332995412    0.001339  V-Shift Swift on Bosu
1093338          1614706332999420    0.001369  V-Shift Swift on Bosu

[14973 rows x 3 columns]

In [30]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=37, second=24)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=37, second=54)
end_ts=int(end.timestamp() * 1e6)

DF26= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF26['Activity_Label']='Freestyle Boxing'
DF26

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2202540641.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF26['Activity_Label']='Freestyle Boxing'

         Timestamp (microseconds)  Sample (V)    Activity_Label
1170943          1614706644001924    0.001899  Freestyle Boxing
1170944          1614706644005931    0.001905  Freestyle Boxing
1170945          1614706644009939    0.001899  Freestyle Boxing
1170946          1614706644013946    0.001905  Freestyle Boxing
1170947          1614706644017953    0.001917  Freestyle Boxing
...                           ...         ...               ...
1178424          1614706673981144    0.001572  Freestyle Boxing
1178425          1614706673985151    0.001566  Freestyle Boxing
1178426          1614706673989158    0.001597  Freestyle Boxing
1178427          1614706673993166    0.001609  Freestyle Boxing
1178428          1614706673997173    0.001597  Freestyle Boxing

[7486 rows x 3 columns]

In [31]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=39, second=49)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=40, second=19)
end_ts=int(end.timestamp() * 1e6)

DF27= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF27['Activity_Label']='Left_Right_Punches_flip'
DF27

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/3375753314.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF27['Activity_Label']='Left_Right_Punches_flip'

         Timestamp (microseconds)  Sample (V)           Activity_Label
1207127          1614706789002790    0.002520  Left_Right_Punches_flip
1207128          1614706789006797    0.002508  Left_Right_Punches_flip
1207129          1614706789010805    0.002483  Left_Right_Punches_flip
1207130          1614706789014812    0.002453  Left_Right_Punches_flip
1207131          1614706789018819    0.002440  Left_Right_Punches_flip
...                           ...         ...                      ...
1214608          1614706818981098    0.001825  Left_Right_Punches_flip
1214609          1614706818985105    0.001825  Left_Right_Punches_flip
1214610          1614706818989112    0.001843  Left_Right_Punches_flip
1214611          1614706818993120    0.001862  Left_Right_Punches_flip
1214612          1614706818997127    0.001849  Left_Right_Punches_flip

[7486 rows x 3 columns]

In [32]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=41, second=23)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=41, second=53)
end_ts=int(end.timestamp() * 1e6)

DF28= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF28['Activity_Label']='left_Right_Punch'
DF28

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2128202255.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF28['Activity_Label']='left_Right_Punch'

         Timestamp (microseconds)  Sample (V)    Activity_Label
1230584          1614706883000145    0.002003  left_Right_Punch
1230585          1614706883004152    0.002003  left_Right_Punch
1230586          1614706883008159    0.002065  left_Right_Punch
1230587          1614706883012167    0.002114  left_Right_Punch
1230588          1614706883016174    0.002139  left_Right_Punch
...                           ...         ...               ...
1238066          1614706912981968    0.002108  left_Right_Punch
1238067          1614706912985975    0.002077  left_Right_Punch
1238068          1614706912989982    0.002053  left_Right_Punch
1238069          1614706912993990    0.002034  left_Right_Punch
1238070          1614706912997997    0.002022  left_Right_Punch

[7487 rows x 3 columns]

In [33]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=42, second=53)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=43, second=23)
end_ts=int(end.timestamp() * 1e6)

DF29= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF29['Activity_Label']='one_twos'
DF29

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/1610640975.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF29['Activity_Label']='one_twos'

         Timestamp (microseconds)  Sample (V) Activity_Label
1253044          1614706973001602    0.001979       one_twos
1253045          1614706973005609    0.001942       one_twos
1253046          1614706973009616    0.001899       one_twos
1253047          1614706973013624    0.001812       one_twos
1253048          1614706973017631    0.001868       one_twos
...                           ...         ...            ...
1260526          1614707002983638    0.001776       one_twos
1260527          1614707002987646    0.001776       one_twos
1260528          1614707002991653    0.001776       one_twos
1260529          1614707002995660    0.001776       one_twos
1260530          1614707002999668    0.001788       one_twos

[7487 rows x 3 columns]

In [34]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=44, second=17)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=44, second=47)
end_ts=int(end.timestamp() * 1e6)

DF30= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF30['Activity_Label']='hooks'
DF30

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2703087378.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF30['Activity_Label']='hooks'

         Timestamp (microseconds)  Sample (V) Activity_Label
1274006          1614707057001331    0.001757          hooks
1274007          1614707057005338    0.001757          hooks
1274008          1614707057009346    0.001757          hooks
1274009          1614707057013353    0.001757          hooks
1274010          1614707057017360    0.001745          hooks
...                           ...         ...            ...
1281488          1614707086983703    0.001308          hooks
1281489          1614707086987711    0.001283          hooks
1281490          1614707086991718    0.001271          hooks
1281491          1614707086995725    0.001259          hooks
1281492          1614707086999733    0.001265          hooks

[7487 rows x 3 columns]

In [35]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=45, second=28)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=45, second=58)
end_ts=int(end.timestamp() * 1e6)

DF31= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF31['Activity_Label']='Upper_cuts'
DF31

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2201849507.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF31['Activity_Label']='Upper_cuts'

         Timestamp (microseconds)  Sample (V) Activity_Label
1291724          1614707128002086    0.001862     Upper_cuts
1291725          1614707128006094    0.001856     Upper_cuts
1291726          1614707128010101    0.001849     Upper_cuts
1291727          1614707128014108    0.001849     Upper_cuts
1291728          1614707128018116    0.001837     Upper_cuts
...                           ...         ...            ...
1299205          1614707157980604    0.001776     Upper_cuts
1299206          1614707157984611    0.001745     Upper_cuts
1299207          1614707157988618    0.001714     Upper_cuts
1299208          1614707157992626    0.001696     Upper_cuts
1299209          1614707157996633    0.001689     Upper_cuts

[7486 rows x 3 columns]

In [36]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=47, second=22)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=47, second=52)
end_ts=int(end.timestamp() * 1e6)

DF32= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF32['Activity_Label']='run'
DF32

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2174027170.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF32['Activity_Label']='run'

         Timestamp (microseconds)  Sample (V) Activity_Label
1320172          1614707242001926    0.001936            run
1320173          1614707242005933    0.001936            run
1320174          1614707242009941    0.001929            run
1320175          1614707242013948    0.001929            run
1320176          1614707242017955    0.001942            run
...                           ...         ...            ...
1327653          1614707271981180    0.002379            run
1327654          1614707271985187    0.002428            run
1327655          1614707271989194    0.002428            run
1327656          1614707271993202    0.002379            run
1327657          1614707271997209    0.002336            run

[7486 rows x 3 columns]

In [37]:
start=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=48, second=36)
start_ts=int(start.timestamp() * 1e6)

end=pd.Timestamp(year=2021, month=3, day=2, hour=17, minute=49, second=6)
end_ts=int(end.timestamp() * 1e6)

DF33= df1.loc[(df1['Timestamp (microseconds)'] >=start_ts) & (df1['Timestamp (microseconds)']<=end_ts)]

DF33['Activity_Label']='Punch_down_Up_Hooks'
DF33

/var/folders/q7/2hlrtt8s33n8vg4p3xcc4z3m0000gn/T/ipykernel_7603/2835983749.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF33['Activity_Label']='Punch_down_Up_Hooks'

         Timestamp (microseconds)  Sample (V)       Activity_Label
1338638          1614707316001827    0.001973  Punch_down_Up_Hooks
1338639          1614707316005834    0.001985  Punch_down_Up_Hooks
1338640          1614707316009842    0.001979  Punch_down_Up_Hooks
1338641          1614707316013849    0.001985  Punch_down_Up_Hooks
1338642          1614707316017856    0.001985  Punch_down_Up_Hooks
...                           ...         ...                  ...
1346119          1614707345980592    0.002569  Punch_down_Up_Hooks
1346120          1614707345984600    0.002539  Punch_down_Up_Hooks
1346121          1614707345988607    0.002428  Punch_down_Up_Hooks
1346122          1614707345992614    0.002299  Punch_down_Up_Hooks
1346123          1614707345996622    0.002237  Punch_down_Up_Hooks

[7486 rows x 3 columns]

In [38]:
sub06_final_chest_elec=pd.concat ([DF1,DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, DF11, DF12, DF13, DF14, DF15, DF16, DF17, DF18, DF19, DF20, DF21, DF22, DF23, DF24, DF25, DF26, DF27, DF28, DF29, DF30, DF31, DF32, DF33], ignore_index=True)
sub06_final_chest_elec

        Timestamp (microseconds)  Sample (V)             Activity_Label
0               1614702011002789    0.002071  Forward and backward step
1               1614702011006797    0.002071  Forward and backward step
2               1614702011010806    0.002065  Forward and backward step
3               1614702011014814    0.002065  Forward and backward step
4               1614702011018822    0.002059  Forward and backward step
...                          ...         ...                        ...
431661          1614707345980592    0.002569        Punch_down_Up_Hooks
431662          1614707345984600    0.002539        Punch_down_Up_Hooks
431663          1614707345988607    0.002428        Punch_down_Up_Hooks
431664          1614707345992614    0.002299        Punch_down_Up_Hooks
431665          1614707345996622    0.002237        Punch_down_Up_Hooks

[431666 rows x 3 columns]

In [39]:
sub06_final_chest_elec.to_csv('final_cleaned_chest_elec.csv-sub06')